#!/bin/bash
# Rename flag images from old format to ISO 2-letter codes

echo "🚀 Flag Renaming Script"
echo "======================"
echo ""
echo "⚠️  IMPORTANT: Make a backup of your flags folder first!"
echo ""
echo "Run this script from your project root directory:"
echo "bash rename-flags.sh"
echo ""

# Navigate to flags directory
cd flags || { echo "❌ Error: flags directory not found!"; exit 1; }

echo "Starting flag renames..."
echo ""

# Rename flags
mv afghanistan.png AF.png 2>/dev/null && echo "✅ afghanistan.png → AF.png"
mv albania.png AL.png 2>/dev/null && echo "✅ albania.png → AL.png"
mv algeria.png DZ.png 2>/dev/null && echo "✅ algeria.png → DZ.png"
mv andorra.png AD.png 2>/dev/null && echo "✅ andorra.png → AD.png"
mv angola.png AO.png 2>/dev/null && echo "✅ angola.png → AO.png"
mv antigua-and-barbuda.png AG.png 2>/dev/null && echo "✅ antigua-and-barbuda.png → AG.png"
mv argentina.png AR.png 2>/dev/null && echo "✅ argentina.png → AR.png"
mv armenia.png AM.png 2>/dev/null && echo "✅ armenia.png → AM.png"
mv australia.png AU.png 2>/dev/null && echo "✅ australia.png → AU.png"
mv austria.png AT.png 2>/dev/null && echo "✅ austria.png → AT.png"
mv azerbaijan.png AZ.png 2>/dev/null && echo "✅ azerbaijan.png → AZ.png"
mv bahamas.png BS.png 2>/dev/null && echo "✅ bahamas.png → BS.png"
mv bahrain.png BH.png 2>/dev/null && echo "✅ bahrain.png → BH.png"
mv bangladesh.png BD.png 2>/dev/null && echo "✅ bangladesh.png → BD.png"
mv barbados.png BB.png 2>/dev/null && echo "✅ barbados.png → BB.png"
mv belarus.png BY.png 2>/dev/null && echo "✅ belarus.png → BY.png"
mv belgium.png BE.png 2>/dev/null && echo "✅ belgium.png → BE.png"
mv belize.png BZ.png 2>/dev/null && echo "✅ belize.png → BZ.png"
mv bolivia.png BO.png 2>/dev/null && echo "✅ bolivia.png → BO.png"
mv bosnia-and-herzegovina.png BA.png 2>/dev/null && echo "✅ bosnia-and-herzegovina.png → BA.png"
mv botswana.png BW.png 2>/dev/null && echo "✅ botswana.png → BW.png"
mv brazil.png BR.png 2>/dev/null && echo "✅ brazil.png → BR.png"
mv brunei.png BN.png 2>/dev/null && echo "✅ brunei.png → BN.png"
mv bulgaria.png BG.png 2>/dev/null && echo "✅ bulgaria.png → BG.png"
mv burkina-faso.png BF.png 2>/dev/null && echo "✅ burkina-faso.png → BF.png"
mv cambodia.png KH.png 2>/dev/null && echo "✅ cambodia.png → KH.png"
mv cameroon.png CM.png 2>/dev/null && echo "✅ cameroon.png → CM.png"
mv canada.png CA.png 2>/dev/null && echo "✅ canada.png → CA.png"
mv central-african-republic.png CF.png 2>/dev/null && echo "✅ central-african-republic.png → CF.png"
mv chad.png TD.png 2>/dev/null && echo "✅ chad.png → TD.png"
mv chile.png CL.png 2>/dev/null && echo "✅ chile.png → CL.png"
mv china.png CN.png 2>/dev/null && echo "✅ china.png → CN.png"
mv colombia.png CO.png 2>/dev/null && echo "✅ colombia.png → CO.png"
mv costa-rica.png CR.png 2>/dev/null && echo "✅ costa-rica.png → CR.png"
mv croatia.png HR.png 2>/dev/null && echo "✅ croatia.png → HR.png"
mv cuba.png CU.png 2>/dev/null && echo "✅ cuba.png → CU.png"
mv cyprus.png CY.png 2>/dev/null && echo "✅ cyprus.png → CY.png"
mv czech-republic.png CZ.png 2>/dev/null && echo "✅ czech-republic.png → CZ.png"
mv czechia.png CZ.png 2>/dev/null && echo "✅ czechia.png → CZ.png"
mv democratic-republic-of-the-congo.png CD.png 2>/dev/null && echo "✅ democratic-republic-of-the-congo.png → CD.png"
mv denmark.png DK.png 2>/dev/null && echo "✅ denmark.png → DK.png"
mv djibouti.png DJ.png 2>/dev/null && echo "✅ djibouti.png → DJ.png"
mv dominican-republic.png DO.png 2>/dev/null && echo "✅ dominican-republic.png → DO.png"
mv ecuador.png EC.png 2>/dev/null && echo "✅ ecuador.png → EC.png"
mv egypt.png EG.png 2>/dev/null && echo "✅ egypt.png → EG.png"
mv el-salvador.png SV.png 2>/dev/null && echo "✅ el-salvador.png → SV.png"
mv england.png GB-ENG.png 2>/dev/null && echo "✅ england.png → GB-ENG.png"
mv equatorial-guinea.png GQ.png 2>/dev/null && echo "✅ equatorial-guinea.png → GQ.png"
mv eritrea.png ER.png 2>/dev/null && echo "✅ eritrea.png → ER.png"
mv estonia.png EE.png 2>/dev/null && echo "✅ estonia.png → EE.png"
mv ethiopia.png ET.png 2>/dev/null && echo "✅ ethiopia.png → ET.png"
mv fiji.png FJ.png 2>/dev/null && echo "✅ fiji.png → FJ.png"
mv finland.png FI.png 2>/dev/null && echo "✅ finland.png → FI.png"
mv france.png FR.png 2>/dev/null && echo "✅ france.png → FR.png"
mv gabon.png GA.png 2>/dev/null && echo "✅ gabon.png → GA.png"
mv gambia.png GM.png 2>/dev/null && echo "✅ gambia.png → GM.png"
mv georgia.png GE.png 2>/dev/null && echo "✅ georgia.png → GE.png"
mv germany.png DE.png 2>/dev/null && echo "✅ germany.png → DE.png"
mv ghana.png GH.png 2>/dev/null && echo "✅ ghana.png → GH.png"
mv greece.png GR.png 2>/dev/null && echo "✅ greece.png → GR.png"
mv greenland.png GL.png 2>/dev/null && echo "✅ greenland.png → GL.png"
mv guatemala.png GT.png 2>/dev/null && echo "✅ guatemala.png → GT.png"
mv guinea.png GN.png 2>/dev/null && echo "✅ guinea.png → GN.png"
mv guinea-bissau.png GW.png 2>/dev/null && echo "✅ guinea-bissau.png → GW.png"
mv guyana.png GY.png 2>/dev/null && echo "✅ guyana.png → GY.png"
mv haiti.png HT.png 2>/dev/null && echo "✅ haiti.png → HT.png"
mv honduras.png HN.png 2>/dev/null && echo "✅ honduras.png → HN.png"
mv hong-kong.png HK.png 2>/dev/null && echo "✅ hong-kong.png → HK.png"
mv hungary.png HU.png 2>/dev/null && echo "✅ hungary.png → HU.png"
mv iceland.png IS.png 2>/dev/null && echo "✅ iceland.png → IS.png"
mv india.png IN.png 2>/dev/null && echo "✅ india.png → IN.png"
mv indonesia.png ID.png 2>/dev/null && echo "✅ indonesia.png → ID.png"
mv iran.png IR.png 2>/dev/null && echo "✅ iran.png → IR.png"
mv iraq.png IQ.png 2>/dev/null && echo "✅ iraq.png → IQ.png"
mv ireland.png IE.png 2>/dev/null && echo "✅ ireland.png → IE.png"
mv israel.png IL.png 2>/dev/null && echo "✅ israel.png → IL.png"
mv italy.png IT.png 2>/dev/null && echo "✅ italy.png → IT.png"
mv ivory-coast.png CI.png 2>/dev/null && echo "✅ ivory-coast.png → CI.png"
mv jamaica.png JM.png 2>/dev/null && echo "✅ jamaica.png → JM.png"
mv japan.png JP.png 2>/dev/null && echo "✅ japan.png → JP.png"
mv jordan.png JO.png 2>/dev/null && echo "✅ jordan.png → JO.png"
mv kazakhstan.png KZ.png 2>/dev/null && echo "✅ kazakhstan.png → KZ.png"
mv kenya.png KE.png 2>/dev/null && echo "✅ kenya.png → KE.png"
mv kiribati.png KI.png 2>/dev/null && echo "✅ kiribati.png → KI.png"
mv kosovo.png XK.png 2>/dev/null && echo "✅ kosovo.png → XK.png"
mv kuwait.png KW.png 2>/dev/null && echo "✅ kuwait.png → KW.png"
mv kyrgyzstan.png KG.png 2>/dev/null && echo "✅ kyrgyzstan.png → KG.png"
mv laos.png LA.png 2>/dev/null && echo "✅ laos.png → LA.png"
mv latvia.png LV.png 2>/dev/null && echo "✅ latvia.png → LV.png"
mv lebanon.png LB.png 2>/dev/null && echo "✅ lebanon.png → LB.png"
mv libya.png LY.png 2>/dev/null && echo "✅ libya.png → LY.png"
mv lithuania.png LT.png 2>/dev/null && echo "✅ lithuania.png → LT.png"
mv luxembourg.png LU.png 2>/dev/null && echo "✅ luxembourg.png → LU.png"
mv madagascar.png MG.png 2>/dev/null && echo "✅ madagascar.png → MG.png"
mv malawi.png MW.png 2>/dev/null && echo "✅ malawi.png → MW.png"
mv malaysia.png MY.png 2>/dev/null && echo "✅ malaysia.png → MY.png"
mv maldives.png MV.png 2>/dev/null && echo "✅ maldives.png → MV.png"
mv mali.png ML.png 2>/dev/null && echo "✅ mali.png → ML.png"
mv malta.png MT.png 2>/dev/null && echo "✅ malta.png → MT.png"
mv mauritius.png MU.png 2>/dev/null && echo "✅ mauritius.png → MU.png"
mv mexico.png MX.png 2>/dev/null && echo "✅ mexico.png → MX.png"
mv micronesia.png FM.png 2>/dev/null && echo "✅ micronesia.png → FM.png"
mv moldova.png MD.png 2>/dev/null && echo "✅ moldova.png → MD.png"
mv monaco.png MC.png 2>/dev/null && echo "✅ monaco.png → MC.png"
mv mongolia.png MN.png 2>/dev/null && echo "✅ mongolia.png → MN.png"
mv montenegro.png ME.png 2>/dev/null && echo "✅ montenegro.png → ME.png"
mv morocco.png MA.png 2>/dev/null && echo "✅ morocco.png → MA.png"
mv mozambique.png MZ.png 2>/dev/null && echo "✅ mozambique.png → MZ.png"
mv myanmar.png MM.png 2>/dev/null && echo "✅ myanmar.png → MM.png"
mv namibia.png NA.png 2>/dev/null && echo "✅ namibia.png → NA.png"
mv nepal.png NP.png 2>/dev/null && echo "✅ nepal.png → NP.png"
mv netherlands.png NL.png 2>/dev/null && echo "✅ netherlands.png → NL.png"
mv new-zealand.png NZ.png 2>/dev/null && echo "✅ new-zealand.png → NZ.png"
mv nicaragua.png NI.png 2>/dev/null && echo "✅ nicaragua.png → NI.png"
mv niger.png NE.png 2>/dev/null && echo "✅ niger.png → NE.png"
mv nigeria.png NG.png 2>/dev/null && echo "✅ nigeria.png → NG.png"
mv north-korea.png KP.png 2>/dev/null && echo "✅ north-korea.png → KP.png"
mv north-macedonia.png MK.png 2>/dev/null && echo "✅ north-macedonia.png → MK.png"
mv norway.png NO.png 2>/dev/null && echo "✅ norway.png → NO.png"
mv oman.png OM.png 2>/dev/null && echo "✅ oman.png → OM.png"
mv pakistan.png PK.png 2>/dev/null && echo "✅ pakistan.png → PK.png"
mv palau.png PW.png 2>/dev/null && echo "✅ palau.png → PW.png"
mv palestine.png PS.png 2>/dev/null && echo "✅ palestine.png → PS.png"
mv panama.png PA.png 2>/dev/null && echo "✅ panama.png → PA.png"
mv papua-new-guinea.png PG.png 2>/dev/null && echo "✅ papua-new-guinea.png → PG.png"
mv paraguay.png PY.png 2>/dev/null && echo "✅ paraguay.png → PY.png"
mv peru.png PE.png 2>/dev/null && echo "✅ peru.png → PE.png"
mv philippines.png PH.png 2>/dev/null && echo "✅ philippines.png → PH.png"
mv poland.png PL.png 2>/dev/null && echo "✅ poland.png → PL.png"
mv portugal.png PT.png 2>/dev/null && echo "✅ portugal.png → PT.png"
mv puerto-rico.png PR.png 2>/dev/null && echo "✅ puerto-rico.png → PR.png"
mv qatar.png QA.png 2>/dev/null && echo "✅ qatar.png → QA.png"
mv republic-of-the-congo.png CG.png 2>/dev/null && echo "✅ republic-of-the-congo.png → CG.png"
mv romania.png RO.png 2>/dev/null && echo "✅ romania.png → RO.png"
mv russia.png RU.png 2>/dev/null && echo "✅ russia.png → RU.png"
mv rwanda.png RW.png 2>/dev/null && echo "✅ rwanda.png → RW.png"
mv saint-kitts-and-nevis.png KN.png 2>/dev/null && echo "✅ saint-kitts-and-nevis.png → KN.png"
mv san-marino.png SM.png 2>/dev/null && echo "✅ san-marino.png → SM.png"
mv saudi-arabia.png SA.png 2>/dev/null && echo "✅ saudi-arabia.png → SA.png"
mv scotland.png GB-SCT.png 2>/dev/null && echo "✅ scotland.png → GB-SCT.png"
mv senegal.png SN.png 2>/dev/null && echo "✅ senegal.png → SN.png"
mv serbia.png RS.png 2>/dev/null && echo "✅ serbia.png → RS.png"
mv singapore.png SG.png 2>/dev/null && echo "✅ singapore.png → SG.png"
mv slovakia.png SK.png 2>/dev/null && echo "✅ slovakia.png → SK.png"
mv slovenia.png SI.png 2>/dev/null && echo "✅ slovenia.png → SI.png"
mv somalia.png SO.png 2>/dev/null && echo "✅ somalia.png → SO.png"
mv south-africa.png ZA.png 2>/dev/null && echo "✅ south-africa.png → ZA.png"
mv south-korea.png KR.png 2>/dev/null && echo "✅ south-korea.png → KR.png"
mv south-sudan.png SS.png 2>/dev/null && echo "✅ south-sudan.png → SS.png"
mv spain.png ES.png 2>/dev/null && echo "✅ spain.png → ES.png"
mv sri-lanka.png LK.png 2>/dev/null && echo "✅ sri-lanka.png → LK.png"
mv sudan.png SD.png 2>/dev/null && echo "✅ sudan.png → SD.png"
mv suriname.png SR.png 2>/dev/null && echo "✅ suriname.png → SR.png"
mv sweden.png SE.png 2>/dev/null && echo "✅ sweden.png → SE.png"
mv switzerland.png CH.png 2>/dev/null && echo "✅ switzerland.png → CH.png"
mv syria.png SY.png 2>/dev/null && echo "✅ syria.png → SY.png"
mv taiwan.png TW.png 2>/dev/null && echo "✅ taiwan.png → TW.png"
mv tajikistan.png TJ.png 2>/dev/null && echo "✅ tajikistan.png → TJ.png"
mv tanzania.png TZ.png 2>/dev/null && echo "✅ tanzania.png → TZ.png"
mv thailand.png TH.png 2>/dev/null && echo "✅ thailand.png → TH.png"
mv trinidad-and-tobago.png TT.png 2>/dev/null && echo "✅ trinidad-and-tobago.png → TT.png"
mv tunisia.png TN.png 2>/dev/null && echo "✅ tunisia.png → TN.png"
mv turkey.png TR.png 2>/dev/null && echo "✅ turkey.png → TR.png"
mv turkmenistan.png TM.png 2>/dev/null && echo "✅ turkmenistan.png → TM.png"
mv uganda.png UG.png 2>/dev/null && echo "✅ uganda.png → UG.png"
mv ukraine.png UA.png 2>/dev/null && echo "✅ ukraine.png → UA.png"
mv united-arab-emirates.png AE.png 2>/dev/null && echo "✅ united-arab-emirates.png → AE.png"
mv united-kingdom.png GB.png 2>/dev/null && echo "✅ united-kingdom.png → GB.png"
mv united-states.png US.png 2>/dev/null && echo "✅ united-states.png → US.png"
mv uruguay.png UY.png 2>/dev/null && echo "✅ uruguay.png → UY.png"
mv uzbekistan.png UZ.png 2>/dev/null && echo "✅ uzbekistan.png → UZ.png"
mv vanuatu.png VU.png 2>/dev/null && echo "✅ vanuatu.png → VU.png"
mv venezuela.png VE.png 2>/dev/null && echo "✅ venezuela.png → VE.png"
mv vietnam.png VN.png 2>/dev/null && echo "✅ vietnam.png → VN.png"
mv yemen.png YE.png 2>/dev/null && echo "✅ yemen.png → YE.png"
mv zambia.png ZM.png 2>/dev/null && echo "✅ zambia.png → ZM.png"
mv zimbabwe.png ZW.png 2>/dev/null && echo "✅ zimbabwe.png → ZW.png"

echo ""
echo "✨ Done! All flags renamed to ISO 2-letter codes!"
echo ""
echo "Your flags are now:"
echo "  flags/CN.png, flags/US.png, flags/BR.png, etc."