export const altitudeData = [
  { name: 'China', code: 'china', highestPointRank: 1, highestPoint: 29029 },
  { name: 'Nepal', code: 'nepal', highestPointRank: 2, highestPoint: 29029 },
  { name: 'Pakistan', code: 'pakistan', highestPointRank: 3, highestPoint: 28251 },
  { name: 'India', code: 'india', highestPointRank: 4, highestPoint: 28169 },
  { name: 'Bhutan', code: 'bhutan', highestPointRank: 5, highestPoint: 24836 },
  { name: 'Tajikistan', code: 'tajikistan', highestPointRank: 6, highestPoint: 24590 },
  { name: 'Afghanistan', code: 'afghanistan', highestPointRank: 7, highestPoint: 24580 },
  { name: 'Kyrgyzstan', code: 'kyrgyzstan', highestPointRank: 8, highestPoint: 24406 },
  { name: 'Kazakhstan', code: 'kazakhstan', highestPointRank: 9, highestPoint: 22999 },
  { name: 'Argentina', code: 'argentina', highestPointRank: 10, highestPoint: 22835 },
  { name: 'Chile', code: 'chile', highestPointRank: 11, highestPoint: 22615 },
  { name: 'Peru', code: 'peru', highestPointRank: 12, highestPoint: 22205 },
  { name: 'Bolivia', code: 'bolivia', highestPointRank: 13, highestPoint: 21463 },
  { name: 'Ecuador', code: 'ecuador', highestPointRank: 14, highestPoint: 20561 },
  { name: 'United States', code: 'united-states', highestPointRank: 15, highestPoint: 20310 },
  { name: 'Canada', code: 'canada', highestPointRank: 16, highestPoint: 19551 },
  { name: 'Tanzania', code: 'tanzania', highestPointRank: 17, highestPoint: 19331 },
  { name: 'Myanmar', code: 'myanmar', highestPointRank: 18, highestPoint: 19295 },
  { name: 'Colombia', code: 'colombia', highestPointRank: 19, highestPoint: 18701 },
  { name: 'Russia', code: 'russia', highestPointRank: 20, highestPoint: 18510 },
  { name: 'Mexico', code: 'mexico', highestPointRank: 21, highestPoint: 18491 },
  { name: 'Iran', code: 'iran', highestPointRank: 22, highestPoint: 18406 },
  { name: 'Georgia', code: 'georgia', highestPointRank: 23, highestPoint: 17064 },
  { name: 'Kenya', code: 'kenya', highestPointRank: 24, highestPoint: 17057 },
  { name: 'Turkey', code: 'turkey', highestPointRank: 25, highestPoint: 16854 },
  { name: 'DR Congo', code: 'dr-congo', highestPointRank: 26, highestPoint: 16762 },
  { name: 'Uganda', code: 'uganda', highestPointRank: 27, highestPoint: 16762 },
  { name: 'Venezuela', code: 'venezuela', highestPointRank: 28, highestPoint: 16332 },
  { name: 'Indonesia', code: 'indonesia', highestPointRank: 29, highestPoint: 16024 },
  { name: 'France', code: 'france', highestPointRank: 30, highestPoint: 15781 },
  { name: 'Italy', code: 'italy', highestPointRank: 31, highestPoint: 15781 },
  { name: 'Uzbekistan', code: 'uzbekistan', highestPointRank: 32, highestPoint: 15233 },
  { name: 'Switzerland', code: 'switzerland', highestPointRank: 33, highestPoint: 15203 },
  { name: 'Ethiopia', code: 'ethiopia', highestPointRank: 34, highestPoint: 14928 },
  { name: 'Papua New Guinea', code: 'papua-new-guinea', highestPointRank: 35, highestPoint: 14793 },
  { name: 'Rwanda', code: 'rwanda', highestPointRank: 36, highestPoint: 14787 },
  { name: 'Azerbaijan', code: 'azerbaijan', highestPointRank: 37, highestPoint: 14715 },
  { name: 'Mongolia', code: 'mongolia', highestPointRank: 38, highestPoint: 14350 },
  { name: 'Guatemala', code: 'guatemala', highestPointRank: 39, highestPoint: 13845 },
  { name: 'Morocco', code: 'morocco', highestPointRank: 40, highestPoint: 13665 },
  { name: 'Malaysia', code: 'malaysia', highestPointRank: 41, highestPoint: 13436 },
  { name: 'Armenia', code: 'armenia', highestPointRank: 42, highestPoint: 13419 },
  { name: 'Cameroon', code: 'cameroon', highestPointRank: 43, highestPoint: 13255 },
  { name: 'Taiwan', code: 'taiwan', highestPointRank: 44, highestPoint: 12966 },
  { name: 'Costa Rica', code: 'costa-rica', highestPointRank: 45, highestPoint: 12533 },
  { name: 'Austria', code: 'austria', highestPointRank: 46, highestPoint: 12461 },
  { name: 'Japan', code: 'japan', highestPointRank: 47, highestPoint: 12388 },
  { name: 'New Zealand', code: 'new-zealand', highestPointRank: 48, highestPoint: 12218 },
  { name: 'Spain', code: 'spain', highestPointRank: 49, highestPoint: 12188 },
  { name: 'Greenland', code: 'greenland', highestPointRank: 50, highestPoint: 12139 },
  { name: 'Yemen', code: 'yemen', highestPointRank: 51, highestPoint: 12028 },
  { name: 'Iraq', code: 'iraq', highestPointRank: 52, highestPoint: 11847 },
  { name: 'Lesotho', code: 'lesotho', highestPointRank: 53, highestPoint: 11424 },
  { name: 'Panama', code: 'panama', highestPointRank: 54, highestPoint: 11401 },
  { name: 'South Africa', code: 'south-africa', highestPointRank: 55, highestPoint: 11319 },
  { name: 'Chad', code: 'chad', highestPointRank: 56, highestPoint: 11302 },
  { name: 'South Sudan', code: 'south-sudan', highestPointRank: 57, highestPoint: 10456 },
  { name: 'Vietnam', code: 'vietnam', highestPointRank: 58, highestPoint: 10312 },
  { name: 'Turkmenistan', code: 'turkmenistan', highestPointRank: 59, highestPoint: 10299 },
  { name: 'Saudi Arabia', code: 'saudi-arabia', highestPointRank: 60, highestPoint: 10279 },
  { name: 'Dominican Republic', code: 'dominican-republic', highestPointRank: 61, highestPoint: 10164 },
  { name: 'Lebanon', code: 'lebanon', highestPointRank: 62, highestPoint: 10131 },
  { name: 'Sudan', code: 'sudan', highestPointRank: 64, highestPoint: 9980 },
  { name: 'Eritrea', code: 'eritrea', highestPointRank: 65, highestPoint: 9902 },
  { name: 'Oman', code: 'oman', highestPointRank: 66, highestPoint: 9872 },
  { name: 'Equatorial Guinea', code: 'equatorial-guinea', highestPointRank: 67, highestPoint: 9869 },
  { name: 'Algeria', code: 'algeria', highestPointRank: 68, highestPoint: 9852 },
  { name: 'Malawi', code: 'malawi', highestPointRank: 69, highestPoint: 9849 },
  { name: 'Brazil', code: 'brazil', highestPointRank: 70, highestPoint: 9826 },
  { name: 'Timor-Leste', code: 'timor-leste', highestPointRank: 71, highestPoint: 9721 },
  { name: 'Germany', code: 'germany', highestPointRank: 72, highestPoint: 9718 },
  { name: 'Philippines', code: 'philippines', highestPointRank: 73, highestPoint: 9692 },
  { name: 'Andorra', code: 'andorra', highestPointRank: 74, highestPoint: 9652 },
  { name: 'Bulgaria', code: 'bulgaria', highestPointRank: 75, highestPoint: 9596 },
  { name: 'Greece', code: 'greece', highestPointRank: 76, highestPoint: 9570 },
  { name: 'Madagascar', code: 'madagascar', highestPointRank: 77, highestPoint: 9436 },
  { name: 'Honduras', code: 'honduras', highestPointRank: 78, highestPoint: 9416 },
  { name: 'Slovenia', code: 'slovenia', highestPointRank: 79, highestPoint: 9396 },
  { name: 'Cape Verde', code: 'cape-verde', highestPointRank: 80, highestPoint: 9281 },
  { name: 'Laos', code: 'laos', highestPointRank: 81, highestPoint: 9242 },
  { name: 'Syria', code: 'syria', highestPointRank: 82, highestPoint: 9232 },
  { name: 'Albania', code: 'albania', highestPointRank: 83, highestPoint: 9068 },
  { name: 'North Macedonia', code: 'north-macedonia', highestPointRank: 84, highestPoint: 9068 },
  { name: 'North Korea', code: 'north-korea', highestPointRank: 85, highestPoint: 9003 },
  { name: 'Guyana', code: 'guyana', highestPointRank: 86, highestPoint: NaN },
  { name: 'El Salvador', code: 'el-salvador', highestPointRank: 87, highestPoint: 8957 },
  { name: 'Burundi', code: 'burundi', highestPointRank: 88, highestPoint: 8806 },
  { name: 'Haiti', code: 'haiti', highestPointRank: 89, highestPoint: 8793 },
  { name: 'Slovakia', code: 'slovakia', highestPointRank: 90, highestPoint: 8711 },
  { name: 'Egypt', code: 'egypt', highestPointRank: 91, highestPoint: 8625 },
  { name: 'Angola', code: 'angola', highestPointRank: 92, highestPoint: 8596 },
  { name: 'Liechtenstein', code: 'liechtenstein', highestPointRank: 93, highestPoint: 8527 },
  { name: 'Zimbabwe', code: 'zimbabwe', highestPointRank: 94, highestPoint: 8504 },
  { name: 'Namibia', code: 'namibia', highestPointRank: 95, highestPoint: 8442 },
  { name: 'Thailand', code: 'thailand', highestPointRank: 96, highestPoint: 8415 },
  { name: 'Romania', code: 'romania', highestPointRank: 97, highestPoint: 8346 },
  { name: 'Montenegro', code: 'montenegro', highestPointRank: 98, highestPoint: 8314 },
  { name: 'Sri Lanka', code: 'sri-lanka', highestPointRank: 99, highestPoint: 8281 },
  { name: 'Poland', code: 'poland', highestPointRank: 100, highestPoint: 8199 },
  { name: 'Norway', code: 'norway', highestPointRank: 101, highestPoint: 8100 },
  { name: 'Somalia', code: 'somalia', highestPointRank: 102, highestPoint: 8038 },
  { name: 'Mozambique', code: 'mozambique', highestPointRank: 103, highestPoint: 7992 },
  { name: 'Nigeria', code: 'nigeria', highestPointRank: 104, highestPoint: 7936 },
  { name: 'Bosnia and Herzegovina', code: 'bosnia-and-herzegovina', highestPointRank: 105, highestPoint: 7828 },
  { name: 'Comoros', code: 'comoros', highestPointRank: 106, highestPoint: 7743 },
  { name: 'Portugal', code: 'portugal', highestPointRank: 107, highestPoint: 7713 },
  { name: 'Solomon Islands', code: 'solomon-islands', highestPointRank: 108, highestPoint: 7661 },
  { name: 'Zambia', code: 'zambia', highestPointRank: 109, highestPoint: 7641 },
  { name: 'Libya', code: 'libya', highestPointRank: 110, highestPoint: 7438 },
  { name: 'Jamaica', code: 'jamaica', highestPointRank: 111, highestPoint: 7402 },
  { name: 'Australia', code: 'australia', highestPointRank: 113, highestPoint: 7310 },
  { name: 'Serbia', code: 'serbia', highestPointRank: 114, highestPoint: 7116 },
  { name: 'Iceland', code: 'iceland', highestPointRank: 115, highestPoint: 6921 },
  { name: 'Nicaragua', code: 'nicaragua', highestPointRank: 116, highestPoint: 6913 },
  { name: 'Sweden', code: 'sweden', highestPointRank: 117, highestPoint: 6880 },
  { name: 'Ukraine', code: 'ukraine', highestPointRank: 118, highestPoint: 6762 },
  { name: 'Djibouti', code: 'djibouti', highestPointRank: 119, highestPoint: 6654 },
  { name: 'Sao Tome and Principe', code: 'sao-tome-and-principe', highestPointRank: 120, highestPoint: 6640 },
  { name: 'Niger', code: 'niger', highestPointRank: 121, highestPoint: 6634 },
  { name: 'Cuba', code: 'cuba', highestPointRank: 122, highestPoint: 6476 },
  { name: 'Cyprus', code: 'cyprus', highestPointRank: 123, highestPoint: 6401 },
  { name: 'South Korea', code: 'south-korea', highestPointRank: 124, highestPoint: 6398 },
  { name: 'Sierra Leone', code: 'sierra-leone', highestPointRank: 125, highestPoint: 6391 },
  { name: 'United Arab Emirates', code: 'united-arab-emirates', highestPointRank: 126, highestPoint: 6266 },
  { name: 'Vanuatu', code: 'vanuatu', highestPointRank: 127, highestPoint: 6158 },
  { name: 'Eswatini', code: 'eswatini', highestPointRank: 128, highestPoint: 6109 },
  { name: 'Samoa', code: 'samoa', highestPointRank: 129, highestPoint: 6093 },
  { name: 'Jordan', code: 'jordan', highestPointRank: 130, highestPoint: 6083 },
  { name: 'Brunei', code: 'brunei', highestPointRank: 131, highestPoint: 6070 },
  { name: 'Croatia', code: 'croatia', highestPointRank: 132, highestPoint: 6007 },
  { name: 'Cambodia', code: 'cambodia', highestPointRank: 133, highestPoint: 5938 },
  { name: 'Ivory Coast', code: 'ivory-coast', highestPointRank: 134, highestPoint: 5748 },
  { name: 'Guinea', code: 'guinea', highestPointRank: 135, highestPoint: 5748 },
  { name: 'Tunisia', code: 'tunisia', highestPointRank: 137, highestPoint: 5066 },
  { name: 'Botswana', code: 'botswana', highestPointRank: 138, highestPoint: 4892 },
  { name: 'Dominica', code: 'dominica', highestPointRank: 140, highestPoint: 4747 },
  { name: 'Liberia', code: 'liberia', highestPointRank: 141, highestPoint: 4724 },
  { name: 'Central African Republic', code: 'central-african-republic', highestPointRank: 142, highestPoint: 4659 },
  { name: 'United Kingdom', code: 'united-kingdom', highestPointRank: 144, highestPoint: 4413 },
  { name: 'Puerto Rico', code: 'puerto-rico', highestPointRank: 145, highestPoint: 4390 },
  { name: 'Finland', code: 'finland', highestPointRank: 146, highestPoint: 4344 },
  { name: 'Fiji', code: 'fiji', highestPointRank: 147, highestPoint: 4344 },
  { name: 'Bangladesh', code: 'bangladesh', highestPointRank: 148, highestPoint: 4199 },
  { name: 'Saint Vincent and the Grenadines', code: 'saint-vincent-and-the-grenadines', highestPointRank: 149, highestPoint: 4049 },
  { name: 'Suriname', code: 'suriname', highestPointRank: 150, highestPoint: 4035 },
  { name: 'Israel', code: 'israel', highestPointRank: 151, highestPoint: 3963 },
  { name: 'Saint Kitts and Nevis', code: 'saint-kitts-and-nevis', highestPointRank: 152, highestPoint: 3793 },
  { name: 'Mali', code: 'mali', highestPointRank: 153, highestPoint: 3789 },
  { name: 'Belize', code: 'belize', highestPointRank: 154, highestPoint: 3688 },
  { name: 'Gabon', code: 'gabon', highestPointRank: 155, highestPoint: 3510 },
  { name: 'Ireland', code: 'ireland', highestPointRank: 156, highestPoint: 3406 },
  { name: 'Tonga', code: 'tonga', highestPointRank: 157, highestPoint: 3389 },
  { name: 'Palestine', code: 'palestine', highestPointRank: 158, highestPoint: 3379 },
  { name: 'Republic of the Congo', code: 'republic-of-the-congo', highestPointRank: 159, highestPoint: 3346 },
  { name: 'Hungary', code: 'hungary', highestPointRank: 160, highestPoint: 3327 },
  { name: 'Togo', code: 'togo', highestPointRank: 161, highestPoint: 3235 },
  { name: 'Hong Kong', code: 'hong-kong', highestPointRank: 164, highestPoint: 3143 },
  { name: 'Saint Lucia', code: 'saint-lucia', highestPointRank: 165, highestPoint: 3117 },
  { name: 'Trinidad and Tobago', code: 'trinidad-and-tobago', highestPointRank: 166, highestPoint: 3084 },
  { name: 'Mauritania', code: 'mauritania', highestPointRank: 167, highestPoint: 3002 },
  { name: 'Seychelles', code: 'seychelles', highestPointRank: 169, highestPoint: 2969 },
  { name: 'Netherlands', code: 'netherlands', highestPointRank: 170, highestPoint: 2910 },
  { name: 'Ghana', code: 'ghana', highestPointRank: 171, highestPoint: 2887 },
  { name: 'Paraguay', code: 'paraguay', highestPointRank: 174, highestPoint: 2762 },
  { name: 'Grenada', code: 'grenada', highestPointRank: 175, highestPoint: 2756 },
  { name: 'Mauritius', code: 'mauritius', highestPointRank: 176, highestPoint: 2717 },
  { name: 'Micronesia', code: 'micronesia', highestPointRank: 177, highestPoint: 2566 },
  { name: 'Burkina Faso', code: 'burkina-faso', highestPointRank: 178, highestPoint: 2457 },
  { name: 'San Marino', code: 'san-marino', highestPointRank: 179, highestPoint: 2425 },
  { name: 'Belgium', code: 'belgium', highestPointRank: 181, highestPoint: 2277 },
  { name: 'Mayotte', code: 'mayotte', highestPointRank: 182, highestPoint: 2165 },
  { name: 'Benin', code: 'benin', highestPointRank: 183, highestPoint: 2159 },
  { name: 'Cook Islands', code: 'cook-islands', highestPointRank: 184, highestPoint: 2139 },
  { name: 'Senegal', code: 'senegal', highestPointRank: 185, highestPoint: 2126 },
  { name: 'Luxembourg', code: 'luxembourg', highestPointRank: 188, highestPoint: 1837 },
  { name: 'Uruguay', code: 'uruguay', highestPointRank: 191, highestPoint: 1685 },
  { name: 'Moldova', code: 'moldova', highestPointRank: 193, highestPoint: 1411 },
  { name: 'Antigua and Barbuda', code: 'antigua-and-barbuda', highestPointRank: 197, highestPoint: 1319 },
  { name: 'Belarus', code: 'belarus', highestPointRank: 200, highestPoint: 1135 },
  { name: 'Barbados', code: 'barbados', highestPointRank: 201, highestPoint: 1102 },
  { name: 'Estonia', code: 'estonia', highestPointRank: 202, highestPoint: 1043 },
  { name: 'Latvia', code: 'latvia', highestPointRank: 203, highestPoint: 1024 },
  { name: 'Kuwait', code: 'kuwait', highestPointRank: 204, highestPoint: 1004 },
  { name: 'Lithuania', code: 'lithuania', highestPointRank: 205, highestPoint: 964 },
  { name: 'Guinea-Bissau', code: 'guinea-bissau', highestPointRank: 206, highestPoint: 860 },
  { name: 'Malta', code: 'malta', highestPointRank: 207, highestPoint: 830 },
  { name: 'Palau', code: 'palau', highestPointRank: 208, highestPoint: 794 },
  { name: 'Macau', code: 'macau', highestPointRank: 211, highestPoint: 564 },
  { name: 'Denmark', code: 'denmark', highestPointRank: 212, highestPoint: 561 },
  { name: 'Singapore', code: 'singapore', highestPointRank: 213, highestPoint: 537 },
  { name: 'Monaco', code: 'monaco', highestPointRank: 214, highestPoint: 528 },
  { name: 'Bahrain', code: 'bahrain', highestPointRank: 216, highestPoint: 400 },
  { name: 'Qatar', code: 'qatar', highestPointRank: 218, highestPoint: 338 },
  { name: 'Kiribati', code: 'kiribati', highestPointRank: 219, highestPoint: 266 },
  { name: 'Vatican City', code: 'vatican-city', highestPointRank: 221, highestPoint: 246 },
  { name: 'Nauru', code: 'nauru', highestPointRank: 224, highestPoint: 213 },
  { name: 'Bahamas', code: 'bahamas', highestPointRank: 225, highestPoint: 207 },
  { name: 'Marshall Islands', code: 'marshall-islands', highestPointRank: 228, highestPoint: 33 },
  { name: 'Maldives', code: 'maldives', highestPointRank: 229, highestPoint: 17 },
  { name: 'Tuvalu', code: 'tuvalu', highestPointRank: 231, highestPoint: 15 }
];
