export const altitudeData = [
  { name: 'China', code: 'china', highestPointRank: 1, highestPoint: 8848 },
  { name: 'Nepal', code: 'nepal', highestPointRank: 2, highestPoint: 8848 },
  { name: 'Pakistan', code: 'pakistan', highestPointRank: 3, highestPoint: 8611 },
  { name: 'India', code: 'india', highestPointRank: 4, highestPoint: 8586 },
  { name: 'Bhutan', code: 'bhutan', highestPointRank: 5, highestPoint: 7570 },
  { name: 'Tajikistan', code: 'tajikistan', highestPointRank: 6, highestPoint: 7495 },
  { name: 'Afghanistan', code: 'afghanistan', highestPointRank: 7, highestPoint: 7492 },
  { name: 'Kyrgyzstan', code: 'kyrgyzstan', highestPointRank: 8, highestPoint: 7439 },
  { name: 'Kazakhstan', code: 'kazakhstan', highestPointRank: 9, highestPoint: 7010 },
  { name: 'Argentina', code: 'argentina', highestPointRank: 10, highestPoint: 6960 },
  { name: 'Chile', code: 'chile', highestPointRank: 11, highestPoint: 6893 },
  { name: 'Peru', code: 'peru', highestPointRank: 12, highestPoint: 6768 },
  { name: 'Bolivia', code: 'bolivia', highestPointRank: 13, highestPoint: 6542 },
  { name: 'Ecuador', code: 'ecuador', highestPointRank: 14, highestPoint: 6267 },
  { name: 'United States', code: 'united-states', highestPointRank: 15, highestPoint: 6190.5 },
  { name: 'Canada', code: 'canada', highestPointRank: 16, highestPoint: 5959 },
  { name: 'Tanzania', code: 'tanzania', highestPointRank: 17, highestPoint: 5892 },
  { name: 'Myanmar', code: 'myanmar', highestPointRank: 18, highestPoint: 5881 },
  { name: 'Colombia', code: 'colombia', highestPointRank: 19, highestPoint: 5700 },
  { name: 'Russia', code: 'russia', highestPointRank: 20, highestPoint: 5642 },
  { name: 'Mexico', code: 'mexico', highestPointRank: 21, highestPoint: 5636 },
  { name: 'Iran', code: 'iran', highestPointRank: 22, highestPoint: 5610 },
  { name: 'Georgia', code: 'georgia', highestPointRank: 23, highestPoint: 5201 },
  { name: 'Kenya', code: 'kenya', highestPointRank: 24, highestPoint: 5199 },
  { name: 'Turkey', code: 'turkey', highestPointRank: 25, highestPoint: 5137 },
  { name: 'DR Congo', code: 'democratic-republic-of-the-congo', highestPointRank: 26, highestPoint: 5109 },
  { name: 'Uganda', code: 'uganda', highestPointRank: 27, highestPoint: 5109 },
  { name: 'Venezuela', code: 'venezuela', highestPointRank: 28, highestPoint: 4978 },
  { name: 'Indonesia', code: 'indonesia', highestPointRank: 29, highestPoint: 4884 },
  { name: 'France', code: 'france', highestPointRank: 30, highestPoint: 4810 },
  { name: 'Italy', code: 'italy', highestPointRank: 31, highestPoint: 4810 },
  { name: 'Uzbekistan', code: 'uzbekistan', highestPointRank: 32, highestPoint: 4643 },
  { name: 'Switzerland', code: 'switzerland', highestPointRank: 33, highestPoint: 4634 },
  { name: 'Ethiopia', code: 'ethiopia', highestPointRank: 34, highestPoint: 4550 },
  { name: 'Papua New Guinea', code: 'papua-new-guinea', highestPointRank: 35, highestPoint: 4509 },
  { name: 'Rwanda', code: 'rwanda', highestPointRank: 36, highestPoint: 4507 },
  { name: 'Azerbaijan', code: 'azerbaijan', highestPointRank: 37, highestPoint: 4485 },
  { name: 'Mongolia', code: 'mongolia', highestPointRank: 38, highestPoint: 4374 },
  { name: 'Guatemala', code: 'guatemala', highestPointRank: 39, highestPoint: 4220 },
  { name: 'Morocco', code: 'morocco', highestPointRank: 40, highestPoint: 4165 },
  { name: 'Malaysia', code: 'malaysia', highestPointRank: 41, highestPoint: 4095 },
  { name: 'Armenia', code: 'armenia', highestPointRank: 42, highestPoint: 4090 },
  { name: 'Cameroon', code: 'cameroon', highestPointRank: 43, highestPoint: 4040 },
  { name: 'Taiwan', code: 'taiwan', highestPointRank: 44, highestPoint: 3952 },
  { name: 'Costa Rica', code: 'costa-rica', highestPointRank: 45, highestPoint: 3820 },
  { name: 'Austria', code: 'austria', highestPointRank: 46, highestPoint: 3798 },
  { name: 'Japan', code: 'japan', highestPointRank: 47, highestPoint: 3776 },
  { name: 'New Zealand', code: 'new-zealand', highestPointRank: 48, highestPoint: 3724 },
  { name: 'Spain', code: 'spain', highestPointRank: 49, highestPoint: 3715 },
  { name: 'Greenland', code: 'greenland', highestPointRank: 50, highestPoint: 3700 },
  { name: 'Yemen', code: 'yemen', highestPointRank: 51, highestPoint: 3666 },
  { name: 'Iraq', code: 'iraq', highestPointRank: 52, highestPoint: 3611 },
  { name: 'Lesotho', code: 'lesotho', highestPointRank: 53, highestPoint: 3482 },
  { name: 'Panama', code: 'panama', highestPointRank: 54, highestPoint: 3475 },
  { name: 'South Africa', code: 'south-africa', highestPointRank: 55, highestPoint: 3450 },
  { name: 'Chad', code: 'chad', highestPointRank: 56, highestPoint: 3445 },
  { name: 'South Sudan', code: 'south-sudan', highestPointRank: 57, highestPoint: 3187 },
  { name: 'Vietnam', code: 'vietnam', highestPointRank: 58, highestPoint: 3143 },
  { name: 'Turkmenistan', code: 'turkmenistan', highestPointRank: 59, highestPoint: 3139 },
  { name: 'Saudi Arabia', code: 'saudi-arabia', highestPointRank: 60, highestPoint: 3133 },
  { name: 'Dominican Republic', code: 'dominican-republic', highestPointRank: 61, highestPoint: 3098 },
  { name: 'Lebanon', code: 'lebanon', highestPointRank: 62, highestPoint: 3088 },
  { name: 'Sudan', code: 'sudan', highestPointRank: 64, highestPoint: 3042 },
  { name: 'Eritrea', code: 'eritrea', highestPointRank: 65, highestPoint: 3018 },
  { name: 'Oman', code: 'oman', highestPointRank: 66, highestPoint: 3009 },
  { name: 'Equatorial Guinea', code: 'equatorial-guinea', highestPointRank: 67, highestPoint: 3008 },
  { name: 'Algeria', code: 'algeria', highestPointRank: 68, highestPoint: 3003 },
  { name: 'Malawi', code: 'malawi', highestPointRank: 69, highestPoint: 3002 },
  { name: 'Brazil', code: 'brazil', highestPointRank: 70, highestPoint: 2995 },
  { name: 'East Timor', code: 'east-timor', highestPointRank: 71, highestPoint: 2963 },
  { name: 'Germany', code: 'germany', highestPointRank: 72, highestPoint: 2962 },
  { name: 'Philippines', code: 'philippines', highestPointRank: 73, highestPoint: 2954 },
  { name: 'Andorra', code: 'andorra', highestPointRank: 74, highestPoint: 2942 },
  { name: 'Bulgaria', code: 'bulgaria', highestPointRank: 75, highestPoint: 2925 },
  { name: 'Greece', code: 'greece', highestPointRank: 76, highestPoint: 2917 },
  { name: 'Madagascar', code: 'madagascar', highestPointRank: 77, highestPoint: 2876 },
  { name: 'Honduras', code: 'honduras', highestPointRank: 78, highestPoint: 2870 },
  { name: 'Slovenia', code: 'slovenia', highestPointRank: 79, highestPoint: 2864 },
  { name: 'Cape Verde', code: 'cape-verde', highestPointRank: 80, highestPoint: 2829 },
  { name: 'Laos', code: 'laos', highestPointRank: 81, highestPoint: 2817 },
  { name: 'Syria', code: 'syria', highestPointRank: 82, highestPoint: 2814 },
  { name: 'Albania', code: 'albania', highestPointRank: 83, highestPoint: 2764 },
  { name: 'North Macedonia', code: 'north-macedonia', highestPointRank: 84, highestPoint: 2764 },
  { name: 'North Korea', code: 'north-korea', highestPointRank: 85, highestPoint: 2744 },
  { name: 'Guyana', code: 'guyana', highestPointRank: 86, highestPoint: 2772 },
  { name: 'El Salvador', code: 'el-salvador', highestPointRank: 87, highestPoint: 2730 },
  { name: 'Burundi', code: 'burundi', highestPointRank: 88, highestPoint: 2684 },
  { name: 'Haiti', code: 'haiti', highestPointRank: 89, highestPoint: 2680 },
  { name: 'Slovakia', code: 'slovakia', highestPointRank: 90, highestPoint: 2655 },
  { name: 'Egypt', code: 'egypt', highestPointRank: 91, highestPoint: 2629 },
  { name: 'Angola', code: 'angola', highestPointRank: 92, highestPoint: 2620 },
  { name: 'Liechtenstein', code: 'liechtenstein', highestPointRank: 93, highestPoint: 2599 },
  { name: 'Zimbabwe', code: 'zimbabwe', highestPointRank: 94, highestPoint: 2592 },
  { name: 'Namibia', code: 'namibia', highestPointRank: 95, highestPoint: 2573 },
  { name: 'Thailand', code: 'thailand', highestPointRank: 96, highestPoint: 2565 },
  { name: 'Romania', code: 'romania', highestPointRank: 97, highestPoint: 2544 },
  { name: 'Montenegro', code: 'montenegro', highestPointRank: 98, highestPoint: 2534 },
  { name: 'Sri Lanka', code: 'sri-lanka', highestPointRank: 99, highestPoint: 2524 },
  { name: 'Poland', code: 'poland', highestPointRank: 100, highestPoint: 2499 },
  { name: 'Norway', code: 'norway', highestPointRank: 101, highestPoint: 2469 },
  { name: 'Somalia', code: 'somalia', highestPointRank: 102, highestPoint: 2450 },
  { name: 'Mozambique', code: 'mozambique', highestPointRank: 103, highestPoint: 2436 },
  { name: 'Nigeria', code: 'nigeria', highestPointRank: 104, highestPoint: 2419 },
  { name: 'Bosnia and Herzegovina', code: 'bosnia-and-herzegovina', highestPointRank: 105, highestPoint: 2386 },
  { name: 'Comoros', code: 'comoros', highestPointRank: 106, highestPoint: 2360 },
  { name: 'Portugal', code: 'portugal', highestPointRank: 107, highestPoint: 2351 },
  { name: 'Solomon Islands', code: 'solomon-islands', highestPointRank: 108, highestPoint: 2335 },
  { name: 'Zambia', code: 'zambia', highestPointRank: 109, highestPoint: 2329 },
  { name: 'Libya', code: 'libya', highestPointRank: 110, highestPoint: 2267 },
  { name: 'Jamaica', code: 'jamaica', highestPointRank: 111, highestPoint: 2256 },
  { name: 'Australia', code: 'australia', highestPointRank: 113, highestPoint: 2228 },
  { name: 'Serbia', code: 'serbia', highestPointRank: 114, highestPoint: 2169 },
  { name: 'Iceland', code: 'iceland', highestPointRank: 115, highestPoint: 2110 },
  { name: 'Nicaragua', code: 'nicaragua', highestPointRank: 116, highestPoint: 2107 },
  { name: 'Sweden', code: 'sweden', highestPointRank: 117, highestPoint: 2097 },
  { name: 'Ukraine', code: 'ukraine', highestPointRank: 118, highestPoint: 2061 },
  { name: 'Djibouti', code: 'djibouti', highestPointRank: 119, highestPoint: 2028 },
  { name: 'Sao Tome and Principe', code: 'sao-tome-and-principe', highestPointRank: 120, highestPoint: 2024 },
  { name: 'Niger', code: 'niger', highestPointRank: 121, highestPoint: 2022 },
  { name: 'Cuba', code: 'cuba', highestPointRank: 122, highestPoint: 1974 },
  { name: 'Cyprus', code: 'cyprus', highestPointRank: 123, highestPoint: 1951 },
  { name: 'South Korea', code: 'south-korea', highestPointRank: 124, highestPoint: 1950 },
  { name: 'Sierra Leone', code: 'sierra-leone', highestPointRank: 125, highestPoint: 1948 },
  { name: 'United Arab Emirates', code: 'united-arab-emirates', highestPointRank: 126, highestPoint: 1910 },
  { name: 'Vanuatu', code: 'vanuatu', highestPointRank: 127, highestPoint: 1877 },
  { name: 'Eswatini', code: 'eswatini', highestPointRank: 128, highestPoint: 1862 },
  { name: 'Samoa', code: 'samoa', highestPointRank: 129, highestPoint: 1857 },
  { name: 'Jordan', code: 'jordan', highestPointRank: 130, highestPoint: 1854 },
  { name: 'Brunei', code: 'brunei', highestPointRank: 131, highestPoint: 1850 },
  { name: 'Croatia', code: 'croatia', highestPointRank: 132, highestPoint: 1831 },
  { name: 'Cambodia', code: 'cambodia', highestPointRank: 133, highestPoint: 1810 },
  { name: 'Ivory Coast', code: 'ivory-coast', highestPointRank: 134, highestPoint: 1752 },
  { name: 'Guinea', code: 'guinea', highestPointRank: 135, highestPoint: 1752 },
  { name: 'Tunisia', code: 'tunisia', highestPointRank: 137, highestPoint: 1544 },
  { name: 'Botswana', code: 'botswana', highestPointRank: 138, highestPoint: 1491 },
  { name: 'Dominica', code: 'dominica', highestPointRank: 140, highestPoint: 1447 },
  { name: 'Liberia', code: 'liberia', highestPointRank: 141, highestPoint: 1440 },
  { name: 'Central African Republic', code: 'central-african-republic', highestPointRank: 142, highestPoint: 1420 },
  { name: 'United Kingdom', code: 'united-kingdom', highestPointRank: 144, highestPoint: 1345 },
  { name: 'Puerto Rico', code: 'puerto-rico', highestPointRank: 145, highestPoint: 1338 },
  { name: 'Finland', code: 'finland', highestPointRank: 146, highestPoint: 1324 },
  { name: 'Fiji', code: 'fiji', highestPointRank: 147, highestPoint: 1324 },
  { name: 'Bangladesh', code: 'bangladesh', highestPointRank: 148, highestPoint: 1280 },
  { name: 'Saint Vincent and the Grenadines', code: 'saint-vincent-and-the-grenadines', highestPointRank: 149, highestPoint: 1234 },
  { name: 'Suriname', code: 'suriname', highestPointRank: 150, highestPoint: 1230 },
  { name: 'Israel', code: 'israel', highestPointRank: 151, highestPoint: 1208 },
  { name: 'Saint Kitts and Nevis', code: 'saint-kitts-and-nevis', highestPointRank: 152, highestPoint: 1156 },
  { name: 'Mali', code: 'mali', highestPointRank: 153, highestPoint: 1155 },
  { name: 'Belize', code: 'belize', highestPointRank: 154, highestPoint: 1124 },
  { name: 'Gabon', code: 'gabon', highestPointRank: 155, highestPoint: 1070 },
  { name: 'Ireland', code: 'ireland', highestPointRank: 156, highestPoint: 1038 },
  { name: 'Tonga', code: 'tonga', highestPointRank: 157, highestPoint: 1033 },
  { name: 'Palestine', code: 'palestine', highestPointRank: 158, highestPoint: 1030 },
  { name: 'Republic of the Congo', code: 'republic-of-the-congo', highestPointRank: 159, highestPoint: 1020 },
  { name: 'Hungary', code: 'hungary', highestPointRank: 160, highestPoint: 1014 },
  { name: 'Togo', code: 'togo', highestPointRank: 161, highestPoint: 986 },
  { name: 'Hong Kong', code: 'hong-kong', highestPointRank: 164, highestPoint: 958 },
  { name: 'Saint Lucia', code: 'saint-lucia', highestPointRank: 165, highestPoint: 950 },
  { name: 'Trinidad and Tobago', code: 'trinidad-and-tobago', highestPointRank: 166, highestPoint: 940 },
  { name: 'Seychelles', code: 'seychelles', highestPointRank: 169, highestPoint: 905 },
  { name: 'Netherlands', code: 'netherlands', highestPointRank: 170, highestPoint: 887 },
  { name: 'Ghana', code: 'ghana', highestPointRank: 171, highestPoint: 880 },
  { name: 'Paraguay', code: 'paraguay', highestPointRank: 174, highestPoint: 842 },
  { name: 'Grenada', code: 'grenada', highestPointRank: 175, highestPoint: 840 },
  { name: 'Mauritius', code: 'mauritius', highestPointRank: 176, highestPoint: 828 },
  { name: 'Micronesia', code: 'micronesia', highestPointRank: 177, highestPoint: 782 },
  { name: 'Burkina Faso', code: 'burkina-faso', highestPointRank: 178, highestPoint: 749 },
  { name: 'San Marino', code: 'san-marino', highestPointRank: 179, highestPoint: 739 },
  { name: 'Belgium', code: 'belgium', highestPointRank: 181, highestPoint: 694 },
  { name: 'Benin', code: 'benin', highestPointRank: 183, highestPoint: 658 },
  { name: 'Senegal', code: 'senegal', highestPointRank: 185, highestPoint: 648 },
  { name: 'Luxembourg', code: 'luxembourg', highestPointRank: 188, highestPoint: 560 },
  { name: 'Uruguay', code: 'uruguay', highestPointRank: 191, highestPoint: 514 },
  { name: 'Moldova', code: 'moldova', highestPointRank: 193, highestPoint: 430 },
  { name: 'Antigua and Barbuda', code: 'antigua-and-barbuda', highestPointRank: 197, highestPoint: 402 },
  { name: 'Belarus', code: 'belarus', highestPointRank: 200, highestPoint: 346 },
  { name: 'Barbados', code: 'barbados', highestPointRank: 201, highestPoint: 336 },
  { name: 'Estonia', code: 'estonia', highestPointRank: 202, highestPoint: 318 },
  { name: 'Latvia', code: 'latvia', highestPointRank: 203, highestPoint: 312 },
  { name: 'Kuwait', code: 'kuwait', highestPointRank: 204, highestPoint: 306 },
  { name: 'Lithuania', code: 'lithuania', highestPointRank: 205, highestPoint: 294 },
  { name: 'Guinea-Bissau', code: 'guinea-bissau', highestPointRank: 206, highestPoint: 262 },
  { name: 'Malta', code: 'malta', highestPointRank: 207, highestPoint: 253 },
  { name: 'Palau', code: 'palau', highestPointRank: 208, highestPoint: 242 },
  { name: 'Macau', code: 'macau', highestPointRank: 211, highestPoint: 172 },
  { name: 'Denmark', code: 'denmark', highestPointRank: 212, highestPoint: 171 },
  { name: 'Singapore', code: 'singapore', highestPointRank: 213, highestPoint: 164 },
  { name: 'Monaco', code: 'monaco', highestPointRank: 214, highestPoint: 161 },
  { name: 'Bahrain', code: 'bahrain', highestPointRank: 216, highestPoint: 122 },
  { name: 'Qatar', code: 'qatar', highestPointRank: 218, highestPoint: 103 },
  { name: 'Kiribati', code: 'kiribati', highestPointRank: 219, highestPoint: 81 },
  { name: 'Vatican City', code: 'vatican-city', highestPointRank: 221, highestPoint: 75 },
  { name: 'Nauru', code: 'nauru', highestPointRank: 224, highestPoint: 65 },
  { name: 'Bahamas', code: 'bahamas', highestPointRank: 225, highestPoint: 63 },
  { name: 'Marshall Islands', code: 'marshall-islands', highestPointRank: 228, highestPoint: 10 },
  { name: 'Maldives', code: 'maldives', highestPointRank: 229, highestPoint: 5 },
  { name: 'Tuvalu', code: 'tuvalu', highestPointRank: 231, highestPoint: 5 }
];