export const altitudeData = [
  { name: 'China', code: 'CN', highestPointRank: 1, highestPoint: 8848, altitude: 8848, highestPointName: 'Mount Everest' },
  { name: 'Nepal', code: 'NP', highestPointRank: 2, highestPoint: 8848, altitude: 8848, highestPointName: 'Mount Everest' },
  { name: 'Pakistan', code: 'PK', highestPointRank: 3, highestPoint: 8611, altitude: 8611, highestPointName: 'K2' },
  { name: 'India', code: 'IN', highestPointRank: 4, highestPoint: 8586, altitude: 8586, highestPointName: 'Kangchenjunga' },
  { name: 'Bhutan', code: 'bhutan', highestPointRank: 5, highestPoint: 7570, altitude: 7570, highestPointName: 'Gangkhar Puensum' },
  { name: 'Tajikistan', code: 'TJ', highestPointRank: 6, highestPoint: 7495, altitude: 7495, highestPointName: 'Ismoil Somoni Peak' },
  { name: 'Afghanistan', code: 'AF', highestPointRank: 7, highestPoint: 7492, altitude: 7492, highestPointName: 'Noshakh' },
  { name: 'Kyrgyzstan', code: 'KG', highestPointRank: 8, highestPoint: 7439, altitude: 7439, highestPointName: 'Jengish Chokusu' },
  { name: 'Kazakhstan', code: 'KZ', highestPointRank: 9, highestPoint: 7010, altitude: 7010, highestPointName: 'Khan Tengri' },
  { name: 'Argentina', code: 'AR', highestPointRank: 10, highestPoint: 6960, altitude: 6960, highestPointName: 'Aconcagua' },
  { name: 'Chile', code: 'CL', highestPointRank: 11, highestPoint: 6893, altitude: 6893, highestPointName: 'Ojos del Salado' },
  { name: 'Peru', code: 'PE', highestPointRank: 12, highestPoint: 6768, altitude: 6768, highestPointName: 'Huascarán' },
  { name: 'Bolivia', code: 'BO', highestPointRank: 13, highestPoint: 6542, altitude: 6542, highestPointName: 'Sajama' },
  { name: 'Ecuador', code: 'EC', highestPointRank: 14, highestPoint: 6267, altitude: 6267, highestPointName: 'Chimborazo' },
  { name: 'United States', code: 'US', highestPointRank: 15, highestPoint: 6190.5, altitude: 6190.5, highestPointName: 'Denali' },
  { name: 'Canada', code: 'CA', highestPointRank: 16, highestPoint: 5959, altitude: 5959, highestPointName: 'Mount Logan' },
  { name: 'Tanzania', code: 'TZ', highestPointRank: 17, highestPoint: 5892, altitude: 5892, highestPointName: 'Kilimanjaro' },
  { name: 'Myanmar', code: 'MM', highestPointRank: 18, highestPoint: 5881, altitude: 5881, highestPointName: 'Hkakabo Razi' },
  { name: 'Colombia', code: 'CO', highestPointRank: 19, highestPoint: 5700, altitude: 5700, highestPointName: 'Pico Cristóbal Colón' },
  { name: 'Russia', code: 'RU', highestPointRank: 20, highestPoint: 5642, altitude: 5642, highestPointName: 'Mount Elbrus' },
  { name: 'Mexico', code: 'MX', highestPointRank: 21, highestPoint: 5636, altitude: 5636, highestPointName: 'Volcán Citlaltépetl' },
  { name: 'Iran', code: 'IR', highestPointRank: 22, highestPoint: 5610, altitude: 5610, highestPointName: 'Damavand' },
  { name: 'Georgia', code: 'GE', highestPointRank: 23, highestPoint: 5201, altitude: 5201, highestPointName: 'Shkhara' },
  { name: 'Kenya', code: 'KE', highestPointRank: 24, highestPoint: 5199, altitude: 5199, highestPointName: 'Mount Kenya' },
  { name: 'Turkey', code: 'TR', highestPointRank: 25, highestPoint: 5137, altitude: 5137, highestPointName: 'Mount Ararat' },
  { name: 'DR Congo', code: 'CD', highestPointRank: 26, highestPoint: 5109, altitude: 5109, highestPointName: 'Mount Stanley' },
  { name: 'Uganda', code: 'UG', highestPointRank: 27, highestPoint: 5109, altitude: 5109, highestPointName: 'Mount Stanley' },
  { name: 'Venezuela', code: 'VE', highestPointRank: 28, highestPoint: 4978, altitude: 4978, highestPointName: 'Pico Bolívar' },
  { name: 'Indonesia', code: 'ID', highestPointRank: 29, highestPoint: 4884, altitude: 4884, highestPointName: 'Puncak Jaya' },
  { name: 'France', code: 'FR', highestPointRank: 30, highestPoint: 4810, altitude: 4810, highestPointName: 'Mont Blanc' },
  { name: 'Italy', code: 'IT', highestPointRank: 31, highestPoint: 4810, altitude: 4810, highestPointName: 'Monte Bianco' },
  { name: 'Uzbekistan', code: 'UZ', highestPointRank: 32, highestPoint: 4643, altitude: 4643, highestPointName: 'Khazret Sultan' },
  { name: 'Switzerland', code: 'CH', highestPointRank: 33, highestPoint: 4634, altitude: 4634, highestPointName: 'Dufourspitze' },
  { name: 'Ethiopia', code: 'ET', highestPointRank: 34, highestPoint: 4550, altitude: 4550, highestPointName: 'Ras Dejen' },
  { name: 'Papua New Guinea', code: 'PG', highestPointRank: 35, highestPoint: 4509, altitude: 4509, highestPointName: 'Mount Wilhelm' },
  { name: 'Rwanda', code: 'RW', highestPointRank: 36, highestPoint: 4507, altitude: 4507, highestPointName: 'Mount Karisimbi' },
  { name: 'Azerbaijan', code: 'AZ', highestPointRank: 37, highestPoint: 4485, altitude: 4485, highestPointName: 'Mount Bazardüzü' },
  { name: 'Mongolia', code: 'MN', highestPointRank: 38, highestPoint: 4374, altitude: 4374, highestPointName: 'Khüiten Peak' },
  { name: 'Guatemala', code: 'GT', highestPointRank: 39, highestPoint: 4220, altitude: 4220, highestPointName: 'Volcán Tajumulco' },
  { name: 'Morocco', code: 'MA', highestPointRank: 40, highestPoint: 4165, altitude: 4165, highestPointName: 'Jbel Toubkal' },
  { name: 'Malaysia', code: 'MY', highestPointRank: 41, highestPoint: 4095, altitude: 4095, highestPointName: 'Gunung Kinabalu' },
  { name: 'Armenia', code: 'AM', highestPointRank: 42, highestPoint: 4090, altitude: 4090, highestPointName: 'Mount Aragats' },
  { name: 'Cameroon', code: 'CM', highestPointRank: 43, highestPoint: 4040, altitude: 4040, highestPointName: 'Mount Cameroon' },
  { name: 'Taiwan', code: 'TW', highestPointRank: 44, highestPoint: 3952, altitude: 3952, highestPointName: 'Yu Shan' },
  { name: 'Costa Rica', code: 'CR', highestPointRank: 45, highestPoint: 3820, altitude: 3820, highestPointName: 'Cerro Chirripó' },
  { name: 'Austria', code: 'AT', highestPointRank: 46, highestPoint: 3798, altitude: 3798, highestPointName: 'Grossglockner' },
  { name: 'Japan', code: 'JP', highestPointRank: 47, highestPoint: 3776, altitude: 3776, highestPointName: 'Mount Fuji' },
  { name: 'New Zealand', code: 'NZ', highestPointRank: 48, highestPoint: 3724, altitude: 3724, highestPointName: 'Mount Cook' },
  { name: 'Spain', code: 'ES', highestPointRank: 49, highestPoint: 3715, altitude: 3715, highestPointName: 'Teide' },
  { name: 'Greenland', code: 'GL', highestPointRank: 50, highestPoint: 3700, altitude: 3700, highestPointName: 'Gunnbjørn Fjeld' },
  { name: 'Yemen', code: 'YE', highestPointRank: 51, highestPoint: 3666, altitude: 3666, highestPointName: 'Jabal An-Nabi Shu ayb' },
  { name: 'Iraq', code: 'IQ', highestPointRank: 52, highestPoint: 3611, altitude: 3611, highestPointName: 'Cheekha Dar' },
  { name: 'Lesotho', code: 'lesotho', highestPointRank: 53, highestPoint: 3482, altitude: 3482, highestPointName: 'Thabana Ntlenyana' },
  { name: 'Panama', code: 'PA', highestPointRank: 54, highestPoint: 3475, altitude: 3475, highestPointName: 'Volcán Barú' },
  { name: 'South Africa', code: 'ZA', highestPointRank: 55, highestPoint: 3450, altitude: 3450, highestPointName: 'Mafadi' },
  { name: 'Chad', code: 'TD', highestPointRank: 56, highestPoint: 3445, altitude: 3445, highestPointName: 'Emi Koussi' },
  { name: 'South Sudan', code: 'SS', highestPointRank: 57, highestPoint: 3187, altitude: 3187, highestPointName: 'Kinyeti' },
  { name: 'Vietnam', code: 'VN', highestPointRank: 58, highestPoint: 3143, altitude: 3143, highestPointName: 'Fansipan' },
  { name: 'Turkmenistan', code: 'TM', highestPointRank: 59, highestPoint: 3139, altitude: 3139, highestPointName: 'Aýrybaba' },
  { name: 'Saudi Arabia', code: 'SA', highestPointRank: 60, highestPoint: 3133, altitude: 3133, highestPointName: 'Jabal Ferwa’' },
  { name: 'Dominican Republic', code: 'DO', highestPointRank: 61, highestPoint: 3098, altitude: 3098, highestPointName: 'Pico Duarte' },
  { name: 'Lebanon', code: 'LB', highestPointRank: 62, highestPoint: 3088, altitude: 3088, highestPointName: 'Qurnat as Sawda' },
  { name: 'Sudan', code: 'SD', highestPointRank: 64, highestPoint: 3042, altitude: 3042, highestPointName: 'Deriba Caldera' },
  { name: 'Eritrea', code: 'ER', highestPointRank: 65, highestPoint: 3018, altitude: 3018, highestPointName: 'Emba Soira' },
  { name: 'Oman', code: 'OM', highestPointRank: 66, highestPoint: 3009, altitude: 3009, highestPointName: 'Jabal Shams' },
  { name: 'Equatorial Guinea', code: 'GQ', highestPointRank: 67, highestPoint: 3008, altitude: 3008, highestPointName: 'Pico Basile' },
  { name: 'Algeria', code: 'DZ', highestPointRank: 68, highestPoint: 3003, altitude: 3003, highestPointName: 'Mount Tahat' },
  { name: 'Malawi', code: 'MW', highestPointRank: 69, highestPoint: 3002, altitude: 3002, highestPointName: 'Mount Mulanje' },
  { name: 'Brazil', code: 'BR', highestPointRank: 70, highestPoint: 2995, altitude: 2995, highestPointName: 'Pico da Neblina' },
  { name: 'East Timor', code: 'east-timor', highestPointRank: 71, highestPoint: 2963, altitude: 2963, highestPointName: 'Mount Ramelau' },
  { name: 'Germany', code: 'DE', highestPointRank: 72, highestPoint: 2962, altitude: 2962, highestPointName: 'Zugspitze' },
  { name: 'Philippines', code: 'PH', highestPointRank: 73, highestPoint: 2954, altitude: 2954, highestPointName: 'Mount Apo' },
  { name: 'Andorra', code: 'AD', highestPointRank: 74, highestPoint: 2942, altitude: 2942, highestPointName: 'Coma Pedrosa' },
  { name: 'Bulgaria', code: 'BG', highestPointRank: 75, highestPoint: 2925, altitude: 2925, highestPointName: 'Musala' },
  { name: 'Greece', code: 'GR', highestPointRank: 76, highestPoint: 2917, altitude: 2917, highestPointName: 'Mount Olympus' },
  { name: 'Madagascar', code: 'MG', highestPointRank: 77, highestPoint: 2876, altitude: 2876, highestPointName: 'Maromokotro' },
  { name: 'Honduras', code: 'HN', highestPointRank: 78, highestPoint: 2870, altitude: 2870, highestPointName: 'Cerro Las Minas' },
  { name: 'Slovenia', code: 'SI', highestPointRank: 79, highestPoint: 2864, altitude: 2864, highestPointName: 'Triglav' },
  { name: 'Cape Verde', code: 'cape-verde', highestPointRank: 80, highestPoint: 2829, altitude: 2829, highestPointName: 'Pico do Fogo' },
  { name: 'Laos', code: 'LA', highestPointRank: 81, highestPoint: 2817, altitude: 2817, highestPointName: 'Phou Bia' },
  { name: 'Syria', code: 'SY', highestPointRank: 82, highestPoint: 2814, altitude: 2814, highestPointName: 'Jabal el-Sheikh' },
  { name: 'Albania', code: 'AL', highestPointRank: 83, highestPoint: 2764, altitude: 2764, highestPointName: 'Korab' },
  { name: 'North Macedonia', code: 'MK', highestPointRank: 84, highestPoint: 2764, altitude: 2764, highestPointName: 'Golem Korab' },
  { name: 'North Korea', code: 'KP', highestPointRank: 85, highestPoint: 2744, altitude: 2744, highestPointName: 'Paektu-san' },
  { name: 'Guyana', code: 'GY', highestPointRank: 86, highestPoint: 2772, altitude: 2772, highestPointName: 'Mount Roraima' },
  { name: 'El Salvador', code: 'SV', highestPointRank: 87, highestPoint: 2730, altitude: 2730, highestPointName: 'Cerro El Pital' },
  { name: 'Burundi', code: 'burundi', highestPointRank: 88, highestPoint: 2684, altitude: 2684, highestPointName: 'Mount Heha' },
  { name: 'Haiti', code: 'HT', highestPointRank: 89, highestPoint: 2680, altitude: 2680, highestPointName: 'Pic la Selle' },
  { name: 'Slovakia', code: 'SK', highestPointRank: 90, highestPoint: 2655, altitude: 2655, highestPointName: 'Gerlachovský štít' },
  { name: 'Egypt', code: 'EG', highestPointRank: 91, highestPoint: 2629, altitude: 2629, highestPointName: 'Mount Catherine' },
  { name: 'Angola', code: 'AO', highestPointRank: 92, highestPoint: 2620, altitude: 2620, highestPointName: 'Mount Moco' },
  { name: 'Liechtenstein', code: 'liechtenstein', highestPointRank: 93, highestPoint: 2599, altitude: 2599, highestPointName: 'Grauspitz' },
  { name: 'Zimbabwe', code: 'ZW', highestPointRank: 94, highestPoint: 2592, altitude: 2592, highestPointName: 'Mount Nyangani' },
  { name: 'Namibia', code: 'NA', highestPointRank: 95, highestPoint: 2573, altitude: 2573, highestPointName: 'Königstein' },
  { name: 'Thailand', code: 'TH', highestPointRank: 96, highestPoint: 2565, altitude: 2565, highestPointName: 'Doi Inthanon' },
  { name: 'Romania', code: 'RO', highestPointRank: 97, highestPoint: 2544, altitude: 2544, highestPointName: 'Moldoveanu' },
  { name: 'Montenegro', code: 'ME', highestPointRank: 98, highestPoint: 2534, altitude: 2534, highestPointName: 'Zla Kolata' },
  { name: 'Sri Lanka', code: 'LK', highestPointRank: 99, highestPoint: 2524, altitude: 2524, highestPointName: 'Pidurutalagala' },
  { name: 'Poland', code: 'PL', highestPointRank: 100, highestPoint: 2499, altitude: 2499, highestPointName: 'Northwestern peak of Rysy' },
  { name: 'Norway', code: 'NO', highestPointRank: 101, highestPoint: 2469, altitude: 2469, highestPointName: 'Galdhøpiggen' },
  { name: 'Somalia', code: 'SO', highestPointRank: 102, highestPoint: 2450, altitude: 2450, highestPointName: 'Shimbiris' },
  { name: 'Mozambique', code: 'MZ', highestPointRank: 103, highestPoint: 2436, altitude: 2436, highestPointName: 'Monte Binga' },
  { name: 'Nigeria', code: 'NG', highestPointRank: 104, highestPoint: 2419, altitude: 2419, highestPointName: 'Chappal Waddi' },
  { name: 'Bosnia and Herzegovina', code: 'BA', highestPointRank: 105, highestPoint: 2386, altitude: 2386, highestPointName: 'Maglić' },
  { name: 'Comoros', code: 'comoros', highestPointRank: 106, highestPoint: 2360, altitude: 2360, highestPointName: 'Mount Karthala' },
  { name: 'Portugal', code: 'PT', highestPointRank: 107, highestPoint: 2351, altitude: 2351, highestPointName: 'Montanha do Pico' },
  { name: 'Solomon Islands', code: 'solomon-islands', highestPointRank: 108, highestPoint: 2335, altitude: 2335, highestPointName: 'Mount Popomanaseu' },
  { name: 'Zambia', code: 'ZM', highestPointRank: 109, highestPoint: 2329, altitude: 2329, highestPointName: 'Mafinga Central' },
  { name: 'Libya', code: 'LY', highestPointRank: 110, highestPoint: 2267, altitude: 2267, highestPointName: 'Bikku Bitti' },
  { name: 'Jamaica', code: 'JM', highestPointRank: 111, highestPoint: 2256, altitude: 2256, highestPointName: 'Blue Mountain Peak' },
  { name: 'Australia', code: 'AU', highestPointRank: 113, highestPoint: 2228, altitude: 2228, highestPointName: 'Mount Kosciuszko' },
  { name: 'Iceland', code: 'IS', highestPointRank: 115, highestPoint: 2110, altitude: 2110, highestPointName: 'Hvannadalshnúkur' },
  { name: 'Nicaragua', code: 'NI', highestPointRank: 116, highestPoint: 2107, altitude: 2107, highestPointName: 'Mogotón' },
  { name: 'Sweden', code: 'SE', highestPointRank: 117, highestPoint: 2097, altitude: 2097, highestPointName: 'Kebnekaise' },
  { name: 'Ukraine', code: 'UA', highestPointRank: 118, highestPoint: 2061, altitude: 2061, highestPointName: 'Hoverla' },
  { name: 'Djibouti', code: 'DJ', highestPointRank: 119, highestPoint: 2028, altitude: 2028, highestPointName: 'Mousa Ali' },
  { name: 'Sao Tome and Principe', code: 'sao-tome-and-principe', highestPointRank: 120, highestPoint: 2024, altitude: 2024, highestPointName: 'Pico de São Tomé' },
  { name: 'Niger', code: 'NE', highestPointRank: 121, highestPoint: 2022, altitude: 2022, highestPointName: 'Mont Idoukal-n-Taghès' },
  { name: 'Cuba', code: 'CU', highestPointRank: 122, highestPoint: 1974, altitude: 1974, highestPointName: 'Pico Turquino' },
  { name: 'Cyprus', code: 'CY', highestPointRank: 123, highestPoint: 1951, altitude: 1951, highestPointName: 'Mount Olympus' },
  { name: 'South Korea', code: 'KR', highestPointRank: 124, highestPoint: 1950, altitude: 1950, highestPointName: 'Halla-san on Jejudo' },
  { name: 'Sierra Leone', code: 'sierra-leone', highestPointRank: 125, highestPoint: 1948, altitude: 1948, highestPointName: 'Mount Bintumani' },
  { name: 'United Arab Emirates', code: 'AE', highestPointRank: 126, highestPoint: 1910, altitude: 1910, highestPointName: 'Jabal Al Jais' },
  { name: 'Vanuatu', code: 'VU', highestPointRank: 127, highestPoint: 1877, altitude: 1877, highestPointName: 'Mount Tabwemasana' },
  { name: 'Eswatini', code: 'eswatini', highestPointRank: 128, highestPoint: 1862, altitude: 1862, highestPointName: 'Emlembe' },
  { name: 'Samoa', code: 'samoa', highestPointRank: 129, highestPoint: 1857, altitude: 1857, highestPointName: 'Mauga Silisili on Savai' },
  { name: 'Jordan', code: 'JO', highestPointRank: 130, highestPoint: 1854, altitude: 1854, highestPointName: 'Jabal Umm ad Dami' },
  { name: 'Brunei', code: 'BN', highestPointRank: 131, highestPoint: 1850, altitude: 1850, highestPointName: 'Bukit Pagon' },
  { name: 'Croatia', code: 'HR', highestPointRank: 132, highestPoint: 1831, altitude: 1831, highestPointName: 'Dinara' },
  { name: 'Cambodia', code: 'KH', highestPointRank: 133, highestPoint: 1810, altitude: 1810, highestPointName: 'Phnom Aural' },
  { name: 'Ivory Coast', code: 'CI', highestPointRank: 134, highestPoint: 1752, altitude: 1752, highestPointName: 'Mont Nimba' },
  { name: 'Guinea', code: 'GN', highestPointRank: 135, highestPoint: 1752, altitude: 1752, highestPointName: 'Mont Nimba' },
  { name: 'Tunisia', code: 'TN', highestPointRank: 137, highestPoint: 1544, altitude: 1544, highestPointName: 'Jebel ech Chambi' },
  { name: 'Botswana', code: 'BW', highestPointRank: 138, highestPoint: 1491, altitude: 1491, highestPointName: 'Otse Hill' },
  { name: 'Dominica', code: 'dominica', highestPointRank: 140, highestPoint: 1447, altitude: 1447, highestPointName: 'Morne Diablotins' },
  { name: 'Liberia', code: 'liberia', highestPointRank: 141, highestPoint: 1440, altitude: 1440, highestPointName: 'Mount Wuteve' },
  { name: 'Central African Republic', code: 'CF', highestPointRank: 142, highestPoint: 1420, altitude: 1420, highestPointName: 'Mont Ngaoui' },
  { name: 'United Kingdom', code: 'GB', highestPointRank: 144, highestPoint: 1345, altitude: 1345, highestPointName: 'Ben Nevis' },
  { name: 'Puerto Rico', code: 'PR', highestPointRank: 145, highestPoint: 1338, altitude: 1338, highestPointName: 'Cerro de Punta' },
  { name: 'Finland', code: 'FI', highestPointRank: 146, highestPoint: 1324, altitude: 1324, highestPointName: 'Halti' },
  { name: 'Fiji', code: 'FJ', highestPointRank: 147, highestPoint: 1324, altitude: 1324, highestPointName: 'Tomanivi' },
  { name: 'Bangladesh', code: 'BD', highestPointRank: 148, highestPoint: 1280, altitude: 1280, highestPointName: 'Tazing Dong' },
  { name: 'Saint Vincent and the Grenadines', code: 'saint-vincent-and-the-grenadines', highestPointRank: 149, highestPoint: 1234, altitude: 1234, highestPointName: 'La Soufrière' },
  { name: 'Suriname', code: 'SR', highestPointRank: 150, highestPoint: 1230, altitude: 1230, highestPointName: 'Juliana Top' },
  { name: 'Israel', code: 'IL', highestPointRank: 151, highestPoint: 1208, altitude: 1208, highestPointName: 'Mount Meron' },
  { name: 'Saint Kitts and Nevis', code: 'KN', highestPointRank: 152, highestPoint: 1156, altitude: 1156, highestPointName: 'Mount Liamuiga' },
  { name: 'Mali', code: 'ML', highestPointRank: 153, highestPoint: 1155, altitude: 1155, highestPointName: 'Hombori Tondo' },
  { name: 'Belize', code: 'BZ', highestPointRank: 154, highestPoint: 1124, altitude: 1124, highestPointName: 'Doyles Delight' },
  { name: 'Gabon', code: 'GA', highestPointRank: 155, highestPoint: 1070, altitude: 1070, highestPointName: 'Mont Bengoué' },
  { name: 'Ireland', code: 'IE', highestPointRank: 156, highestPoint: 1038, altitude: 1038, highestPointName: 'Carrauntoohil' },
  { name: 'Tonga', code: 'tonga', highestPointRank: 157, highestPoint: 1033, altitude: 1033, highestPointName: 'Unnamed location' },
  { name: 'Palestine', code: 'PS', highestPointRank: 158, highestPoint: 1030, altitude: 1030, highestPointName: 'Mount Nabi Yunis' },
  { name: 'Republic of the Congo', code: 'CG', highestPointRank: 159, highestPoint: 1020, altitude: 1020, highestPointName: 'Mont Nabemba' },
  { name: 'Hungary', code: 'HU', highestPointRank: 160, highestPoint: 1014, altitude: 1014, highestPointName: 'Kékes' },
  { name: 'Togo', code: 'togo', highestPointRank: 161, highestPoint: 986, altitude: 986, highestPointName: 'Mont Agou' },
  { name: 'Hong Kong', code: 'HK', highestPointRank: 164, highestPoint: 958, altitude: 958, highestPointName: 'Tai Mo Shan' },
  { name: 'Saint Lucia', code: 'saint-lucia', highestPointRank: 165, highestPoint: 950, altitude: 950, highestPointName: 'Mount Gimie' },
  { name: 'Trinidad and Tobago', code: 'TT', highestPointRank: 166, highestPoint: 940, altitude: 940, highestPointName: 'El Cerro del Aripo' },
  { name: 'Seychelles', code: 'seychelles', highestPointRank: 169, highestPoint: 905, altitude: 905, highestPointName: 'Morne Seychellois' },
  { name: 'Netherlands', code: 'NL', highestPointRank: 170, highestPoint: 887, altitude: 887, highestPointName: 'Mount Scenery' },
  { name: 'Ghana', code: 'GH', highestPointRank: 171, highestPoint: 880, altitude: 880, highestPointName: 'Mount Afadjato' },
  { name: 'Paraguay', code: 'PY', highestPointRank: 174, highestPoint: 842, altitude: 842, highestPointName: 'Cerro Peró' },
  { name: 'Grenada', code: 'grenada', highestPointRank: 175, highestPoint: 840, altitude: 840, highestPointName: 'Mount Saint Catherine' },
  { name: 'Mauritius', code: 'MU', highestPointRank: 176, highestPoint: 828, altitude: 828, highestPointName: 'Piton de la Petite Rivière Noire' },
  { name: 'Micronesia', code: 'FM', highestPointRank: 177, highestPoint: 782, altitude: 782, highestPointName: 'Nanlaud on Pohnpei' },
  { name: 'Burkina Faso', code: 'BF', highestPointRank: 178, highestPoint: 749, altitude: 749, highestPointName: 'Mount Tenakourou' },
  { name: 'San Marino', code: 'SM', highestPointRank: 179, highestPoint: 739, altitude: 739, highestPointName: 'Monte Titano' },
  { name: 'Belgium', code: 'BE', highestPointRank: 181, highestPoint: 694, altitude: 694, highestPointName: 'Signal de Botrange' },
  { name: 'Benin', code: 'benin', highestPointRank: 183, highestPoint: 658, altitude: 658, highestPointName: 'Mont Sokbaro' },
  { name: 'Senegal', code: 'SN', highestPointRank: 185, highestPoint: 648, altitude: 648, highestPointName: 'Baunez ridge' },
  { name: 'Luxembourg', code: 'LU', highestPointRank: 188, highestPoint: 560, altitude: 560, highestPointName: 'Kneiff' },
  { name: 'Uruguay', code: 'UY', highestPointRank: 191, highestPoint: 514, altitude: 514, highestPointName: 'Cerro Catedral' },
  { name: 'Moldova', code: 'MD', highestPointRank: 193, highestPoint: 430, altitude: 430, highestPointName: 'Bălănești Hill' },
  { name: 'Antigua and Barbuda', code: 'AG', highestPointRank: 197, highestPoint: 402, altitude: 402, highestPointName: 'Boggy Peak' },
  { name: 'Belarus', code: 'BY', highestPointRank: 200, highestPoint: 346, altitude: 346, highestPointName: 'Dzyarzhynskaya Hara' },
  { name: 'Barbados', code: 'BB', highestPointRank: 201, highestPoint: 336, altitude: 336, highestPointName: 'Mount Hillaby' },
  { name: 'Estonia', code: 'EE', highestPointRank: 202, highestPoint: 318, altitude: 318, highestPointName: 'Suur Munamägi' },
  { name: 'Latvia', code: 'LV', highestPointRank: 203, highestPoint: 312, altitude: 312, highestPointName: 'Gaiziņkalns' },
  { name: 'Kuwait', code: 'KW', highestPointRank: 204, highestPoint: 306, altitude: 306, highestPointName: 'Mutla Ridge' },
  { name: 'Lithuania', code: 'LT', highestPointRank: 205, highestPoint: 294, altitude: 294, highestPointName: 'Aukštojas Hill' },
  { name: 'Guinea-Bissau', code: 'GW', highestPointRank: 206, highestPoint: 262, altitude: 262, highestPointName: 'Monte Torin' },
  { name: 'Malta', code: 'MT', highestPointRank: 207, highestPoint: 253, altitude: 253, highestPointName: 'Ta Dmejrek' },
  { name: 'Palau', code: 'PW', highestPointRank: 208, highestPoint: 242, altitude: 242, highestPointName: 'Mount Ngerchelchuus' },
  { name: 'Macau', code: 'macau', highestPointRank: 211, highestPoint: 172, altitude: 172, highestPointName: 'Coloane Alto' },
  { name: 'Denmark', code: 'DK', highestPointRank: 212, highestPoint: 171, altitude: 171, highestPointName: 'Møllehøj' },
  { name: 'Singapore', code: 'SG', highestPointRank: 213, highestPoint: 164, altitude: 164, highestPointName: 'Bukit Timah Hill' },
  { name: 'Monaco', code: 'MC', highestPointRank: 214, highestPoint: 161, altitude: 161, highestPointName: 'along Chemin des Révoires' },
  { name: 'Bahrain', code: 'BH', highestPointRank: 216, highestPoint: 122, altitude: 122, highestPointName: 'Mountain of Smoke' },
  { name: 'Qatar', code: 'QA', highestPointRank: 218, highestPoint: 103, altitude: 103, highestPointName: 'Qurayn Abu al Bawl' },
  { name: 'Kiribati', code: 'KI', highestPointRank: 219, highestPoint: 81, altitude: 81, highestPointName: 'Unnamed location' },
  { name: 'Vatican City', code: 'vatican-city', highestPointRank: 221, highestPoint: 75, altitude: 75, highestPointName: 'Vatican Hill' },
  { name: 'Nauru', code: 'nauru', highestPointRank: 224, highestPoint: 65, altitude: 65, highestPointName: 'Command Ridge' },
  { name: 'Bahamas', code: 'BS', highestPointRank: 225, highestPoint: 63, altitude: 63, highestPointName: 'Mount Alvernia' },
  { name: 'Marshall Islands', code: 'marshall-islands', highestPointRank: 228, highestPoint: 10, altitude: 10, highestPointName: 'Unnamed location' },
  { name: 'Maldives', code: 'MV', highestPointRank: 229, highestPoint: 5, altitude: 5, highestPointName: 'Mount Villingili' },
  { name: 'Tuvalu', code: 'tuvalu', highestPointRank: 231, highestPoint: 5, altitude: 5, highestPointName: 'Unnamed location' }
];