export const beerData = [
{ name: 'Czechia', code: 'czechia', beerConsumptionRank: 1, beerConsumption: 152.1 },
{ name: 'Austria', code: 'austria', beerConsumptionRank: 2, beerConsumption: 106.5 },
{ name: 'Lithuania', code: 'lithuania', beerConsumptionRank: 3, beerConsumption: 103.3 },
{ name: 'Ireland', code: 'ireland', beerConsumptionRank: 4, beerConsumption: 100.6 },
{ name: 'Croatia', code: 'croatia', beerConsumptionRank: 5, beerConsumption: 94.2 },
{ name: 'Spain', code: 'spain', beerConsumptionRank: 6, beerConsumption: 93 },
{ name: 'Estonia', code: 'estonia', beerConsumptionRank: 7, beerConsumption: 92.6 },
{ name: 'Germany', code: 'germany', beerConsumptionRank: 8, beerConsumption: 88.8 },
{ name: 'Romania', code: 'romania', beerConsumptionRank: 9, beerConsumption: 84.4 },
{ name: 'Slovenia', code: 'slovenia', beerConsumptionRank: 10, beerConsumption: 84.1 },
{ name: 'Latvia', code: 'latvia', beerConsumptionRank: 11, beerConsumption: 83.8 },
{ name: 'Poland', code: 'poland', beerConsumptionRank: 12, beerConsumption: 83 },
{ name: 'Panama', code: 'panama', beerConsumptionRank: 13, beerConsumption: 81 },
{ name: 'Bulgaria', code: 'bulgaria', beerConsumptionRank: 14, beerConsumption: 80 },
{ name: 'Mexico', code: 'mexico', beerConsumptionRank: 15, beerConsumption: 79.8 },
{ name: 'Gabon', code: 'gabon', beerConsumptionRank: 16, beerConsumption: 78.4 },
{ name: 'Slovakia', code: 'slovakia', beerConsumptionRank: 17, beerConsumption: 73.5 },
{ name: 'South Africa', code: 'south_africa', beerConsumptionRank: 18, beerConsumption: 72.7 },
{ name: 'Bosnia-Herzegovina', code: 'bosnia_herzegovina', beerConsumptionRank: 19, beerConsumption: 71.3 },
{ name: 'Hungary', code: 'hungary', beerConsumptionRank: 20, beerConsumption: 70.1 },
{ name: 'Brazil', code: 'brazil', beerConsumptionRank: 21, beerConsumption: 69.9 },
{ name: 'Finland', code: 'finland', beerConsumptionRank: 22, beerConsumption: 69.6 },
{ name: 'Netherlands', code: 'netherlands', beerConsumptionRank: 23, beerConsumption: 69 },
{ name: 'Australia', code: 'australia', beerConsumptionRank: 24, beerConsumption: 67.5 },
{ name: 'UK', code: 'uk', beerConsumptionRank: 25, beerConsumption: 65.5 },
{ name: 'Portugal', code: 'portugal', beerConsumptionRank: 26, beerConsumption: 64.8 },
{ name: 'United States', code: 'united_states', beerConsumptionRank: 27, beerConsumption: 63.1 },
{ name: 'Serbia', code: 'serbia', beerConsumptionRank: 28, beerConsumption: 62.3 },
{ name: 'Puerto Rico', code: 'puerto_rico', beerConsumptionRank: 29, beerConsumption: 61 },
{ name: 'Denmark', code: 'denmark', beerConsumptionRank: 30, beerConsumption: 60.9 },
{ name: 'Russia', code: 'russia', beerConsumptionRank: 31, beerConsumption: 60.4 },
{ name: 'Namibia', code: 'namibia', beerConsumptionRank: 32, beerConsumption: 60.1 },
{ name: 'Belgium', code: 'belgium', beerConsumptionRank: 33, beerConsumption: 57.7 },
{ name: 'Cambodia', code: 'cambodia', beerConsumptionRank: 34, beerConsumption: 57 },
{ name: 'Laos', code: 'laos', beerConsumptionRank: 35, beerConsumption: 55.5 },
];