export const beerData = [
{ name: 'Czechia', code: 'CZ', beerConsumptionRank: 1, beerConsumption: 152.1, beer: 152.1 },
{ name: 'Austria', code: 'AT', beerConsumptionRank: 2, beerConsumption: 106.5, beer: 106.5 },
{ name: 'Lithuania', code: 'LT', beerConsumptionRank: 3, beerConsumption: 103.3, beer: 103.3 },
{ name: 'Ireland', code: 'IE', beerConsumptionRank: 4, beerConsumption: 100.6, beer: 100.6 },
{ name: 'Croatia', code: 'HR', beerConsumptionRank: 5, beerConsumption: 94.2, beer: 94.2 },
{ name: 'Spain', code: 'ES', beerConsumptionRank: 6, beerConsumption: 93, beer: 93 },
{ name: 'Estonia', code: 'EE', beerConsumptionRank: 7, beerConsumption: 92.6, beer: 92.6 },
{ name: 'Germany', code: 'DE', beerConsumptionRank: 8, beerConsumption: 88.8, beer: 88.8 },
{ name: 'Romania', code: 'RO', beerConsumptionRank: 9, beerConsumption: 84.4, beer: 84.4 },
{ name: 'Slovenia', code: 'SI', beerConsumptionRank: 10, beerConsumption: 84.1, beer: 84.1 },
{ name: 'Latvia', code: 'LV', beerConsumptionRank: 11, beerConsumption: 83.8, beer: 83.8 },
{ name: 'Poland', code: 'PL', beerConsumptionRank: 12, beerConsumption: 83, beer: 83 },
{ name: 'Panama', code: 'PA', beerConsumptionRank: 13, beerConsumption: 81, beer: 81 },
{ name: 'Bulgaria', code: 'BG', beerConsumptionRank: 14, beerConsumption: 80, beer: 80 },
{ name: 'Mexico', code: 'MX', beerConsumptionRank: 15, beerConsumption: 79.8, beer: 79.8 },
{ name: 'Gabon', code: 'GA', beerConsumptionRank: 16, beerConsumption: 78.4, beer: 78.4 },
{ name: 'Slovakia', code: 'SK', beerConsumptionRank: 17, beerConsumption: 73.5, beer: 73.5 },
{ name: 'South Africa', code: 'ZA', beerConsumptionRank: 18, beerConsumption: 72.7, beer: 72.7 },
{ name: 'Bosnia Herzegovina', code: 'BA', beerConsumptionRank: 19, beerConsumption: 71.3, beer: 71.3 },
{ name: 'Hungary', code: 'HU', beerConsumptionRank: 20, beerConsumption: 70.1, beer: 70.1 },
{ name: 'Brazil', code: 'BR', beerConsumptionRank: 21, beerConsumption: 69.9, beer: 69.9 },
{ name: 'Finland', code: 'FI', beerConsumptionRank: 22, beerConsumption: 69.6, beer: 69.6 },
{ name: 'Netherlands', code: 'NL', beerConsumptionRank: 23, beerConsumption: 69, beer: 69 },
{ name: 'Australia', code: 'AU', beerConsumptionRank: 24, beerConsumption: 67.5, beer: 67.5 },
{ name: 'United Kingdom', code: 'GB', beerConsumptionRank: 25, beerConsumption: 65.5, beer: 65.5 },
{ name: 'Portugal', code: 'PT', beerConsumptionRank: 26, beerConsumption: 64.8, beer: 64.8 },
{ name: 'United States', code: 'US', beerConsumptionRank: 27, beerConsumption: 63.1, beer: 63.1 },
{ name: 'Serbia', code: 'RS', beerConsumptionRank: 28, beerConsumption: 62.3, beer: 62.3 },
{ name: 'Puerto Rico', code: 'PR', beerConsumptionRank: 29, beerConsumption: 61, beer: 61 },
{ name: 'Denmark', code: 'DK', beerConsumptionRank: 30, beerConsumption: 60.9, beer: 60.9 },
{ name: 'Russia', code: 'RU', beerConsumptionRank: 31, beerConsumption: 60.4, beer: 60.4 },
{ name: 'Namibia', code: 'NA', beerConsumptionRank: 32, beerConsumption: 60.1, beer: 60.1 },
{ name: 'Belgium', code: 'BE', beerConsumptionRank: 33, beerConsumption: 57.7, beer: 57.7 },
{ name: 'Cambodia', code: 'KH', beerConsumptionRank: 34, beerConsumption: 57, beer: 57 },
{ name: 'Laos', code: 'LA', beerConsumptionRank: 35, beerConsumption: 55.5, beer: 55.5 },
];