// js/categories/bigmac.js
// Ranking countries by Big Mac price (USD)

export const bigmacData = [
  { name: "Switzerland", code: "CH", bigMacPrice: 7.99, bigMacRank: 1 },
  { name: "Argentina", code: "AR", bigMacPrice: 6.95, bigMacRank: 2 },
  { name: "Uruguay", code: "UY", bigMacPrice: 6.91, bigMacRank: 3 },
  { name: "Norway", code: "NO", bigMacPrice: 6.67, bigMacRank: 4 },
  { name: "Costa Rica", code: "CR", bigMacPrice: 5.90, bigMacRank: 5 },
  { name: "United States", code: "US", bigMacPrice: 5.79, bigMacRank: 6 },
  { name: "United Kingdom", code: "GB", bigMacPrice: 5.73, bigMacRank: 7 },
  { name: "Sweden", code: "SE", bigMacPrice: 5.67, bigMacRank: 8 },
  { name: "Denmark", code: "DK", bigMacPrice: 5.49, bigMacRank: 9 },
  { name: "Canada", code: "CA", bigMacPrice: 5.43, bigMacRank: 10 },
  { name: "Lebanon", code: "LB", bigMacPrice: 5.36, bigMacRank: 11 },
  { name: "Turkey", code: "TR", bigMacPrice: 5.32, bigMacRank: 12 },
  { name: "Poland", code: "PL", bigMacPrice: 5.21, bigMacRank: 13 },
  { name: "Colombia", code: "CO", bigMacPrice: 5.17, bigMacRank: 14 },
  { name: "Singapore", code: "SG", bigMacPrice: 5.17, bigMacRank: 15 },
  { name: "Saudi Arabia", code: "SA", bigMacPrice: 5.07, bigMacRank: 16 },
  { name: "United Arab Emirates", code: "AE", bigMacPrice: 4.90, bigMacRank: 17 },
  { name: "Australia", code: "AU", bigMacPrice: 4.87, bigMacRank: 18 },
  { name: "New Zealand", code: "NZ", bigMacPrice: 4.77, bigMacRank: 19 },
  { name: "Israel", code: "IL", bigMacPrice: 4.71, bigMacRank: 20 },
  { name: "Mexico", code: "MX", bigMacPrice: 4.60, bigMacRank: 21 },
  { name: "Czechia", code: "CZ", bigMacPrice: 4.56, bigMacRank: 22 },
  { name: "Chile", code: "CL", bigMacPrice: 4.55, bigMacRank: 23 },
  { name: "Kuwait", code: "KW", bigMacPrice: 4.54, bigMacRank: 24 },
  { name: "Peru", code: "PE", bigMacPrice: 4.53, bigMacRank: 25 },
  { name: "Bahrain", code: "BH", bigMacPrice: 4.51, bigMacRank: 26 },
  { name: "Nicaragua", code: "NI", bigMacPrice: 4.48, bigMacRank: 27 },
  { name: "Venezuela", code: "VE", bigMacPrice: 4.45, bigMacRank: 28 },
  { name: "Honduras", code: "HN", bigMacPrice: 4.12, bigMacRank: 29 },
  { name: "Qatar", code: "QA", bigMacPrice: 4.12, bigMacRank: 30 },
  { name: "Brazil", code: "BR", bigMacPrice: 4.03, bigMacRank: 31 },
  { name: "Thailand", code: "TH", bigMacPrice: 4.01, bigMacRank: 32 },
  { name: "Guatemala", code: "GT", bigMacPrice: 4.01, bigMacRank: 33 },
  { name: "Oman", code: "OM", bigMacPrice: 3.97, bigMacRank: 34 },
  { name: "South Korea", code: "KR", bigMacPrice: 3.84, bigMacRank: 35 },
  { name: "Pakistan", code: "PK", bigMacPrice: 3.77, bigMacRank: 36 },
  { name: "Azerbaijan", code: "AZ", bigMacPrice: 3.67, bigMacRank: 37 },
  { name: "Hungary", code: "HU", bigMacPrice: 3.65, bigMacRank: 38 },
  { name: "Jordan", code: "JO", bigMacPrice: 3.53, bigMacRank: 39 },
  { name: "China", code: "CN", bigMacPrice: 3.52, bigMacRank: 40 },
  { name: "Moldova", code: "MD", bigMacPrice: 3.52, bigMacRank: 41 },
  { name: "Romania", code: "RO", bigMacPrice: 3.43, bigMacRank: 42 },
  { name: "Japan", code: "JP", bigMacPrice: 3.11, bigMacRank: 43 },
  { name: "Hong Kong", code: "HK", bigMacPrice: 3.08, bigMacRank: 44 },
  { name: "Vietnam", code: "VN", bigMacPrice: 3.03, bigMacRank: 45 },
  { name: "Malaysia", code: "MY", bigMacPrice: 3.00, bigMacRank: 46 },
  { name: "Philippines", code: "PH", bigMacPrice: 2.89, bigMacRank: 47 },
  { name: "Ukraine", code: "UA", bigMacPrice: 2.86, bigMacRank: 48 },
  { name: "South Africa", code: "ZA", bigMacPrice: 2.78, bigMacRank: 49 },
  { name: "Egypt", code: "EG", bigMacPrice: 2.69, bigMacRank: 50 },
  { name: "India", code: "IN", bigMacPrice: 2.62, bigMacRank: 51 },
  { name: "Indonesia", code: "ID", bigMacPrice: 2.54, bigMacRank: 52 },
  { name: "Taiwan", code: "TW", bigMacPrice: 2.38, bigMacRank: 53 }
];