export const coastlineData = [
  { name: 'Canada', code: 'canada', coastlineRank: 1, coastline: 202080 },
  { name: 'Norway', code: 'norway', coastlineRank: 2, coastline: 83281 },
  { name: 'Indonesia', code: 'indonesia', coastlineRank: 3, coastline: 54717 },
  { name: 'Philippines', code: 'philippines', coastlineRank: 4, coastline: 36289 },
  { name: 'Japan', code: 'japan', coastlineRank: 5, coastline: 29751 },
  { name: 'Australia', code: 'australia', coastlineRank: 6, coastline: 25760 },
  { name: 'United States', code: 'united-states', coastlineRank: 7, coastline: 19924 },
  { name: 'New Zealand', code: 'new-zealand', coastlineRank: 8, coastline: 15134 },
  { name: 'Greece', code: 'greece', coastlineRank: 9, coastline: 13676 },
  { name: 'United Kingdom', code: 'united-kingdom', coastlineRank: 10, coastline: 12429 },
  { name: 'Mexico', code: 'mexico', coastlineRank: 11, coastline: 9330 },
  { name: 'Italy', code: 'italy', coastlineRank: 12, coastline: 7600 },
  { name: 'Brazil', code: 'brazil', coastlineRank: 13, coastline: 7491 },
  { name: 'Turkey', code: 'turkey', coastlineRank: 14, coastline: 7200 },
  { name: 'Chile', code: 'chile', coastlineRank: 15, coastline: 6435 },
  { name: 'Argentina', code: 'argentina', coastlineRank: 16, coastline: 4989 },
  { name: 'France', code: 'france', coastlineRank: 17, coastline: 4853 },
  { name: 'Malaysia', code: 'malaysia', coastlineRank: 18, coastline: 4675 },
  { name: 'South Africa', code: 'south-africa', coastlineRank: 19, coastline: 2798 },
  { name: 'Saudi Arabia', code: 'saudi-arabia', coastlineRank: 20, coastline: 2640 },
  { name: 'Egypt', code: 'egypt', coastlineRank: 21, coastline: 2450 },
  { name: 'Peru', code: 'peru', coastlineRank: 22, coastline: 2414 },
  { name: 'South Korea', code: 'south-korea', coastlineRank: 23, coastline: 2413 },
  { name: 'Vietnam', code: 'vietnam', coastlineRank: 24, coastline: 3260 },
  { name: 'Thailand', code: 'thailand', coastlineRank: 25, coastline: 3219 },
  { name: 'Sweden', code: 'sweden', coastlineRank: 26, coastline: 3218 },
  { name: 'Portugal', code: 'portugal', coastlineRank: 27, coastline: 1794 },
  { name: 'Morocco', code: 'morocco', coastlineRank: 28, coastline: 1835 },
  { name: 'Sri Lanka', code: 'sri-lanka', coastlineRank: 29, coastline: 1340 },
  { name: 'Kenya', code: 'kenya', coastlineRank: 30, coastline: 536 },
];
