export const coastlineData = [
  { name: 'Canada', code: 'CA', coastlineRank: 1, coastline: 202080 },
  { name: 'Norway', code: 'NO', coastlineRank: 2, coastline: 83281 },
  { name: 'Indonesia', code: 'ID', coastlineRank: 3, coastline: 54717 },
  { name: 'Philippines', code: 'PH', coastlineRank: 4, coastline: 36289 },
  { name: 'Japan', code: 'JP', coastlineRank: 5, coastline: 29751 },
  { name: 'Australia', code: 'AU', coastlineRank: 6, coastline: 25760 },
  { name: 'United States', code: 'US', coastlineRank: 7, coastline: 19924 },
  { name: 'New Zealand', code: 'NZ', coastlineRank: 8, coastline: 15134 },
  { name: 'Greece', code: 'GR', coastlineRank: 9, coastline: 13676 },
  { name: 'United Kingdom', code: 'GB', coastlineRank: 10, coastline: 12429 },
  { name: 'Mexico', code: 'MX', coastlineRank: 11, coastline: 9330 },
  { name: 'Italy', code: 'IT', coastlineRank: 12, coastline: 7600 },
  { name: 'Brazil', code: 'BR', coastlineRank: 13, coastline: 7491 },
  { name: 'Turkey', code: 'TR', coastlineRank: 14, coastline: 7200 },
  { name: 'Chile', code: 'CL', coastlineRank: 15, coastline: 6435 },
  { name: 'Argentina', code: 'AR', coastlineRank: 16, coastline: 4989 },
  { name: 'France', code: 'FR', coastlineRank: 17, coastline: 4853 },
  { name: 'Malaysia', code: 'MY', coastlineRank: 18, coastline: 4675 },
  { name: 'South Africa', code: 'ZA', coastlineRank: 19, coastline: 2798 },
  { name: 'Saudi Arabia', code: 'SA', coastlineRank: 20, coastline: 2640 },
  { name: 'Egypt', code: 'EG', coastlineRank: 21, coastline: 2450 },
  { name: 'Peru', code: 'PE', coastlineRank: 22, coastline: 2414 },
  { name: 'South Korea', code: 'KR', coastlineRank: 23, coastline: 2413 },
  { name: 'Vietnam', code: 'VN', coastlineRank: 24, coastline: 3260 },
  { name: 'Thailand', code: 'TH', coastlineRank: 25, coastline: 3219 },
  { name: 'Sweden', code: 'SE', coastlineRank: 26, coastline: 3218 },
  { name: 'Portugal', code: 'PT', coastlineRank: 27, coastline: 1794 },
  { name: 'Morocco', code: 'MA', coastlineRank: 28, coastline: 1835 },
  { name: 'Sri Lanka', code: 'LK', coastlineRank: 29, coastline: 1340 },
  { name: 'Kenya', code: 'KE', coastlineRank: 30, coastline: 536 },
];