export const coastlineData = [
  { name: 'Canada', code: 'CA', coastlineRank: 1, coastline: 202080 },
  { name: 'Indonesia', code: 'ID', coastlineRank: 2, coastline: 54716 },
  { name: 'Greenland', code: 'GL', coastlineRank: 3, coastline: 44087 },
  { name: 'Russia', code: 'RU', coastlineRank: 4, coastline: 37653 },
  { name: 'Philippines', code: 'PH', coastlineRank: 5, coastline: 36289 },
  { name: 'Japan', code: 'JP', coastlineRank: 6, coastline: 29751 },
  { name: 'Australia', code: 'AU', coastlineRank: 7, coastline: 25760 },
  { name: 'Norway', code: 'NO', coastlineRank: 8, coastline: 25148 },
  { name: 'United States', code: 'US', coastlineRank: 9, coastline: 19924 },
  { name: 'New Zealand', code: 'NZ', coastlineRank: 10, coastline: 15134 },
  { name: 'China', code: 'CN', coastlineRank: 11, coastline: 14500 },
  { name: 'Greece', code: 'GR', coastlineRank: 12, coastline: 13676 },
  { name: 'United Kingdom', code: 'GB', coastlineRank: 13, coastline: 12429 },
  { name: 'Mexico', code: 'MX', coastlineRank: 14, coastline: 9330 },
  { name: 'Italy', code: 'IT', coastlineRank: 15, coastline: 7600 },
  { name: 'Brazil', code: 'BR', coastlineRank: 16, coastline: 7491 },
  { name: 'Denmark', code: 'DK', coastlineRank: 17, coastline: 7314 },
  { name: 'Turkey', code: 'TR', coastlineRank: 18, coastline: 7200 },
  { name: 'India', code: 'IN', coastlineRank: 19, coastline: 7000 },
  { name: 'Chile', code: 'CL', coastlineRank: 20, coastline: 6435 },
  { name: 'Micronesia', code: 'FM', coastlineRank: 21, coastline: 6112 },
  { name: 'Croatia', code: 'HR', coastlineRank: 22, coastline: 5835 },
  { name: 'Solomon Islands', code: 'SB', coastlineRank: 23, coastline: 5313 },
  { name: 'Papua New Guinea', code: 'PG', coastlineRank: 24, coastline: 5152 },
  { name: 'Argentina', code: 'AR', coastlineRank: 25, coastline: 4989 },
  { name: 'Iceland', code: 'IS', coastlineRank: 26, coastline: 4970 },
  { name: 'Spain', code: 'ES', coastlineRank: 27, coastline: 4964 },
  { name: 'Madagascar', code: 'MG', coastlineRank: 28, coastline: 4828 },
  { name: 'Malaysia', code: 'MY', coastlineRank: 29, coastline: 4675 },
  { name: 'France', code: 'FR', coastlineRank: 30, coastline: 4668 },
  { name: 'Estonia', code: 'EE', coastlineRank: 31, coastline: 3794 },
  { name: 'Cuba', code: 'CU', coastlineRank: 32, coastline: 3735 },
  { name: 'Bahamas', code: 'BS', coastlineRank: 33, coastline: 3542 },
  { name: 'Vietnam', code: 'VN', coastlineRank: 34, coastline: 3444 },
  { name: 'Thailand', code: 'TH', coastlineRank: 35, coastline: 3219 },
  { name: 'Sweden', code: 'SE', coastlineRank: 36, coastline: 3218 },
  { name: 'Colombia', code: 'CO', coastlineRank: 37, coastline: 3208 },
  { name: 'Somalia', code: 'SO', coastlineRank: 38, coastline: 3025 },
  { name: 'Venezuela', code: 'VE', coastlineRank: 39, coastline: 2800 },
  { name: 'South Africa', code: 'ZA', coastlineRank: 40, coastline: 2798 },
  { name: 'Ukraine', code: 'UA', coastlineRank: 41, coastline: 2782 },
  { name: 'Saudi Arabia', code: 'SA', coastlineRank: 42, coastline: 2640 },
  { name: 'Vanuatu', code: 'VU', coastlineRank: 43, coastline: 2528 },
  { name: 'North Korea', code: 'KP', coastlineRank: 44, coastline: 2495 },
  { name: 'Panama', code: 'PA', coastlineRank: 45, coastline: 2490 },
  { name: 'Mozambique', code: 'MZ', coastlineRank: 46, coastline: 2470 },
  { name: 'Egypt', code: 'EG', coastlineRank: 47, coastline: 2450 },
  { name: 'Iran', code: 'IR', coastlineRank: 48, coastline: 2440 },
  { name: 'Peru', code: 'PE', coastlineRank: 49, coastline: 2414 },
  { name: 'South Korea', code: 'KR', coastlineRank: 50, coastline: 2413 },
  { name: 'Germany', code: 'DE', coastlineRank: 51, coastline: 2389 },
  { name: 'Ecuador', code: 'EC', coastlineRank: 52, coastline: 2237 },
  { name: 'Eritrea', code: 'ER', coastlineRank: 53, coastline: 2234 },
  { name: 'Oman', code: 'OM', coastlineRank: 54, coastline: 2092 },
  { name: 'Myanmar', code: 'MM', coastlineRank: 55, coastline: 1930 },
  { name: 'Yemen', code: 'YE', coastlineRank: 56, coastline: 1906 },
  { name: 'Morocco', code: 'MA', coastlineRank: 57, coastline: 1835 },
  { name: 'Portugal', code: 'PT', coastlineRank: 58, coastline: 1793 },
  { name: 'Haiti', code: 'HT', coastlineRank: 59, coastline: 1771 },
  { name: 'Libya', code: 'LY', coastlineRank: 60, coastline: 1770 },
  { name: 'Angola', code: 'AO', coastlineRank: 61, coastline: 1600 },
  { name: 'Namibia', code: 'NA', coastlineRank: 62, coastline: 1572 },
  { name: 'Taiwan', code: 'TW', coastlineRank: 63, coastline: 1566 },
  { name: 'Palau', code: 'PW', coastlineRank: 64, coastline: 1519 },
  { name: 'Ireland', code: 'IE', coastlineRank: 65, coastline: 1448 },
  { name: 'Tanzania', code: 'TZ', coastlineRank: 66, coastline: 1424 },
  { name: 'Sri Lanka', code: 'LK', coastlineRank: 67, coastline: 1340 },
  { name: 'United Arab Emirates', code: 'AE', coastlineRank: 68, coastline: 1318 },
  { name: 'Costa Rica', code: 'CR', coastlineRank: 69, coastline: 1290 },
  { name: 'Dominican Republic', code: 'DO', coastlineRank: 70, coastline: 1288 },
  { name: 'Finland', code: 'FI', coastlineRank: 71, coastline: 1250 },
  { name: 'Tunisia', code: 'TN', coastlineRank: 72, coastline: 1148 },
  { name: 'Kiribati', code: 'KI', coastlineRank: 73, coastline: 1143 },
  { name: 'Fiji', code: 'FJ', coastlineRank: 74, coastline: 1129 },
  { name: 'Pakistan', code: 'PK', coastlineRank: 75, coastline: 1046 },
  { name: 'Jamaica', code: 'JM', coastlineRank: 76, coastline: 1022 },
  { name: 'Algeria', code: 'DZ', coastlineRank: 77, coastline: 998 },
  { name: 'Cape Verde', code: 'CV', coastlineRank: 78, coastline: 965 },
  { name: 'Nicaragua', code: 'NI', coastlineRank: 79, coastline: 910 },
  { name: 'Gabon', code: 'GA', coastlineRank: 80, coastline: 885 },
  { name: 'Nigeria', code: 'NG', coastlineRank: 81, coastline: 853 },
  { name: 'Sudan', code: 'SD', coastlineRank: 82, coastline: 853 },
  { name: 'Honduras', code: 'HN', coastlineRank: 83, coastline: 820 },
  { name: 'Hong Kong', code: 'HK', coastlineRank: 84, coastline: 733 },
  { name: 'Timor-Leste', code: 'TL', coastlineRank: 85, coastline: 706 },
  { name: 'Uruguay', code: 'UY', coastlineRank: 86, coastline: 660 },
  { name: 'Cyprus', code: 'CY', coastlineRank: 87, coastline: 648 },
  { name: 'Maldives', code: 'MV', coastlineRank: 88, coastline: 644 },
  { name: 'Bangladesh', code: 'BD', coastlineRank: 89, coastline: 580 },
  { name: 'Liberia', code: 'LR', coastlineRank: 90, coastline: 579 },
  { name: 'Qatar', code: 'QA', coastlineRank: 91, coastline: 563 },
  { name: 'Ghana', code: 'GH', coastlineRank: 92, coastline: 539 },
  { name: 'Kenya', code: 'KE', coastlineRank: 93, coastline: 536 },
  { name: 'Senegal', code: 'SN', coastlineRank: 94, coastline: 531 },
  { name: 'Ivory Coast', code: 'CI', coastlineRank: 95, coastline: 515 },
  { name: 'Kuwait', code: 'KW', coastlineRank: 96, coastline: 499 },
  { name: 'Latvia', code: 'LV', coastlineRank: 97, coastline: 498 },
  { name: 'Seychelles', code: 'SC', coastlineRank: 98, coastline: 491 },
  { name: 'Guyana', code: 'GY', coastlineRank: 99, coastline: 459 },
  { name: 'Netherlands', code: 'NL', coastlineRank: 100, coastline: 451 },
  { name: 'Cambodia', code: 'KH', coastlineRank: 101, coastline: 443 },
  { name: 'Poland', code: 'PL', coastlineRank: 102, coastline: 440 },
  { name: 'Tonga', code: 'TO', coastlineRank: 103, coastline: 419 },
  { name: 'Samoa', code: 'WS', coastlineRank: 104, coastline: 403 },
  { name: 'Cameroon', code: 'CM', coastlineRank: 105, coastline: 402 },
  { name: 'Sierra Leone', code: 'SL', coastlineRank: 106, coastline: 402 },
  { name: 'Guatemala', code: 'GT', coastlineRank: 107, coastline: 400 },
  { name: 'Belize', code: 'BZ', coastlineRank: 108, coastline: 386 },
  { name: 'Suriname', code: 'SR', coastlineRank: 109, coastline: 386 },
  { name: 'Marshall Islands', code: 'MH', coastlineRank: 110, coastline: 370 },
  { name: 'Albania', code: 'AL', coastlineRank: 111, coastline: 362 },
  { name: 'Trinidad and Tobago', code: 'TT', coastlineRank: 112, coastline: 362 },
  { name: 'Bulgaria', code: 'BG', coastlineRank: 113, coastline: 354 },
  { name: 'Guinea-Bissau', code: 'GW', coastlineRank: 114, coastline: 350 },
  { name: 'Comoros', code: 'KM', coastlineRank: 115, coastline: 340 },
  { name: 'Guinea', code: 'GN', coastlineRank: 116, coastline: 320 },
  { name: 'Djibouti', code: 'DJ', coastlineRank: 117, coastline: 314 },
  { name: 'Georgia', code: 'GE', coastlineRank: 118, coastline: 310 },
  { name: 'El Salvador', code: 'SV', coastlineRank: 119, coastline: 307 },
  { name: 'Equatorial Guinea', code: 'GQ', coastlineRank: 120, coastline: 296 },
  { name: 'Montenegro', code: 'ME', coastlineRank: 121, coastline: 293 },
  { name: 'Israel', code: 'IL', coastlineRank: 122, coastline: 273 },
  { name: 'Lebanon', code: 'LB', coastlineRank: 123, coastline: 225 },
  { name: 'Romania', code: 'RO', coastlineRank: 124, coastline: 225 },
  { name: 'Sao Tome and Principe', code: 'ST', coastlineRank: 125, coastline: 209 },
  { name: 'Malta', code: 'MT', coastlineRank: 126, coastline: 197 },
  { name: 'Singapore', code: 'SG', coastlineRank: 127, coastline: 193 },
  { name: 'Syria', code: 'SY', coastlineRank: 128, coastline: 193 },
  { name: 'Mauritius', code: 'MU', coastlineRank: 129, coastline: 177 },
  { name: 'Republic of the Congo', code: 'CG', coastlineRank: 130, coastline: 169 },
  { name: 'Bahrain', code: 'BH', coastlineRank: 131, coastline: 161 },
  { name: 'Brunei', code: 'BN', coastlineRank: 132, coastline: 161 },
  { name: 'Saint Lucia', code: 'LC', coastlineRank: 133, coastline: 158 },
  { name: 'Antigua and Barbuda', code: 'AG', coastlineRank: 134, coastline: 153 },
  { name: 'Dominica', code: 'DM', coastlineRank: 135, coastline: 148 },
  { name: 'Saint Kitts and Nevis', code: 'KN', coastlineRank: 136, coastline: 135 },
  { name: 'Benin', code: 'BJ', coastlineRank: 137, coastline: 121 },
  { name: 'Grenada', code: 'GD', coastlineRank: 138, coastline: 121 },
  { name: 'Barbados', code: 'BB', coastlineRank: 139, coastline: 97 },
  { name: 'Lithuania', code: 'LT', coastlineRank: 140, coastline: 90 },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', coastlineRank: 141, coastline: 84 },
  { name: 'Gambia', code: 'GM', coastlineRank: 142, coastline: 80 },
  { name: 'Belgium', code: 'BE', coastlineRank: 143, coastline: 67 },
  { name: 'Iraq', code: 'IQ', coastlineRank: 144, coastline: 58 },
  { name: 'Togo', code: 'TG', coastlineRank: 145, coastline: 56 },
  { name: 'Slovenia', code: 'SI', coastlineRank: 146, coastline: 47 },
  { name: 'Macau', code: 'MO', coastlineRank: 147, coastline: 41 },
  { name: 'Gaza Strip', code: 'PS', coastlineRank: 148, coastline: 40 },
  { name: 'DR Congo', code: 'CD', coastlineRank: 149, coastline: 37 },
  { name: 'Nauru', code: 'NR', coastlineRank: 150, coastline: 30 },
  { name: 'Jordan', code: 'JO', coastlineRank: 151, coastline: 26 },
  { name: 'Tuvalu', code: 'TV', coastlineRank: 152, coastline: 24 },
  { name: 'Bosnia and Herzegovina', code: 'BA', coastlineRank: 153, coastline: 20 },
  { name: 'Monaco', code: 'MC', coastlineRank: 154, coastline: 4 }
];