export const crimerateData = [
{ name: 'Venezuela', code: 'VE', crimerateRank: 1, crimerate: 81.2 },
{ name: 'Papua New Guinea', code: 'PG', crimerateRank: 2, crimerate: 79.7 },
{ name: 'Afghanistan', code: 'AF', crimerateRank: 3, crimerate: 78.3 },
{ name: 'Haiti', code: 'HT', crimerateRank: 4, crimerate: 77.9 },
{ name: 'South Africa', code: 'ZA', crimerateRank: 5, crimerate: 75.4 },
{ name: 'Honduras', code: 'HN', crimerateRank: 6, crimerate: 73.4 },
{ name: 'Trinidad and Tobago', code: 'TT', crimerateRank: 7, crimerate: 70.8 },
{ name: 'Syria', code: 'SY', crimerateRank: 8, crimerate: 69.1 },
{ name: 'Yemen', code: 'YE', crimerateRank: 9, crimerate: 68.6 },
{ name: 'Jamaica', code: 'JM', crimerateRank: 10, crimerate: 68.1 },
{ name: 'Peru', code: 'PE', crimerateRank: 11, crimerate: 67.8 },
{ name: 'Guyana', code: 'GY', crimerateRank: 12, crimerate: 67.3 },
{ name: 'Angola', code: 'AO', crimerateRank: 13, crimerate: 66.5 },
{ name: 'Nigeria', code: 'NG', crimerateRank: 14, crimerate: 66.2 },
{ name: 'Brazil', code: 'BR', crimerateRank: 15, crimerate: 65.6 },
{ name: 'Somalia', code: 'SO', crimerateRank: 16, crimerate: 65.2 },
{ name: 'Bolivia', code: 'BO', crimerateRank: 17, crimerate: 64.6 },
{ name: 'Argentina', code: 'AR', crimerateRank: 18, crimerate: 64.2 },
{ name: 'Namibia', code: 'NA', crimerateRank: 19, crimerate: 63.9 },
{ name: 'Mozambique', code: 'MZ', crimerateRank: 20, crimerate: 63.7 },
{ name: 'Cameroon', code: 'CM', crimerateRank: 21, crimerate: 63.5 },
{ name: 'Ecuador', code: 'EC', crimerateRank: 22, crimerate: 62.1 },
{ name: 'Puerto Rico', code: 'PR', crimerateRank: 23, crimerate: 61.7 },
{ name: 'Bangladesh', code: 'BD', crimerateRank: 24, crimerate: 61.5 },
{ name: 'El Salvador', code: 'SV', crimerateRank: 25, crimerate: 61.3 },
{ name: 'Colombia', code: 'CO', crimerateRank: 26, crimerate: 61.2 },
{ name: 'Zimbabwe', code: 'ZW', crimerateRank: 27, crimerate: 60.9 },
{ name: 'Dominican Republic', code: 'DO', crimerateRank: 28, crimerate: 60.5 },
{ name: 'Libya', code: 'LY', crimerateRank: 29, crimerate: 60.4 },
{ name: 'Guatemala', code: 'GT', crimerateRank: 30, crimerate: 59.5 },
{ name: 'Chile', code: 'CL', crimerateRank: 31, crimerate: 59.3 },
{ name: 'Fiji', code: 'FJ', crimerateRank: 32, crimerate: 57.3 },
{ name: 'Ivory Coast', code: 'CI', crimerateRank: 33, crimerate: 57.1 },
{ name: 'Bahamas', code: 'BS', crimerateRank: 34, crimerate: 56.5 },
{ name: 'Kenya', code: 'KE', crimerateRank: 35, crimerate: 56.4 },
{ name: 'France', code: 'FR', crimerateRank: 36, crimerate: 55.3 },
{ name: 'Uganda', code: 'UG', crimerateRank: 37, crimerate: 55 },
{ name: 'Maldives', code: 'MV', crimerateRank: 38, crimerate: 55 },
{ name: 'Tanzania', code: 'TZ', crimerateRank: 39, crimerate: 54.5 },
{ name: 'Kyrgyzstan', code: 'KG', crimerateRank: 40, crimerate: 54 },
{ name: 'Mexico', code: 'MX', crimerateRank: 41, crimerate: 53.8 },
{ name: 'Costa Rica', code: 'CR', crimerateRank: 42, crimerate: 53.7 },
{ name: 'Belize', code: 'BZ', crimerateRank: 43, crimerate: 53 },
{ name: 'Cambodia', code: 'KH', crimerateRank: 44, crimerate: 52.8 },
{ name: 'Mongolia', code: 'MN', crimerateRank: 45, crimerate: 52.4 },
{ name: 'Algeria', code: 'DZ', crimerateRank: 46, crimerate: 52.2 },
{ name: 'Nicaragua', code: 'NI', crimerateRank: 47, crimerate: 52.2 },
{ name: 'Uruguay', code: 'UY', crimerateRank: 48, crimerate: 52.2 },
{ name: 'Botswana', code: 'BW', crimerateRank: 49, crimerate: 52.2 },
{ name: 'North Korea', code: 'KP', crimerateRank: 50, crimerate: 51.7 },
{ name: 'Paraguay', code: 'PY', crimerateRank: 51, crimerate: 50.9 },
{ name: 'Ethiopia', code: 'ET', crimerateRank: 52, crimerate: 50.8 },
{ name: 'Belarus', code: 'BY', crimerateRank: 53, crimerate: 50.8 },
{ name: 'Malaysia', code: 'MY', crimerateRank: 54, crimerate: 50.7 },
{ name: 'Myanmar', code: 'MM', crimerateRank: 55, crimerate: 50.4 },
{ name: 'Iran', code: 'IR', crimerateRank: 56, crimerate: 49.5 },
{ name: 'United States', code: 'US', crimerateRank: 57, crimerate: 49.3 },
{ name: 'Belgium', code: 'BE', crimerateRank: 58, crimerate: 49.2 },
{ name: 'Sweden', code: 'SE', crimerateRank: 59, crimerate: 48.4 },
{ name: 'Mauritius', code: 'MU', crimerateRank: 60, crimerate: 47.8 },
{ name: 'New Zealand', code: 'NZ', crimerateRank: 61, crimerate: 47.7 },
{ name: 'United Kingdom', code: 'GB', crimerateRank: 62, crimerate: 47.4 },
{ name: 'Egypt', code: 'EG', crimerateRank: 63, crimerate: 47.3 },
{ name: 'Italy', code: 'IT', crimerateRank: 64, crimerate: 47.3 },
{ name: 'Australia', code: 'AU', crimerateRank: 65, crimerate: 47.1 },
{ name: 'Barbados', code: 'BB', crimerateRank: 66, crimerate: 47.1 },
{ name: 'Ukraine', code: 'UA', crimerateRank: 67, crimerate: 46.9 },
{ name: 'Greece', code: 'GR', crimerateRank: 68, crimerate: 46.7 },
{ name: 'Morocco', code: 'MA', crimerateRank: 69, crimerate: 46.5 },
{ name: 'Ireland', code: 'IE', crimerateRank: 70, crimerate: 46.5 },
{ name: 'Zambia', code: 'ZM', crimerateRank: 71, crimerate: 46.4 },
{ name: 'Lebanon', code: 'LB', crimerateRank: 72, crimerate: 46.4 },
{ name: 'Indonesia', code: 'ID', crimerateRank: 73, crimerate: 46.1 },
{ name: 'Kazakhstan', code: 'KZ', crimerateRank: 74, crimerate: 45.9 },
{ name: 'Albania', code: 'AL', crimerateRank: 75, crimerate: 45.6 },
{ name: 'Sudan', code: 'SD', crimerateRank: 76, crimerate: 45.4 },
{ name: 'Canada', code: 'CA', crimerateRank: 77, crimerate: 45.2 },
{ name: 'Moldova', code: 'MD', crimerateRank: 78, crimerate: 45.1 },
{ name: 'Iraq', code: 'IQ', crimerateRank: 79, crimerate: 44.7 },
{ name: 'Tunisia', code: 'TN', crimerateRank: 80, crimerate: 44.4 },
{ name: 'India', code: 'IN', crimerateRank: 81, crimerate: 44.3 },
{ name: 'Panama', code: 'PA', crimerateRank: 82, crimerate: 44.3 },
{ name: 'Ghana', code: 'GH', crimerateRank: 83, crimerate: 43.9 },
{ name: 'Pakistan', code: 'PK', crimerateRank: 84, crimerate: 43.2 },
{ name: 'Philippines', code: 'PH', crimerateRank: 85, crimerate: 42.8 },
{ name: 'Vietnam', code: 'VN', crimerateRank: 86, crimerate: 42.2 },
{ name: 'Sri Lanka', code: 'LK', crimerateRank: 87, crimerate: 42.1 },
{ name: 'Palestine', code: 'PS', crimerateRank: 88, crimerate: 42.1 },
{ name: 'Malta', code: 'MT', crimerateRank: 89, crimerate: 41.2 },
{ name: 'North Macedonia', code: 'MK', crimerateRank: 90, crimerate: 41 },
{ name: 'Turkey', code: 'TR', crimerateRank: 91, crimerate: 40.9 },
{ name: 'Jordan', code: 'JO', crimerateRank: 92, crimerate: 40.4 },
{ name: 'Russia', code: 'RU', crimerateRank: 93, crimerate: 39.1 },
{ name: 'Germany', code: 'DE', crimerateRank: 94, crimerate: 38.9 },
{ name: 'Serbia', code: 'RS', crimerateRank: 95, crimerate: 38.3 },
{ name: 'Montenegro', code: 'ME', crimerateRank: 96, crimerate: 38 },
{ name: 'Thailand', code: 'TH', crimerateRank: 97, crimerate: 37.9 },
{ name: 'Nepal', code: 'NP', crimerateRank: 98, crimerate: 37.7 },
{ name: 'Latvia', code: 'LV', crimerateRank: 99, crimerate: 37.4 },
{ name: 'Bulgaria', code: 'BG', crimerateRank: 100, crimerate: 37.1 },
{ name: 'Spain', code: 'ES', crimerateRank: 101, crimerate: 36.2 },
{ name: 'Luxembourg', code: 'LU', crimerateRank: 102, crimerate: 34.4 },
{ name: 'Romania', code: 'RO', crimerateRank: 103, crimerate: 33.7 },
{ name: 'Hungary', code: 'HU', crimerateRank: 104, crimerate: 33.7 },
{ name: 'Cuba', code: 'CU', crimerateRank: 105, crimerate: 33.4 },
{ name: 'Kuwait', code: 'KW', crimerateRank: 106, crimerate: 32.8 },
{ name: 'Lithuania', code: 'LT', crimerateRank: 107, crimerate: 32.8 },
{ name: 'Norway', code: 'NO', crimerateRank: 108, crimerate: 32.6 },
{ name: 'Israel', code: 'IL', crimerateRank: 109, crimerate: 32.4 },
{ name: 'Cyprus', code: 'CY', crimerateRank: 110, crimerate: 32.4 },
{ name: 'Azerbaijan', code: 'AZ', crimerateRank: 111, crimerate: 31.6 },
{ name: 'Portugal', code: 'PT', crimerateRank: 112, crimerate: 31.2 },
{ name: 'Slovakia', code: 'SK', crimerateRank: 113, crimerate: 31.1 },
{ name: 'Poland', code: 'PL', crimerateRank: 114, crimerate: 30.7 },
{ name: 'Uzbekistan', code: 'UZ', crimerateRank: 115, crimerate: 30.5 },
{ name: 'Brunei', code: 'BN', crimerateRank: 116, crimerate: 29.5 },
{ name: 'Austria', code: 'AT', crimerateRank: 117, crimerate: 29.3 },
{ name: 'Saudi Arabia', code: 'SA', crimerateRank: 118, crimerate: 26.9 },
{ name: 'Rwanda', code: 'RW', crimerateRank: 119, crimerate: 26.8 },
{ name: 'Netherlands', code: 'NL', crimerateRank: 120, crimerate: 26.3 },
{ name: 'Denmark', code: 'DK', crimerateRank: 121, crimerate: 26.3 },
{ name: 'Finland', code: 'FI', crimerateRank: 122, crimerate: 26.3 },
{ name: 'Georgia', code: 'GE', crimerateRank: 123, crimerate: 26.1 },
{ name: 'Croatia', code: 'HR', crimerateRank: 124, crimerate: 26 },
{ name: 'Iceland', code: 'IS', crimerateRank: 125, crimerate: 25.4 },
{ name: 'Switzerland', code: 'CH', crimerateRank: 126, crimerate: 25.3 },
{ name: 'China', code: 'CN', crimerateRank: 127, crimerate: 24.9 },
{ name: 'South Korea', code: 'KR', crimerateRank: 128, crimerate: 24.9 },
{ name: 'Slovenia', code: 'SI', crimerateRank: 129, crimerate: 24.2 },
{ name: 'Bahrain', code: 'BH', crimerateRank: 130, crimerate: 23.9 },
{ name: 'Estonia', code: 'EE', crimerateRank: 131, crimerate: 23.8 },
{ name: 'Monaco', code: 'MC', crimerateRank: 132, crimerate: 23.6 },
{ name: 'Singapore', code: 'SG', crimerateRank: 133, crimerate: 23.5 },
{ name: 'Japan', code: 'JP', crimerateRank: 134, crimerate: 22.6 },
{ name: 'Armenia', code: 'AM', crimerateRank: 135, crimerate: 22.4 },
{ name: 'Oman', code: 'OM', crimerateRank: 136, crimerate: 19 },
{ name: 'Taiwan', code: 'TW', crimerateRank: 137, crimerate: 16.7 },
{ name: 'Qatar', code: 'QA', crimerateRank: 138, crimerate: 16 },
{ name: 'United Arab Emirates', code: 'AE', crimerateRank: 139, crimerate: 15.6 },
{ name: 'Andorra', code: 'AD', crimerateRank: 140, crimerate: 12.9 },
];