export const crimerateData = [
{ name: 'Venezuela', code: 'venezuela', crimerateRank: 1, crimerate: 81.2 },
{ name: 'Papua New Guinea', code: 'papua-new-guinea', crimerateRank: 2, crimerate: 79.7 },
{ name: 'Afghanistan', code: 'afghanistan', crimerateRank: 3, crimerate: 78.3 },
{ name: 'Haiti', code: 'haiti', crimerateRank: 4, crimerate: 77.9 },
{ name: 'South Africa', code: 'south-africa', crimerateRank: 5, crimerate: 75.4 },
{ name: 'Honduras', code: 'honduras', crimerateRank: 6, crimerate: 73.4 },
{ name: 'Trinidad and Tobago', code: 'trinidad-and-tobago', crimerateRank: 7, crimerate: 70.8 },
{ name: 'Syria', code: 'syria', crimerateRank: 8, crimerate: 69.1 },
{ name: 'Yemen', code: 'yemen', crimerateRank: 9, crimerate: 68.6 },
{ name: 'Jamaica', code: 'jamaica', crimerateRank: 10, crimerate: 68.1 },
{ name: 'Peru', code: 'peru', crimerateRank: 11, crimerate: 67.8 },
{ name: 'Guyana', code: 'guyana', crimerateRank: 12, crimerate: 67.3 },
{ name: 'Angola', code: 'angola', crimerateRank: 13, crimerate: 66.5 },
{ name: 'Nigeria', code: 'nigeria', crimerateRank: 14, crimerate: 66.2 },
{ name: 'Brazil', code: 'brazil', crimerateRank: 15, crimerate: 65.6 },
{ name: 'Somalia', code: 'somalia', crimerateRank: 16, crimerate: 65.2 },
{ name: 'Bolivia', code: 'bolivia', crimerateRank: 17, crimerate: 64.6 },
{ name: 'Argentina', code: 'argentina', crimerateRank: 18, crimerate: 64.2 },
{ name: 'Namibia', code: 'namibia', crimerateRank: 19, crimerate: 63.9 },
{ name: 'Mozambique', code: 'mozambique', crimerateRank: 20, crimerate: 63.7 },
{ name: 'Cameroon', code: 'cameroon', crimerateRank: 21, crimerate: 63.5 },
{ name: 'Ecuador', code: 'ecuador', crimerateRank: 22, crimerate: 62.1 },
{ name: 'Puerto Rico', code: 'puerto-rico', crimerateRank: 23, crimerate: 61.7 },
{ name: 'Bangladesh', code: 'bangladesh', crimerateRank: 24, crimerate: 61.5 },
{ name: 'El Salvador', code: 'el-salvador', crimerateRank: 25, crimerate: 61.3 },
{ name: 'Colombia', code: 'colombia', crimerateRank: 26, crimerate: 61.2 },
{ name: 'Zimbabwe', code: 'zimbabwe', crimerateRank: 27, crimerate: 60.9 },
{ name: 'Dominican Republic', code: 'dominican-republic', crimerateRank: 28, crimerate: 60.5 },
{ name: 'Libya', code: 'libya', crimerateRank: 29, crimerate: 60.4 },
{ name: 'Guatemala', code: 'guatemala', crimerateRank: 30, crimerate: 59.5 },
{ name: 'Chile', code: 'chile', crimerateRank: 31, crimerate: 59.3 },
{ name: 'Fiji', code: 'fiji', crimerateRank: 32, crimerate: 57.3 },
{ name: 'Ivory Coast', code: 'ivory-coast', crimerateRank: 33, crimerate: 57.1 },
{ name: 'Bahamas', code: 'bahamas', crimerateRank: 34, crimerate: 56.5 },
{ name: 'Kenya', code: 'kenya', crimerateRank: 35, crimerate: 56.4 },
{ name: 'France', code: 'france', crimerateRank: 36, crimerate: 55.3 },
{ name: 'Uganda', code: 'uganda', crimerateRank: 37, crimerate: 55 },
{ name: 'Maldives', code: 'maldives', crimerateRank: 38, crimerate: 55 },
{ name: 'Tanzania', code: 'tanzania', crimerateRank: 39, crimerate: 54.5 },
{ name: 'Kyrgyzstan', code: 'kyrgyzstan', crimerateRank: 40, crimerate: 54 },
{ name: 'Mexico', code: 'mexico', crimerateRank: 41, crimerate: 53.8 },
{ name: 'Costa Rica', code: 'costa-rica', crimerateRank: 42, crimerate: 53.7 },
{ name: 'Belize', code: 'belize', crimerateRank: 43, crimerate: 53 },
{ name: 'Cambodia', code: 'cambodia', crimerateRank: 44, crimerate: 52.8 },
{ name: 'Mongolia', code: 'mongolia', crimerateRank: 45, crimerate: 52.4 },
{ name: 'Algeria', code: 'algeria', crimerateRank: 46, crimerate: 52.2 },
{ name: 'Nicaragua', code: 'nicaragua', crimerateRank: 47, crimerate: 52.2 },
{ name: 'Uruguay', code: 'uruguay', crimerateRank: 48, crimerate: 52.2 },
{ name: 'Botswana', code: 'botswana', crimerateRank: 49, crimerate: 52.2 },
{ name: 'North Korea', code: 'north-korea', crimerateRank: 50, crimerate: 51.7 },
{ name: 'Paraguay', code: 'paraguay', crimerateRank: 51, crimerate: 50.9 },
{ name: 'Ethiopia', code: 'ethiopia', crimerateRank: 52, crimerate: 50.8 },
{ name: 'Belarus', code: 'belarus', crimerateRank: 53, crimerate: 50.8 },
{ name: 'Malaysia', code: 'malaysia', crimerateRank: 54, crimerate: 50.7 },
{ name: 'Myanmar', code: 'myanmar', crimerateRank: 55, crimerate: 50.4 },
{ name: 'Iran', code: 'iran', crimerateRank: 56, crimerate: 49.5 },
{ name: 'United States', code: 'united-states', crimerateRank: 57, crimerate: 49.3 },
{ name: 'Belgium', code: 'belgium', crimerateRank: 58, crimerate: 49.2 },
{ name: 'Sweden', code: 'sweden', crimerateRank: 59, crimerate: 48.4 },
{ name: 'Mauritius', code: 'mauritius', crimerateRank: 60, crimerate: 47.8 },
{ name: 'New Zealand', code: 'new-zealand', crimerateRank: 61, crimerate: 47.7 },
{ name: 'United Kingdom', code: 'united-kingdom', crimerateRank: 62, crimerate: 47.4 },
{ name: 'Egypt', code: 'egypt', crimerateRank: 63, crimerate: 47.3 },
{ name: 'Italy', code: 'italy', crimerateRank: 64, crimerate: 47.3 },
{ name: 'Australia', code: 'australia', crimerateRank: 65, crimerate: 47.1 },
{ name: 'Barbados', code: 'barbados', crimerateRank: 66, crimerate: 47.1 },
{ name: 'Ukraine', code: 'ukraine', crimerateRank: 67, crimerate: 46.9 },
{ name: 'Greece', code: 'greece', crimerateRank: 68, crimerate: 46.7 },
{ name: 'Morocco', code: 'morocco', crimerateRank: 69, crimerate: 46.5 },
{ name: 'Ireland', code: 'ireland', crimerateRank: 70, crimerate: 46.5 },
{ name: 'Zambia', code: 'zambia', crimerateRank: 71, crimerate: 46.4 },
{ name: 'Lebanon', code: 'lebanon', crimerateRank: 72, crimerate: 46.4 },
{ name: 'Indonesia', code: 'indonesia', crimerateRank: 73, crimerate: 46.1 },
{ name: 'Kazakhstan', code: 'kazakhstan', crimerateRank: 74, crimerate: 45.9 },
{ name: 'Albania', code: 'albania', crimerateRank: 75, crimerate: 45.6 },
{ name: 'Sudan', code: 'sudan', crimerateRank: 76, crimerate: 45.4 },
{ name: 'Canada', code: 'canada', crimerateRank: 77, crimerate: 45.2 },
{ name: 'Moldova', code: 'moldova', crimerateRank: 78, crimerate: 45.1 },
{ name: 'Iraq', code: 'iraq', crimerateRank: 79, crimerate: 44.7 },
{ name: 'Tunisia', code: 'tunisia', crimerateRank: 80, crimerate: 44.4 },
{ name: 'India', code: 'india', crimerateRank: 81, crimerate: 44.3 },
{ name: 'Panama', code: 'panama', crimerateRank: 82, crimerate: 44.3 },
{ name: 'Ghana', code: 'ghana', crimerateRank: 83, crimerate: 43.9 },
{ name: 'Pakistan', code: 'pakistan', crimerateRank: 84, crimerate: 43.2 },
{ name: 'Philippines', code: 'philippines', crimerateRank: 85, crimerate: 42.8 },
{ name: 'Vietnam', code: 'vietnam', crimerateRank: 86, crimerate: 42.2 },
{ name: 'Sri Lanka', code: 'sri-lanka', crimerateRank: 87, crimerate: 42.1 },
{ name: 'Palestine', code: 'palestine', crimerateRank: 88, crimerate: 42.1 },
{ name: 'Malta', code: 'malta', crimerateRank: 89, crimerate: 41.2 },
{ name: 'North Macedonia', code: 'north-macedonia', crimerateRank: 90, crimerate: 41 },
{ name: 'Turkey', code: 'turkey', crimerateRank: 91, crimerate: 40.9 },
{ name: 'Jordan', code: 'jordan', crimerateRank: 92, crimerate: 40.4 },
{ name: 'Russia', code: 'russia', crimerateRank: 93, crimerate: 39.1 },
{ name: 'Germany', code: 'germany', crimerateRank: 94, crimerate: 38.9 },
{ name: 'Serbia', code: 'serbia', crimerateRank: 95, crimerate: 38.3 },
{ name: 'Montenegro', code: 'montenegro', crimerateRank: 96, crimerate: 38 },
{ name: 'Thailand', code: 'thailand', crimerateRank: 97, crimerate: 37.9 },
{ name: 'Nepal', code: 'nepal', crimerateRank: 98, crimerate: 37.7 },
{ name: 'Latvia', code: 'latvia', crimerateRank: 99, crimerate: 37.4 },
{ name: 'Bulgaria', code: 'bulgaria', crimerateRank: 100, crimerate: 37.1 },
{ name: 'Spain', code: 'spain', crimerateRank: 101, crimerate: 36.2 },
{ name: 'Luxembourg', code: 'luxembourg', crimerateRank: 102, crimerate: 34.4 },
{ name: 'Romania', code: 'romania', crimerateRank: 103, crimerate: 33.7 },
{ name: 'Hungary', code: 'hungary', crimerateRank: 104, crimerate: 33.7 },
{ name: 'Cuba', code: 'cuba', crimerateRank: 105, crimerate: 33.4 },
{ name: 'Kuwait', code: 'kuwait', crimerateRank: 106, crimerate: 32.8 },
{ name: 'Lithuania', code: 'lithuania', crimerateRank: 107, crimerate: 32.8 },
{ name: 'Norway', code: 'norway', crimerateRank: 108, crimerate: 32.6 },
{ name: 'Israel', code: 'israel', crimerateRank: 109, crimerate: 32.4 },
{ name: 'Cyprus', code: 'cyprus', crimerateRank: 110, crimerate: 32.4 },
{ name: 'Azerbaijan', code: 'azerbaijan', crimerateRank: 111, crimerate: 31.6 },
{ name: 'Portugal', code: 'portugal', crimerateRank: 112, crimerate: 31.2 },
{ name: 'Slovakia', code: 'slovakia', crimerateRank: 113, crimerate: 31.1 },
{ name: 'Poland', code: 'poland', crimerateRank: 114, crimerate: 30.7 },
{ name: 'Uzbekistan', code: 'uzbekistan', crimerateRank: 115, crimerate: 30.5 },
{ name: 'Brunei', code: 'brunei', crimerateRank: 116, crimerate: 29.5 },
{ name: 'Austria', code: 'austria', crimerateRank: 117, crimerate: 29.3 },
{ name: 'Saudi Arabia', code: 'saudi-arabia', crimerateRank: 118, crimerate: 26.9 },
{ name: 'Rwanda', code: 'rwanda', crimerateRank: 119, crimerate: 26.8 },
{ name: 'Netherlands', code: 'netherlands', crimerateRank: 120, crimerate: 26.3 },
{ name: 'Denmark', code: 'denmark', crimerateRank: 121, crimerate: 26.3 },
{ name: 'Finland', code: 'finland', crimerateRank: 122, crimerate: 26.3 },
{ name: 'Georgia', code: 'georgia', crimerateRank: 123, crimerate: 26.1 },
{ name: 'Croatia', code: 'croatia', crimerateRank: 124, crimerate: 26 },
{ name: 'Iceland', code: 'iceland', crimerateRank: 125, crimerate: 25.4 },
{ name: 'Switzerland', code: 'switzerland', crimerateRank: 126, crimerate: 25.3 },
{ name: 'China', code: 'china', crimerateRank: 127, crimerate: 24.9 },
{ name: 'South Korea', code: 'south-korea', crimerateRank: 128, crimerate: 24.9 },
{ name: 'Slovenia', code: 'slovenia', crimerateRank: 129, crimerate: 24.2 },
{ name: 'Bahrain', code: 'bahrain', crimerateRank: 130, crimerate: 23.9 },
{ name: 'Estonia', code: 'estonia', crimerateRank: 131, crimerate: 23.8 },
{ name: 'Monaco', code: 'monaco', crimerateRank: 132, crimerate: 23.6 },
{ name: 'Singapore', code: 'singapore', crimerateRank: 133, crimerate: 23.5 },
{ name: 'Japan', code: 'japan', crimerateRank: 134, crimerate: 22.6 },
{ name: 'Armenia', code: 'armenia', crimerateRank: 135, crimerate: 22.4 },
{ name: 'Oman', code: 'oman', crimerateRank: 136, crimerate: 19 },
{ name: 'Taiwan', code: 'taiwan', crimerateRank: 137, crimerate: 16.7 },
{ name: 'Qatar', code: 'qatar', crimerateRank: 138, crimerate: 16 },
{ name: 'United Arab Emirates', code: 'united-arab-emirates', crimerateRank: 139, crimerate: 15.6 },
{ name: 'Andorra', code: 'andorra', crimerateRank: 140, crimerate: 12.9 },
];