export const cuisineData = [
  { name: 'Greece', code: 'GR', cuisineRank: 1, cuisineScore: 4.60, cuisine: 4.60 },
  { name: 'Italy', code: 'IT', cuisineRank: 2, cuisineScore: 4.59, cuisine: 4.59 },
  { name: 'Mexico', code: 'MX', cuisineRank: 3, cuisineScore: 4.52, cuisine: 4.52 },
  { name: 'Portugal', code: 'PT', cuisineRank: 4, cuisineScore: 4.50, cuisine: 4.50 },
  { name: 'Turkey', code: 'TR', cuisineRank: 5, cuisineScore: 4.48, cuisine: 4.48 },
  { name: 'France', code: 'FR', cuisineRank: 6, cuisineScore: 4.45, cuisine: 4.45 },
  { name: 'United States', code: 'US', cuisineRank: 7, cuisineScore: 4.42, cuisine: 4.42 },
  { name: 'Vietnam', code: 'VN', cuisineRank: 8, cuisineScore: 4.34, cuisine: 4.34 },
  { name: 'Hungary', code: 'HU', cuisineRank: 9, cuisineScore: 4.31, cuisine: 4.31 },
  { name: 'South Korea', code: 'KR', cuisineRank: 10, cuisineScore: 4.29, cuisine: 4.29 },
  { name: 'Lebanon', code: 'LB', cuisineRank: 11, cuisineScore: 4.28, cuisine: 4.28 },
  { name: 'Thailand', code: 'TH', cuisineRank: 12, cuisineScore: 4.26, cuisine: 4.26 },
  { name: 'Russia', code: 'RU', cuisineRank: 13, cuisineScore: 4.22, cuisine: 4.22 },
  { name: 'South Africa', code: 'ZA', cuisineRank: 14, cuisineScore: 4.21, cuisine: 4.21 },
  { name: 'Morocco', code: 'MA', cuisineRank: 15, cuisineScore: 4.20, cuisine: 4.20 },
  { name: 'England', code: 'GB-ENG', cuisineRank: 16, cuisineScore: 4.15, cuisine: 4.15 },
  { name: 'Australia', code: 'AU', cuisineRank: 17, cuisineScore: 4.09, cuisine: 4.09 },
  { name: 'Pakistan', code: 'PK', cuisineRank: 18, cuisineScore: 4.05, cuisine: 4.05 },
  { name: 'Denmark', code: 'DK', cuisineRank: 19, cuisineScore: 4.04, cuisine: 4.04 },
  { name: 'Ecuador', code: 'EC', cuisineRank: 20, cuisineScore: 3.99, cuisine: 3.99 },
  { name: 'Scotland', code: 'GB-SCT', cuisineRank: 21, cuisineScore: 3.98, cuisine: 3.98 },
  { name: 'Malta', code: 'MT', cuisineRank: 22, cuisineScore: 3.95, cuisine: 3.95 },
  { name: 'Bahamas', code: 'BS', cuisineRank: 23, cuisineScore: 3.94, cuisine: 3.94 },
  { name: 'Jamaica', code: 'JM', cuisineRank: 24, cuisineScore: 3.93, cuisine: 3.93 },
  { name: 'Dominican Republic', code: 'DO', cuisineRank: 25, cuisineScore: 3.91, cuisine: 3.91 },
  { name: 'Kazakhstan', code: 'KZ', cuisineRank: 26, cuisineScore: 3.90, cuisine: 3.90 },
  { name: 'Qatar', code: 'QA', cuisineRank: 27, cuisineScore: 3.89, cuisine: 3.89 },
  { name: 'Nigeria', code: 'NG', cuisineRank: 28, cuisineScore: 3.88, cuisine: 3.88 },
  { name: 'Nicaragua', code: 'NI', cuisineRank: 29, cuisineScore: 3.86, cuisine: 3.86 },
];