export const cuisineData = [
  { name: 'Greece', code: 'greece', cuisineRank: 1, cuisineScore: 4.60 },
  { name: 'Italy', code: 'italy', cuisineRank: 2, cuisineScore: 4.59 },
  { name: 'Mexico', code: 'mexico', cuisineRank: 3, cuisineScore: 4.52 },
  { name: 'Portugal', code: 'portugal', cuisineRank: 4, cuisineScore: 4.50 },
  { name: 'Turkey', code: 'turkey', cuisineRank: 5, cuisineScore: 4.48 },
  { name: 'France', code: 'france', cuisineRank: 6, cuisineScore: 4.45 },
  { name: 'United States', code: 'united-states', cuisineRank: 7, cuisineScore: 4.42 },
  { name: 'Vietnam', code: 'vietnam', cuisineRank: 8, cuisineScore: 4.34 },
  { name: 'Hungary', code: 'hungary', cuisineRank: 9, cuisineScore: 4.31 },
  { name: 'South Korea', code: 'south-korea', cuisineRank: 10, cuisineScore: 4.29 },
  { name: 'Lebanon', code: 'lebanon', cuisineRank: 11, cuisineScore: 4.28 },
  { name: 'Thailand', code: 'thailand', cuisineRank: 12, cuisineScore: 4.26 },
  { name: 'Russia', code: 'russia', cuisineRank: 13, cuisineScore: 4.22 },
  { name: 'South Africa', code: 'south-africa', cuisineRank: 14, cuisineScore: 4.21 },
  { name: 'Morocco', code: 'morocco', cuisineRank: 15, cuisineScore: 4.20 },
  { name: 'England', code: 'england', cuisineRank: 16, cuisineScore: 4.15 },
  { name: 'Australia', code: 'australia', cuisineRank: 17, cuisineScore: 4.09 },
  { name: 'Pakistan', code: 'pakistan', cuisineRank: 18, cuisineScore: 4.05 },
  { name: 'Denmark', code: 'denmark', cuisineRank: 19, cuisineScore: 4.04 },
  { name: 'Ecuador', code: 'ecuador', cuisineRank: 20, cuisineScore: 3.99 },
  { name: 'Scotland', code: 'scotland', cuisineRank: 21, cuisineScore: 3.98 },
  { name: 'Malta', code: 'malta', cuisineRank: 22, cuisineScore: 3.95 },
  { name: 'Bahamas', code: 'bahamas', cuisineRank: 23, cuisineScore: 3.94 },
  { name: 'Jamaica', code: 'jamaica', cuisineRank: 24, cuisineScore: 3.93 },
  { name: 'Dominican Republic', code: 'dominican-republic', cuisineRank: 25, cuisineScore: 3.91 },
  { name: 'Kazakhstan', code: 'kazakhstan', cuisineRank: 26, cuisineScore: 3.90 },
  { name: 'Qatar', code: 'qatar', cuisineRank: 27, cuisineScore: 3.89 },
  { name: 'Nigeria', code: 'nigeria', cuisineRank: 28, cuisineScore: 3.88 },
  { name: 'Nicaragua', code: 'nicaragua', cuisineRank: 29, cuisineScore: 3.86 },
];