export const densityData = [
  { name: 'Monaco', code: 'MC', densityRank: 1, density: 19044 },
  { name: 'Singapore', code: 'SG', densityRank: 2, density: 8225 },
  { name: 'Bahrain', code: 'BH', densityRank: 3, density: 2134 },
  { name: 'Maldives', code: 'MV', densityRank: 4, density: 1772 },
  { name: 'Malta', code: 'MT', densityRank: 5, density: 1716 },
  { name: 'Bangladesh', code: 'BD', densityRank: 6, density: 1366 },
  { name: 'Vatican City', code: 'VA', densityRank: 7, density: 1150 },
  { name: 'Palestine', code: 'PS', densityRank: 8, density: 946 },
  { name: 'Barbados', code: 'BB', densityRank: 9, density: 657 },
  { name: 'Taiwan', code: 'TW', densityRank: 10, density: 636 },
  { name: 'Mauritius', code: 'MU', densityRank: 11, density: 623 },
  { name: 'Nauru', code: 'NR', densityRank: 12, density: 605 },
  { name: 'Rwanda', code: 'RW', densityRank: 13, density: 604 },
  { name: 'Lebanon', code: 'LB', densityRank: 14, density: 576 },
  { name: 'Burundi', code: 'BI', densityRank: 15, density: 574 },
  { name: 'San Marino', code: 'SM', densityRank: 16, density: 560 },
  { name: 'Netherlands', code: 'NL', densityRank: 17, density: 548 },
  { name: 'South Korea', code: 'KR', densityRank: 18, density: 529 },
  { name: 'India', code: 'IN', densityRank: 19, density: 497 },
  { name: 'Comoros', code: 'KM', densityRank: 20, density: 483 },
  { name: 'Israel', code: 'IL', densityRank: 21, density: 446 },
  { name: 'Haiti', code: 'HT', densityRank: 22, density: 437 },
  { name: 'Philippines', code: 'PH', densityRank: 23, density: 395 },
  { name: 'Belgium', code: 'BE', densityRank: 24, density: 389 },
  { name: 'Sri Lanka', code: 'LK', densityRank: 25, density: 377 },
  { name: 'Puerto Rico', code: 'PR', densityRank: 26, density: 363 },
  { name: 'Grenada', code: 'GD', densityRank: 27, density: 345 },
  { name: 'Japan', code: 'JP', densityRank: 28, density: 336 },
  { name: 'Vietnam', code: 'VN', densityRank: 29, density: 326 },
  { name: 'Tuvalu', code: 'TV', densityRank: 30, density: 312 },
  { name: 'El Salvador', code: 'SV', densityRank: 31, density: 308 },
  { name: 'Saint Lucia', code: 'LC', densityRank: 32, density: 296 },
  { name: 'Trinidad and Tobago', code: 'TT', densityRank: 33, density: 295 },
  { name: 'Seychelles', code: 'SC', densityRank: 34, density: 293 },
  { name: 'United Kingdom', code: 'GB', densityRank: 35, density: 289 },
  { name: 'Kuwait', code: 'KW', densityRank: 36, density: 286 },
  { name: 'Gambia', code: 'GM', densityRank: 37, density: 285 },
  { name: 'Qatar', code: 'QA', densityRank: 38, density: 276 },
  { name: 'Luxembourg', code: 'LU', densityRank: 39, density: 267 },
  { name: 'Nigeria', code: 'NG', densityRank: 40, density: 266 },
  { name: 'Uganda', code: 'UG', densityRank: 41, density: 263 },
  { name: 'Jamaica', code: 'JM', densityRank: 42, density: 262 },
  { name: 'Sao Tome and Principe', code: 'ST', densityRank: 43, density: 255 },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', densityRank: 44, density: 254 },
  { name: 'Liechtenstein', code: 'LI', densityRank: 45, density: 252 },
  { name: 'Malawi', code: 'MW', densityRank: 46, density: 242 },
  { name: 'Dominican Republic', code: 'DO', densityRank: 47, density: 240 },
  { name: 'Germany', code: 'DE', densityRank: 48, density: 239 },
  { name: 'Switzerland', code: 'CH', densityRank: 49, density: 228 },
  { name: 'North Korea', code: 'KP', densityRank: 50, density: 221 },
  { name: 'Antigua and Barbuda', code: 'AG', densityRank: 51, density: 215 },
  { name: 'Nepal', code: 'NP', densityRank: 52, density: 207 },
  { name: 'Italy', code: 'IT', densityRank: 53, density: 199 },
  { name: 'Marshall Islands', code: 'MH', densityRank: 54, density: 195 },
  { name: 'Togo', code: 'TG', densityRank: 55, density: 183 },
  { name: 'Saint Kitts and Nevis', code: 'KN', densityRank: 56, density: 181 },
  { name: 'Andorra', code: 'AD', densityRank: 57, density: 178 },
  { name: 'Guatemala', code: 'GT', densityRank: 58, density: 177 },
  { name: 'Kiribati', code: 'KI', densityRank: 59, density: 171 },
  { name: 'United Arab Emirates', code: 'AE', densityRank: 60, density: 163 },
  { name: 'Ghana', code: 'GH', densityRank: 61, density: 157 },
  { name: 'Indonesia', code: 'ID', densityRank: 62, density: 153 },
  { name: 'Denmark', code: 'DK', densityRank: 63, density: 151 },
  { name: 'China', code: 'CN', densityRank: 64, density: 150 },
  { name: 'Syria', code: 'SY', densityRank: 65, density: 144 },
  { name: 'Tonga', code: 'TO', densityRank: 66, density: 143 },
  { name: 'Thailand', code: 'TH', densityRank: 67, density: 140 },
  { name: 'Czechia', code: 'CZ', densityRank: 68, density: 136 },
  { name: 'Benin', code: 'BJ', densityRank: 69, density: 135 },
  { name: 'Cape Verde', code: 'CV', densityRank: 70, density: 131 },
  { name: 'Azerbaijan', code: 'AZ', densityRank: 71, density: 127 },
  { name: 'Sierra Leone', code: 'SL', densityRank: 72, density: 125 },
  { name: 'Poland', code: 'PL', densityRank: 73, density: 124 },
  { name: 'Ethiopia', code: 'ET', densityRank: 74, density: 123 },
  { name: 'France', code: 'FR', densityRank: 75, density: 122 },
  { name: 'Egypt', code: 'EG', densityRank: 76, density: 121 },
  { name: 'Portugal', code: 'PT', densityRank: 77, density: 113 },
  { name: 'Turkey', code: 'TR', densityRank: 78, density: 112 },
  { name: 'Slovakia', code: 'SK', densityRank: 79, density: 111 },
  { name: 'Austria', code: 'AT', densityRank: 80, density: 110 },
  { name: 'Ivory Coast', code: 'CI', densityRank: 81, density: 105 },
  { name: 'Kenya', code: 'KE', densityRank: 82, density: 103 },
  { name: 'Cambodia', code: 'KH', densityRank: 83, density: 102 },
  { name: 'Costa Rica', code: 'CR', densityRank: 84, density: 101 },
  { name: 'Albania', code: 'AL', densityRank: 85, density: 100 },
  { name: 'Timor-Leste', code: 'TL', densityRank: 86, density: 97 },
  { name: 'Spain', code: 'ES', densityRank: 87, density: 96 },
  { name: 'Moldova', code: 'MD', densityRank: 88, density: 90 },
  { name: 'Brunei', code: 'BN', densityRank: 89, density: 89 },
  { name: 'Dominica', code: 'DM', densityRank: 90, density: 87 },
  { name: 'Uzbekistan', code: 'UZ', densityRank: 91, density: 86 },
  { name: 'Myanmar', code: 'MM', densityRank: 92, density: 85 },
  { name: 'Tanzania', code: 'TZ', densityRank: 93, density: 82 },
  { name: 'Yemen', code: 'YE', densityRank: 94, density: 81 },
  { name: 'Tunisia', code: 'TN', densityRank: 95, density: 80 },
  { name: 'Samoa', code: 'WS', densityRank: 96, density: 79 },
  { name: 'Ireland', code: 'IE', densityRank: 97, density: 78 },
  { name: 'Greece', code: 'GR', densityRank: 98, density: 77 },
  { name: 'Serbia', code: 'RS', densityRank: 99, density: 76 },
  { name: 'Ecuador', code: 'EC', densityRank: 100, density: 74 },
  { name: 'North Macedonia', code: 'MK', densityRank: 101, density: 72 },
  { name: 'Equatorial Guinea', code: 'GQ', densityRank: 102, density: 71 },
  { name: 'Afghanistan', code: 'AF', densityRank: 103, density: 69 },
  { name: 'Mexico', code: 'MX', densityRank: 104, density: 68 },
  { name: 'Cameroon', code: 'CM', densityRank: 105, density: 65 },
  { name: 'Guinea', code: 'GN', densityRank: 106, density: 63 },
  { name: 'Panama', code: 'PA', densityRank: 107, density: 62 },
  { name: 'Bulgaria', code: 'BG', densityRank: 108, density: 61 },
  { name: 'Nicaragua', code: 'NI', densityRank: 109, density: 59 },
  { name: 'Madagascar', code: 'MG', densityRank: 110, density: 58 },
  { name: 'Iran', code: 'IR', densityRank: 111, density: 57 },
  { name: 'Georgia', code: 'GE', densityRank: 112, density: 55 },
  { name: 'South Africa', code: 'ZA', densityRank: 113, density: 54 },
  { name: 'Djibouti', code: 'DJ', densityRank: 114, density: 52 },
  { name: 'DR Congo', code: 'CD', densityRank: 115, density: 51 },
  { name: 'Colombia', code: 'CO', densityRank: 116, density: 49 },
  { name: 'Mozambique', code: 'MZ', densityRank: 117, density: 47 },
  { name: 'Lithuania', code: 'LT', densityRank: 118, density: 45 },
  { name: 'Belarus', code: 'BY', densityRank: 119, density: 44 },
  { name: 'Bahamas', code: 'BS', densityRank: 120, density: 40 },
  { name: 'Kyrgyzstan', code: 'KG', densityRank: 121, density: 39 },
  { name: 'Palau', code: 'PW', densityRank: 122, density: 38 },
  { name: 'Laos', code: 'LA', densityRank: 123, density: 35 },
  { name: 'Venezuela', code: 'VE', densityRank: 124, density: 32 },
  { name: 'Estonia', code: 'EE', densityRank: 125, density: 31 },
  { name: 'Eritrea', code: 'ER', densityRank: 126, density: 30 },
  { name: 'Sudan', code: 'SD', densityRank: 127, density: 29 },
  { name: 'Vanuatu', code: 'VU', densityRank: 128, density: 28 },
  { name: 'Peru', code: 'PE', densityRank: 129, density: 27 },
  { name: 'Sweden', code: 'SE', densityRank: 130, density: 26 },
  { name: 'Papua New Guinea', code: 'PG', densityRank: 131, density: 24 },
  { name: 'Niger', code: 'NE', densityRank: 132, density: 23 },
  { name: 'Mali', code: 'ML', densityRank: 133, density: 21 },
  { name: 'Algeria', code: 'DZ', densityRank: 134, density: 20 },
  { name: 'Republic of the Congo', code: 'CG', densityRank: 135, density: 19 },
  { name: 'Finland', code: 'FI', densityRank: 136, density: 18 },
  { name: 'Chad', code: 'TD', densityRank: 137, density: 17 },
  { name: 'Turkmenistan', code: 'TM', densityRank: 138, density: 16 },
  { name: 'Bolivia', code: 'BO', densityRank: 139, density: 12 },
  { name: 'Gabon', code: 'GA', densityRank: 140, density: 10 },
  { name: 'Russia', code: 'RU', densityRank: 141, density: 9 },
  { name: 'Kazakhstan', code: 'KZ', densityRank: 142, density: 8 },
  { name: 'Botswana', code: 'BW', densityRank: 143, density: 5 },
  { name: 'Australia', code: 'AU', densityRank: 144, density: 4 },
  { name: 'Mongolia', code: 'MN', densityRank: 145, density: 2 },
  { name: 'Greenland', code: 'GL', densityRank: 146, density: 0 }
];