export const disasterRiskData = [
  { name: 'Philippines', code: 'PH', disasterRank: 1, disasterrisk: 46.91 },
  { name: 'Indonesia', code: 'ID', disasterRank: 2, disasterrisk: 41.13 },
  { name: 'India', code: 'IN', disasterRank: 3, disasterrisk: 40.96 },
  { name: 'Colombia', code: 'CO', disasterRank: 4, disasterrisk: 37.81 },
  { name: 'Mexico', code: 'MX', disasterRank: 5, disasterrisk: 35.93 },
  { name: 'Myanmar', code: 'MM', disasterRank: 6, disasterrisk: 35.85 },
  { name: 'Mozambique', code: 'MZ', disasterRank: 7, disasterrisk: 34.44 },
  { name: 'Russia', code: 'RU', disasterRank: 8, disasterrisk: 28.12 },
  { name: 'Bangladesh', code: 'BD', disasterRank: 9, disasterrisk: 27.73 },
  { name: 'Pakistan', code: 'PK', disasterRank: 10, disasterrisk: 27.02 },
  { name: 'Peru', code: 'PE', disasterRank: 11, disasterrisk: 27.01 },
  { name: 'Papua New Guinea', code: 'PG', disasterRank: 12, disasterrisk: 26.35 },
  { name: 'Madagascar', code: 'MG', disasterRank: 13, disasterrisk: 24.80 },
  { name: 'Somalia', code: 'SO', disasterRank: 14, disasterrisk: 24.64 },
  { name: 'Yemen', code: 'YE', disasterRank: 15, disasterrisk: 24.47 },
  { name: 'Vietnam', code: 'VN', disasterRank: 16, disasterrisk: 24.24 },
  { name: 'Venezuela', code: 'VE', disasterRank: 17, disasterrisk: 24.20 },
  { name: 'Ecuador', code: 'EC', disasterRank: 18, disasterrisk: 23.81 },
  { name: 'United States', code: 'US', disasterRank: 19, disasterrisk: 22.56 },
  { name: 'Nicaragua', code: 'NI', disasterRank: 20, disasterrisk: 21.94 },
  { name: 'Thailand', code: 'TH', disasterRank: 21, disasterrisk: 21.70 },
  { name: 'China', code: 'CN', disasterRank: 22, disasterrisk: 21.31 },
  { name: 'Australia', code: 'AU', disasterRank: 23, disasterrisk: 21.05 },
  { name: 'Japan', code: 'JP', disasterRank: 24, disasterrisk: 20.94 },
  { name: 'Canada', code: 'CA', disasterRank: 25, disasterrisk: 18.89 },
  { name: 'Egypt', code: 'EG', disasterRank: 26, disasterrisk: 18.78 },
  { name: 'Panama', code: 'PA', disasterRank: 27, disasterrisk: 18.19 },
  { name: 'Iran', code: 'IR', disasterRank: 28, disasterrisk: 17.47 },
  { name: 'Honduras', code: 'HN', disasterRank: 29, disasterrisk: 16.81 },
  { name: 'Tanzania', code: 'TZ', disasterRank: 30, disasterrisk: 15.98 },
  { name: 'El Salvador', code: 'SV', disasterRank: 31, disasterrisk: 14.94 },
  { name: 'Argentina', code: 'AR', disasterRank: 32, disasterrisk: 14.81 },
  { name: 'Solomon Islands', code: 'SB', disasterRank: 33, disasterrisk: 14.74 },
  { name: 'Malaysia', code: 'MY', disasterRank: 34, disasterrisk: 14.50 },
  { name: 'Turkey', code: 'TR', disasterRank: 35, disasterrisk: 14.48 },
  { name: 'New Zealand', code: 'NZ', disasterRank: 36, disasterrisk: 14.34 },
  { name: 'Libya', code: 'LY', disasterRank: 37, disasterrisk: 13.87 },
  { name: 'Kenya', code: 'KE', disasterRank: 38, disasterrisk: 13.79 },
  { name: 'Chile', code: 'CL', disasterRank: 39, disasterrisk: 13.74 },
  { name: 'Dominican Republic', code: 'DO', disasterRank: 40, disasterrisk: 13.33 },
  { name: 'Brazil', code: 'BR', disasterRank: 41, disasterrisk: 13.15 },
  { name: 'Syria', code: 'SY', disasterRank: 42, disasterrisk: 12.50 },
  { name: 'North Korea', code: 'KP', disasterRank: 43, disasterrisk: 12.38 },
  { name: 'Guatemala', code: 'GT', disasterRank: 44, disasterrisk: 11.76 },
  { name: 'Vanuatu', code: 'VU', disasterRank: 45, disasterrisk: 11.58 },
  { name: 'Cameroon', code: 'CM', disasterRank: 46, disasterrisk: 11.40 },
  { name: 'Costa Rica', code: 'CR', disasterRank: 47, disasterrisk: 11.17 },
  { name: 'Italy', code: 'IT', disasterRank: 48, disasterrisk: 11.11 },
  { name: 'Djibouti', code: 'DJ', disasterRank: 49, disasterrisk: 10.82 },
  { name: 'South Korea', code: 'KR', disasterRank: 50, disasterrisk: 10.59 },
  { name: 'Morocco', code: 'MA', disasterRank: 51, disasterrisk: 10.43 },
  { name: 'Angola', code: 'AO', disasterRank: 52, disasterrisk: 10.42 },
  { name: 'Sudan', code: 'SD', disasterRank: 53, disasterrisk: 10.30 },
  { name: 'Haiti', code: 'HT', disasterRank: 54, disasterrisk: 9.96 },
  { name: 'Tunisia', code: 'TN', disasterRank: 55, disasterrisk: 9.91 },
  { name: 'DR Congo', code: 'CD', disasterRank: 56, disasterrisk: 9.87 },
  { name: 'Spain', code: 'ES', disasterRank: 57, disasterrisk: 9.74 },
  { name: 'Algeria', code: 'DZ', disasterRank: 58, disasterrisk: 9.64 },
  { name: 'South Africa', code: 'ZA', disasterRank: 59, disasterrisk: 9.60 },
  { name: 'Saudi Arabia', code: 'SA', disasterRank: 60, disasterrisk: 9.34 },
  { name: 'Nigeria', code: 'NG', disasterRank: 61, disasterrisk: 9.33 },
  { name: 'Mauritania', code: 'MR', disasterRank: 62, disasterrisk: 9.32 },
  { name: 'Iraq', code: 'IQ', disasterRank: 63, disasterrisk: 9.24 },
  { name: 'Greece', code: 'GR', disasterRank: 64, disasterrisk: 8.61 },
  { name: 'Cambodia', code: 'KH', disasterRank: 65, disasterrisk: 8.15 },
  { name: 'Oman', code: 'OM', disasterRank: 66, disasterrisk: 8.06 },
  { name: 'Belize', code: 'BZ', disasterRank: 67, disasterrisk: 7.97 },
  { name: 'Cuba', code: 'CU', disasterRank: 68, disasterrisk: 7.80 },
  { name: 'Timor-Leste', code: 'TL', disasterRank: 69, disasterrisk: 7.55 },
  { name: 'France', code: 'FR', disasterRank: 70, disasterrisk: 7.54 },
  { name: 'Eritrea', code: 'ER', disasterRank: 71, disasterrisk: 7.47 },
  { name: 'Guyana', code: 'GY', disasterRank: 72, disasterrisk: 7.35 },
  { name: 'Suriname', code: 'SR', disasterRank: 73, disasterrisk: 6.76 },
  { name: 'Fiji', code: 'FJ', disasterRank: 74, disasterrisk: 6.70 },
  { name: 'Guinea', code: 'GN', disasterRank: 75, disasterrisk: 6.55 },
  { name: 'Albania', code: 'AL', disasterRank: 76, disasterrisk: 6.24 },
  { name: 'Sri Lanka', code: 'LK', disasterRank: 77, disasterrisk: 6.16 },
  { name: 'Sierra Leone', code: 'SL', disasterRank: 78, disasterrisk: 5.72 },
  { name: 'United Kingdom', code: 'GB', disasterRank: 79, disasterrisk: 5.70 },
  { name: 'Senegal', code: 'SN', disasterRank: 80, disasterrisk: 5.66 },
  { name: 'Republic of the Congo', code: 'CG', disasterRank: 81, disasterrisk: 5.49 },
  { name: 'Namibia', code: 'NA', disasterRank: 82, disasterrisk: 5.40 },
  { name: 'Belgium', code: 'BE', disasterRank: 83, disasterrisk: 5.10 },
  { name: 'Portugal', code: 'PT', disasterRank: 84, disasterrisk: 5.08 },
  { name: 'Uruguay', code: 'UY', disasterRank: 85, disasterrisk: 4.97 },
  { name: 'Gambia', code: 'GM', disasterRank: 86, disasterrisk: 4.89 },
  { name: 'Ethiopia', code: 'ET', disasterRank: 87, disasterrisk: 4.86 },
  { name: 'Bahamas', code: 'BS', disasterRank: 88, disasterrisk: 4.82 },
  { name: 'Croatia', code: 'HR', disasterRank: 89, disasterrisk: 4.78 },
  { name: 'Poland', code: 'PL', disasterRank: 90, disasterrisk: 4.74 },
  { name: 'United Arab Emirates', code: 'AE', disasterRank: 91, disasterrisk: 4.54 },
  { name: 'Micronesia', code: 'FM', disasterRank: 92, disasterrisk: 4.44 },
  { name: 'Ukraine', code: 'UA', disasterRank: 93, disasterrisk: 4.41 },
  { name: 'South Sudan', code: 'SS', disasterRank: 94, disasterrisk: 4.25 },
  { name: 'Afghanistan', code: 'AF', disasterRank: 95, disasterrisk: 4.12 },
  { name: 'Netherlands', code: 'NL', disasterRank: 96, disasterrisk: 4.11 },
  { name: 'Germany', code: 'DE', disasterRank: 97, disasterrisk: 4.10 },
  { name: 'Tonga', code: 'TO', disasterRank: 98, disasterrisk: 4.02 },
  { name: 'Lebanon', code: 'LB', disasterRank: 99, disasterrisk: 3.87 },
  { name: 'Israel', code: 'IL', disasterRank: 100, disasterrisk: 3.81 },
];
