export const chessGMData = [
  { name: 'Russia', code: 'RU', gmRank: 1, grandmasters: 256 },
  { name: 'United States', code: 'US', gmRank: 2, grandmasters: 101 },
  { name: 'Germany', code: 'DE', gmRank: 3, grandmasters: 96 },
  { name: 'Ukraine', code: 'UA', gmRank: 4, grandmasters: 93 },
  { name: 'India', code: 'IN', gmRank: 5, grandmasters: 92 },
  { name: 'Hungary', code: 'HU', gmRank: 6, grandmasters: 58 },
  { name: 'Spain', code: 'ES', gmRank: 7, grandmasters: 56 },
  { name: 'France', code: 'FR', gmRank: 8, grandmasters: 50 },
  { name: 'China', code: 'CN', gmRank: 9, grandmasters: 48 },
  { name: 'Poland', code: 'PL', gmRank: 10, grandmasters: 45 },
  { name: 'Armenia', code: 'AM', gmRank: 11, grandmasters: 44 },
  { name: 'Israel', code: 'IL', gmRank: 12, grandmasters: 43 },
  { name: 'Czechia', code: 'CZ', gmRank: 13, grandmasters: 36 },
  { name: 'Bulgaria', code: 'BG', gmRank: 14, grandmasters: 34 },
  { name: 'Croatia', code: 'HR', gmRank: 15, grandmasters: 32 },
  { name: 'Cuba', code: 'CU', gmRank: 16, grandmasters: 27 },
  { name: 'Azerbaijan', code: 'AZ', gmRank: 17, grandmasters: 26 },
  { name: 'Argentina', code: 'AR', gmRank: 18, grandmasters: 23 },
  { name: 'Romania', code: 'RO', gmRank: 19, grandmasters: 22 },
  { name: 'Belarus', code: 'BY', gmRank: 20, grandmasters: 18 },
  { name: 'Uzbekistan', code: 'UZ', gmRank: 21, grandmasters: 17 },
  { name: 'Italy', code: 'IT', gmRank: 22, grandmasters: 16 },
  { name: 'Kazakhstan', code: 'KZ', gmRank: 23, grandmasters: 15 },
  { name: 'Brazil', code: 'BR', gmRank: 24, grandmasters: 14 },
  { name: 'Denmark', code: 'DK', gmRank: 25, grandmasters: 13 },
  { name: 'Latvia', code: 'LV', gmRank: 26, grandmasters: 12 },
  { name: 'Switzerland', code: 'CH', gmRank: 27, grandmasters: 11 },
  { name: 'Australia', code: 'AU', gmRank: 28, grandmasters: 10 },
  { name: 'Austria', code: 'AT', gmRank: 29, grandmasters: 9 },
  { name: 'Bosnia and Herzegovina', code: 'BA', gmRank: 30, grandmasters: 8 },
  { name: 'Moldova', code: 'MD', gmRank: 31, grandmasters: 7 },
  { name: 'Chile', code: 'CL', gmRank: 32, grandmasters: 6 },
];
