export const happinessData = [
  { name: 'Finland', code: 'finland', happinessRank: 1, score: 7.736 },
  { name: 'Denmark', code: 'denmark', happinessRank: 2, score: 7.521 },
  { name: 'Iceland', code: 'iceland', happinessRank: 3, score: 7.515 },
  { name: 'Sweden', code: 'sweden', happinessRank: 4, score: 7.345 },
  { name: 'Netherlands', code: 'netherlands', happinessRank: 5, score: 7.306 },
  { name: 'Costa Rica', code: 'costa-rica', happinessRank: 6, score: 7.274 },
  { name: 'Norway', code: 'norway', happinessRank: 7, score: 7.262 },
  { name: 'Israel', code: 'israel', happinessRank: 8, score: 7.234 },
  { name: 'Luxembourg', code: 'luxembourg', happinessRank: 9, score: 7.122 },
  { name: 'Mexico', code: 'mexico', happinessRank: 10, score: 6.979 },
  { name: 'Australia', code: 'australia', happinessRank: 11, score: 6.974 },
  { name: 'New Zealand', code: 'new-zealand', happinessRank: 12, score: 6.952 },
  { name: 'Switzerland', code: 'switzerland', happinessRank: 13, score: 6.935 },
  { name: 'Belgium', code: 'belgium', happinessRank: 14, score: 6.910 },
  { name: 'Ireland', code: 'ireland', happinessRank: 15, score: 6.889 },
  { name: 'Lithuania', code: 'lithuania', happinessRank: 16, score: 6.829 },
  { name: 'Austria', code: 'austria', happinessRank: 17, score: 6.810 },
  { name: 'Canada', code: 'canada', happinessRank: 18, score: 6.803 },
  { name: 'Slovenia', code: 'slovenia', happinessRank: 19, score: 6.792 },
  { name: 'Czech Republic', code: 'czech-republic', happinessRank: 20, score: 6.775 },
  { name: 'United Arab Emirates', code: 'united-arab-emirates', happinessRank: 21, score: 6.759 },
  { name: 'Germany', code: 'germany', happinessRank: 22, score: 6.753 },
  { name: 'United Kingdom', code: 'united-kingdom', happinessRank: 23, score: 6.728 },
  { name: 'United States', code: 'united-states', happinessRank: 24, score: 6.724 },
  { name: 'Belize', code: 'belize', happinessRank: 25, score: 6.711 },
  { name: 'Poland', code: 'poland', happinessRank: 26, score: 6.673 },
  { name: 'Taiwan', code: 'taiwan', happinessRank: 27, score: 6.669 },
  { name: 'Uruguay', code: 'uruguay', happinessRank: 28, score: 6.661 },
  { name: 'Kosovo', code: 'kosovo', happinessRank: 29, score: 6.659 },
  { name: 'Kuwait', code: 'kuwait', happinessRank: 30, score: 6.629 },
];

