// js/categories/lifeexpectancy.js
// Ranking countries by life expectancy (total average, both sexes)

export const lifeexpectancyData = [
  { name: "Monaco", code: "MC", lifeExpectancy: 86.5, lifeExpectancyRank: 1 },
  { name: "San Marino", code: "SM", lifeExpectancy: 85.8, lifeExpectancyRank: 2 },
  { name: "Hong Kong", code: "HK", lifeExpectancy: 85.6, lifeExpectancyRank: 3 },
  { name: "Japan", code: "JP", lifeExpectancy: 84.8, lifeExpectancyRank: 4 },
  { name: "South Korea", code: "KR", lifeExpectancy: 84.4, lifeExpectancyRank: 5 },
  { name: "Andorra", code: "AD", lifeExpectancy: 84.2, lifeExpectancyRank: 6 },
  { name: "Switzerland", code: "CH", lifeExpectancy: 84.1, lifeExpectancyRank: 7 },
  { name: "Australia", code: "AU", lifeExpectancy: 84.1, lifeExpectancyRank: 8 },
  { name: "Italy", code: "IT", lifeExpectancy: 83.9, lifeExpectancyRank: 9 },
  { name: "Singapore", code: "SG", lifeExpectancy: 83.9, lifeExpectancyRank: 10 },
  { name: "Spain", code: "ES", lifeExpectancy: 83.8, lifeExpectancyRank: 11 },
  { name: "Liechtenstein", code: "LI", lifeExpectancy: 83.8, lifeExpectancyRank: 12 },
  { name: "Malta", code: "MT", lifeExpectancy: 83.5, lifeExpectancyRank: 13 },
  { name: "France", code: "FR", lifeExpectancy: 83.5, lifeExpectancyRank: 14 },
  { name: "Norway", code: "NO", lifeExpectancy: 83.5, lifeExpectancyRank: 15 },
  { name: "Sweden", code: "SE", lifeExpectancy: 83.4, lifeExpectancyRank: 16 },
  { name: "Macau", code: "MO", lifeExpectancy: 83.2, lifeExpectancyRank: 17 },
  { name: "Vatican City", code: "VA", lifeExpectancy: 83.1, lifeExpectancyRank: 18 },
  { name: "United Arab Emirates", code: "AE", lifeExpectancy: 83.1, lifeExpectancyRank: 19 },
  { name: "Iceland", code: "IS", lifeExpectancy: 83.0, lifeExpectancyRank: 20 },
  { name: "Israel", code: "IL", lifeExpectancy: 82.7, lifeExpectancyRank: 21 },
  { name: "Canada", code: "CA", lifeExpectancy: 82.7, lifeExpectancyRank: 22 },
  { name: "Ireland", code: "IE", lifeExpectancy: 82.6, lifeExpectancyRank: 23 },
  { name: "Portugal", code: "PT", lifeExpectancy: 82.5, lifeExpectancyRank: 24 },
  { name: "Qatar", code: "QA", lifeExpectancy: 82.5, lifeExpectancyRank: 25 },
  { name: "Luxembourg", code: "LU", lifeExpectancy: 82.4, lifeExpectancyRank: 26 },
  { name: "Netherlands", code: "NL", lifeExpectancy: 82.3, lifeExpectancyRank: 27 },
  { name: "Belgium", code: "BE", lifeExpectancy: 82.3, lifeExpectancyRank: 28 },
  { name: "New Zealand", code: "NZ", lifeExpectancy: 82.2, lifeExpectancyRank: 29 },
  { name: "Austria", code: "AT", lifeExpectancy: 82.1, lifeExpectancyRank: 30 },
  { name: "Denmark", code: "DK", lifeExpectancy: 82.1, lifeExpectancyRank: 31 },
  { name: "Finland", code: "FI", lifeExpectancy: 82.1, lifeExpectancyRank: 32 },
  { name: "Greece", code: "GR", lifeExpectancy: 82.0, lifeExpectancyRank: 33 },
  { name: "Cyprus", code: "CY", lifeExpectancy: 81.8, lifeExpectancyRank: 34 },
  { name: "Slovenia", code: "SI", lifeExpectancy: 81.8, lifeExpectancyRank: 35 },
  { name: "Germany", code: "DE", lifeExpectancy: 81.5, lifeExpectancyRank: 36 },
  { name: "United Kingdom", code: "GB", lifeExpectancy: 81.5, lifeExpectancyRank: 37 },
  { name: "Bahrain", code: "BH", lifeExpectancy: 81.4, lifeExpectancyRank: 38 },
  { name: "Chile", code: "CL", lifeExpectancy: 81.4, lifeExpectancyRank: 39 },
  { name: "Maldives", code: "MV", lifeExpectancy: 81.3, lifeExpectancyRank: 40 },
  { name: "Costa Rica", code: "CR", lifeExpectancy: 81.0, lifeExpectancyRank: 41 },
  { name: "Kuwait", code: "KW", lifeExpectancy: 80.6, lifeExpectancyRank: 42 },
  { name: "Oman", code: "OM", lifeExpectancy: 80.3, lifeExpectancyRank: 43 },
  { name: "Czechia", code: "CZ", lifeExpectancy: 80.0, lifeExpectancyRank: 44 },
  { name: "United States", code: "US", lifeExpectancy: 79.5, lifeExpectancyRank: 45 },
  { name: "Saudi Arabia", code: "SA", lifeExpectancy: 79.0, lifeExpectancyRank: 46 },
  { name: "Poland", code: "PL", lifeExpectancy: 78.8, lifeExpectancyRank: 47 },
  { name: "China", code: "CN", lifeExpectancy: 78.0, lifeExpectancyRank: 48 },
  { name: "Turkey", code: "TR", lifeExpectancy: 77.4, lifeExpectancyRank: 49 },
  { name: "Argentina", code: "AR", lifeExpectancy: 77.5, lifeExpectancyRank: 50 },
  { name: "Brazil", code: "BR", lifeExpectancy: 76.0, lifeExpectancyRank: 51 },
  { name: "Mexico", code: "MX", lifeExpectancy: 75.3, lifeExpectancyRank: 52 },
  { name: "Vietnam", code: "VN", lifeExpectancy: 74.7, lifeExpectancyRank: 53 },
  { name: "India", code: "IN", lifeExpectancy: 72.2, lifeExpectancyRank: 54 },
  { name: "Indonesia", code: "ID", lifeExpectancy: 71.3, lifeExpectancyRank: 55 },
  { name: "Philippines", code: "PH", lifeExpectancy: 70.0, lifeExpectancyRank: 56 },
  { name: "South Africa", code: "ZA", lifeExpectancy: 66.3, lifeExpectancyRank: 57 },
  { name: "Nigeria", code: "NG", lifeExpectancy: 54.6, lifeExpectancyRank: 58 }
];