export const longestriverData = [
  { name: 'Egypt', code: 'EG', longestriverRank: 1, longestriver: 6650, riverName: 'Nile' },
  { name: 'Brazil', code: 'BR', longestriverRank: 2, longestriver: 6400, riverName: 'Amazon' },
  { name: 'United States', code: 'US', longestriverRank: 3, longestriver: 6275, riverName: 'Missouri-Mississippi' },
  { name: 'China', code: 'CN', longestriverRank: 4, longestriver: 6300, riverName: 'Yangtze' },
  { name: 'DR Congo', code: 'CD', longestriverRank: 5, longestriver: 4700, riverName: 'Congo' },
  { name: 'Russia', code: 'RU', longestriverRank: 6, longestriver: 4400, riverName: 'Lena' },
  { name: 'Vietnam', code: 'VN', longestriverRank: 7, longestriver: 4350, riverName: 'Mekong' },
  { name: 'Nigeria', code: 'NG', longestriverRank: 8, longestriver: 4180, riverName: 'Niger' },
  { name: 'Canada', code: 'CA', longestriverRank: 9, longestriver: 4241, riverName: 'Mackenzie' },
  { name: 'Argentina', code: 'AR', longestriverRank: 10, longestriver: 4880, riverName: 'Paraná' },
  { name: 'India', code: 'IN', longestriverRank: 11, longestriver: 3180, riverName: 'Indus' },
  { name: 'Pakistan', code: 'PK', longestriverRank: 12, longestriver: 3180, riverName: 'Indus' },
  { name: 'Germany', code: 'DE', longestriverRank: 13, longestriver: 2850, riverName: 'Danube' },
  { name: 'Iraq', code: 'IQ', longestriverRank: 14, longestriver: 2800, riverName: 'Euphrates' },
  { name: 'Bangladesh', code: 'BD', longestriverRank: 15, longestriver: 2900, riverName: 'Brahmaputra' },
  { name: 'Mozambique', code: 'MZ', longestriverRank: 16, longestriver: 2650, riverName: 'Zambezi' },
  { name: 'Venezuela', code: 'VE', longestriverRank: 17, longestriver: 2140, riverName: 'Orinoco' },
  { name: 'Afghanistan', code: 'AF', longestriverRank: 18, longestriver: 2400, riverName: 'Amu Darya' },
  { name: 'Ukraine', code: 'UA', longestriverRank: 19, longestriver: 2200, riverName: 'Dnieper' },
  { name: 'South Africa', code: 'ZA', longestriverRank: 20, longestriver: 2200, riverName: 'Orange' },
  { name: 'Myanmar', code: 'MM', longestriverRank: 21, longestriver: 2170, riverName: 'Irrawaddy' },
  { name: 'Australia', code: 'AU', longestriverRank: 22, longestriver: 2508, riverName: 'Murray-Darling' }
]
