export const longestriverData = [
  { name: 'Egypt', code: 'EG', longestriverRank: 1, longestriver: 6695, riverName: 'Nile' },
  { name: 'United States', code: 'US', longestriverRank: 2, longestriver: 6421, riverName: 'Missouri-Mississippi' },
  { name: 'Brazil', code: 'BR', longestriverRank: 3, longestriver: 6276, riverName: 'Amazon' },
  { name: 'DR Congo', code: 'CD', longestriverRank: 4, longestriver: 6276, riverName: 'Congo' },
  { name: 'China', code: 'CN', longestriverRank: 5, longestriver: 5150, riverName: 'Yangtze' },
  { name: 'Russia', code: 'RU', longestriverRank: 6, longestriver: 4506, riverName: 'Lena' },
  { name: 'Vietnam', code: 'VN', longestriverRank: 7, longestriver: 4184, riverName: 'Mekong' },
  { name: 'Nigeria', code: 'NG', longestriverRank: 8, longestriver: 4184, riverName: 'Niger' },
  { name: 'Canada', code: 'CA', longestriverRank: 9, longestriver: 4064, riverName: 'Mackenzie' },
  { name: 'India', code: 'IN', longestriverRank: 10, longestriver: 3058, riverName: 'Indus' },
  { name: 'Argentina', code: 'AR', longestriverRank: 11, longestriver: 3299, riverName: 'Paraná' },
  { name: 'Pakistan', code: 'PK', longestriverRank: 12, longestriver: 3058, riverName: 'Indus' },
  { name: 'Germany', code: 'DE', longestriverRank: 13, longestriver: 2776, riverName: 'Danube' },
  { name: 'Iraq', code: 'IQ', longestriverRank: 14, longestriver: 2736, riverName: 'Euphrates' },
  { name: 'Bangladesh', code: 'BD', longestriverRank: 15, longestriver: 2736, riverName: 'Brahmaputra' },
  { name: 'Mozambique', code: 'MZ', longestriverRank: 16, longestriver: 2655, riverName: 'Zambezi' },
  { name: 'Venezuela', code: 'VE', longestriverRank: 17, longestriver: 2575, riverName: 'Orinoco' },
  { name: 'Afghanistan', code: 'AF', longestriverRank: 18, longestriver: 2253, riverName: 'Amu Darya' },
  { name: 'Ukraine', code: 'UA', longestriverRank: 19, longestriver: 2253, riverName: 'Dnieper' },
  { name: 'South Africa', code: 'ZA', longestriverRank: 20, longestriver: 2092, riverName: 'Orange' },
  { name: 'Myanmar', code: 'MM', longestriverRank: 21, longestriver: 2012, riverName: 'Irrawaddy' },
  { name: 'Australia', code: 'AU', longestriverRank: 22, longestriver: 1931, riverName: 'Murray' },
];
