// js/categories/michelin.js
// Ranking countries by total Michelin-starred restaurants (≥1 star)

export const michelinData = [
  { name: "France", code: "FR", michelinTotal: 654, michelinRank: 1 },
  { name: "Italy", code: "IT", michelinTotal: 393, michelinRank: 2 },
  { name: "Japan", code: "JP", michelinTotal: 351, michelinRank: 3 },
  { name: "Germany", code: "DE", michelinTotal: 341, michelinRank: 4 },
  { name: "Spain", code: "ES", michelinTotal: 291, michelinRank: 5 },
  { name: "United States", code: "US", michelinTotal: 235, michelinRank: 6 },
  { name: "United Kingdom", code: "GB", michelinTotal: 220, michelinRank: 7 },
  { name: "Switzerland", code: "CH", michelinTotal: 145, michelinRank: 8 },
  { name: "Belgium", code: "BE", michelinTotal: 140, michelinRank: 9 },
  { name: "China", code: "CN", michelinTotal: 131, michelinRank: 10 },
  { name: "Netherlands", code: "NL", michelinTotal: 119, michelinRank: 11 },
  { name: "Austria", code: "AT", michelinTotal: 82, michelinRank: 12 },
  { name: "Hong Kong", code: "HK", michelinTotal: 76, michelinRank: 13 },
  { name: "Taiwan", code: "TW", michelinTotal: 53, michelinRank: 14 },
  { name: "Portugal", code: "PT", michelinTotal: 46, michelinRank: 15 },
  { name: "Singapore", code: "SG", michelinTotal: 42, michelinRank: 16 },
  { name: "South Korea", code: "KR", michelinTotal: 40, michelinRank: 17 },
  { name: "Canada", code: "CA", michelinTotal: 38, michelinRank: 18 },
  { name: "Denmark", code: "DK", michelinTotal: 37, michelinRank: 19 },
  { name: "Thailand", code: "TH", michelinTotal: 28, michelinRank: 20 },
  { name: "Brazil", code: "BR", michelinTotal: 25, michelinRank: 21 },
  { name: "United Arab Emirates", code: "AE", michelinTotal: 23, michelinRank: 22 },
  { name: "Mexico", code: "MX", michelinTotal: 23, michelinRank: 23 },
  { name: "Sweden", code: "SE", michelinTotal: 23, michelinRank: 24 },
  { name: "Norway", code: "NO", michelinTotal: 22, michelinRank: 25 },
  { name: "Ireland", code: "IE", michelinTotal: 21, michelinRank: 26 },
  { name: "Macau", code: "MO", michelinTotal: 19, michelinRank: 27 },
  { name: "Turkey", code: "TR", michelinTotal: 14, michelinRank: 28 },
  { name: "Croatia", code: "HR", michelinTotal: 13, michelinRank: 29 },
  { name: "Greece", code: "GR", michelinTotal: 12, michelinRank: 30 },
  { name: "Luxembourg", code: "LU", michelinTotal: 11, michelinRank: 31 },
  { name: "Argentina", code: "AR", michelinTotal: 10, michelinRank: 32 },
  { name: "Vietnam", code: "VN", michelinTotal: 9, michelinRank: 33 },
  { name: "Malaysia", code: "MY", michelinTotal: 9, michelinRank: 34 },
  { name: "Slovenia", code: "SI", michelinTotal: 9, michelinRank: 35 },
  { name: "Hungary", code: "HU", michelinTotal: 8, michelinRank: 36 },
  { name: "Poland", code: "PL", michelinTotal: 7, michelinRank: 37 },
  { name: "Finland", code: "FI", michelinTotal: 7, michelinRank: 38 },
  { name: "Malta", code: "MT", michelinTotal: 7, michelinRank: 39 },
  { name: "San Marino", code: "SM", michelinTotal: 6, michelinRank: 40 },
  { name: "Lithuania", code: "LT", michelinTotal: 4, michelinRank: 41 },
  { name: "Iceland", code: "IS", michelinTotal: 3, michelinRank: 42 },
  { name: "Czechia", code: "CZ", michelinTotal: 2, michelinRank: 43 },
  { name: "Serbia", code: "RS", michelinTotal: 2, michelinRank: 44 },
  { name: "Qatar", code: "QA", michelinTotal: 2, michelinRank: 45 },
  { name: "Latvia", code: "LV", michelinTotal: 2, michelinRank: 46 },
  { name: "Estonia", code: "EE", michelinTotal: 2, michelinRank: 47 },
  { name: "Andorra", code: "AD", michelinTotal: 1, michelinRank: 48 },
  { name: "Liechtenstein", code: "LI", michelinTotal: 1, michelinRank: 49 }
];
