export const nobelprizeData = [
  { name: 'United States',     code: 'united-states',      nobelPrizeRank: 1,  nobelPrizes: 423 },
  { name: 'United Kingdom',    code: 'united-kingdom',     nobelPrizeRank: 2,  nobelPrizes: 143 },
  { name: 'Germany',           code: 'germany',            nobelPrizeRank: 3,  nobelPrizes: 115 },
  { name: 'France',            code: 'france',             nobelPrizeRank: 4,  nobelPrizes: 76  },
  { name: 'Sweden',            code: 'sweden',             nobelPrizeRank: 5,  nobelPrizes: 34  },
  { name: 'Japan',             code: 'japan',              nobelPrizeRank: 6,  nobelPrizes: 31  },
  { name: 'Russia',            code: 'russia',             nobelPrizeRank: 7,  nobelPrizes: 30  },
  { name: 'Canada',            code: 'canada',             nobelPrizeRank: 8,  nobelPrizes: 28  },
  { name: 'Switzerland',       code: 'switzerland',        nobelPrizeRank: 9,  nobelPrizes: 25  },
  { name: 'Netherlands',       code: 'netherlands',        nobelPrizeRank: 10, nobelPrizes: 22  },
  { name: 'Italy',             code: 'italy',              nobelPrizeRank: 11, nobelPrizes: 21  },
  { name: 'Poland',            code: 'poland',             nobelPrizeRank: 12, nobelPrizes: 19  },
  { name: 'Hungary',           code: 'hungary',            nobelPrizeRank: 13, nobelPrizes: 15  },
  { name: 'Denmark',           code: 'denmark',            nobelPrizeRank: 14, nobelPrizes: 14  },
  { name: 'India',             code: 'india',              nobelPrizeRank: 15, nobelPrizes: 13  },
  { name: 'Belgium',           code: 'belgium',            nobelPrizeRank: 16, nobelPrizes: 11  },
  { name: 'China',             code: 'china',              nobelPrizeRank: 17, nobelPrizes: 8   },
  { name: 'Ukraine',           code: 'ukraine',            nobelPrizeRank: 18, nobelPrizes: 6   },
  { name: 'Finland',           code: 'finland',            nobelPrizeRank: 19, nobelPrizes: 5   },
  { name: 'Romania',           code: 'romania',            nobelPrizeRank: 20, nobelPrizes: 4   },
  { name: 'South Korea',       code: 'south-korea',        nobelPrizeRank: 21, nobelPrizes: 3   },
  { name: 'Luxembourg',        code: 'luxembourg',         nobelPrizeRank: 22, nobelPrizes: 2   },
  { name: 'Bangladesh',        code: 'bangladesh',         nobelPrizeRank: 23, nobelPrizes: 1   }
];
