export const nobelprizeData = [
  { name: 'United States',     code: 'US',      nobelPrizeRank: 1,  nobelPrizes: 423, nobelprize: 423 },
  { name: 'United Kingdom',    code: 'GB',     nobelPrizeRank: 2,  nobelPrizes: 143, nobelprize: 143 },
  { name: 'Germany',           code: 'DE',            nobelPrizeRank: 3,  nobelPrizes: 115, nobelprize: 115 },
  { name: 'France',            code: 'FR',             nobelPrizeRank: 4,  nobelPrizes: 76, nobelprize: 76  },
  { name: 'Sweden',            code: 'SE',             nobelPrizeRank: 5,  nobelPrizes: 34, nobelprize: 34  },
  { name: 'Japan',             code: 'JP',              nobelPrizeRank: 6,  nobelPrizes: 31, nobelprize: 31  },
  { name: 'Russia',            code: 'RU',             nobelPrizeRank: 7,  nobelPrizes: 30, nobelprize: 30  },
  { name: 'Canada',            code: 'CA',             nobelPrizeRank: 8,  nobelPrizes: 28, nobelprize: 28  },
  { name: 'Switzerland',       code: 'CH',        nobelPrizeRank: 9,  nobelPrizes: 25, nobelprize: 25  },
  { name: 'Netherlands',       code: 'NL',        nobelPrizeRank: 10, nobelPrizes: 22, nobelprize: 22  },
  { name: 'Italy',             code: 'IT',              nobelPrizeRank: 11, nobelPrizes: 21, nobelprize: 21  },
  { name: 'Poland',            code: 'PL',             nobelPrizeRank: 12, nobelPrizes: 19, nobelprize: 19  },
  { name: 'Hungary',           code: 'HU',            nobelPrizeRank: 13, nobelPrizes: 15, nobelprize: 15  },
  { name: 'Denmark',           code: 'DK',            nobelPrizeRank: 14, nobelPrizes: 14, nobelprize: 14  },
  { name: 'India',             code: 'IN',              nobelPrizeRank: 15, nobelPrizes: 13, nobelprize: 13  },
  { name: 'Belgium',           code: 'BE',            nobelPrizeRank: 16, nobelPrizes: 11, nobelprize: 11  },
  { name: 'China',             code: 'CN',              nobelPrizeRank: 17, nobelPrizes: 8, nobelprize: 8   },
  { name: 'Ukraine',           code: 'UA',            nobelPrizeRank: 18, nobelPrizes: 6, nobelprize: 6   },
  { name: 'Finland',           code: 'FI',            nobelPrizeRank: 19, nobelPrizes: 5, nobelprize: 5   },
  { name: 'Romania',           code: 'RO',            nobelPrizeRank: 20, nobelPrizes: 4, nobelprize: 4   },
  { name: 'South Korea',       code: 'KR',        nobelPrizeRank: 21, nobelPrizes: 3, nobelprize: 3   },
  { name: 'Luxembourg',        code: 'LU',         nobelPrizeRank: 22, nobelPrizes: 2, nobelprize: 2   },
  { name: 'Bangladesh',        code: 'BD',         nobelPrizeRank: 23, nobelPrizes: 1, nobelprize: 1   }
];