export const olympicData = [
  { name: 'United States', code: 'united-states', olympicRank: 1, medals: 3105 },
  { name: 'Germany', code: 'germany', olympicRank: 2, medals: 1211 },
  { name: 'France', code: 'france', olympicRank: 3, medals: 1040 },
  { name: 'United Kingdom', code: 'united-kingdom', olympicRank: 4, medals: 1035 },
  { name: 'China', code: 'china', olympicRank: 5, medals: 900 },
  { name: 'Italy', code: 'italy', olympicRank: 6, medals: 885 },
  { name: 'Russia', code: 'russia', olympicRank: 7, medals: 779 },
  { name: 'Sweden', code: 'sweden', olympicRank: 8, medals: 740 },
  { name: 'Japan', code: 'japan', olympicRank: 9, medals: 690 },
  { name: 'Australia', code: 'australia', olympicRank: 10, medals: 636 },
  { name: 'Norway', code: 'norway', olympicRank: 11, medals: 617 },
  { name: 'Canada', code: 'canada', olympicRank: 12, medals: 604 },
  { name: 'Hungary', code: 'hungary', olympicRank: 13, medals: 601 },
  { name: 'Netherlands', code: 'netherlands', olympicRank: 14, medals: 512 },
  { name: 'Finland', code: 'finland', olympicRank: 15, medals: 507 },
  { name: 'South Korea', code: 'south-korea', olympicRank: 16, medals: 447 },
  { name: 'Switzerland', code: 'switzerland', olympicRank: 17, medals: 441 },
  { name: 'Austria', code: 'austria', olympicRank: 18, medals: 412 },
  { name: 'Poland', code: 'poland', olympicRank: 19, medals: 346 },
  { name: 'Romania', code: 'romania', olympicRank: 20, medals: 332 },
  { name: 'Cuba', code: 'cuba', olympicRank: 21, medals: 259 },
  { name: 'Bulgaria', code: 'bulgaria', olympicRank: 22, medals: 246 },
  { name: 'Denmark', code: 'denmark', olympicRank: 23, medals: 232 },
  { name: 'Ukraine', code: 'ukraine', olympicRank: 24, medals: 225 },
  { name: 'Spain', code: 'spain', olympicRank: 25, medals: 208 },
  { name: 'Belgium', code: 'belgium', olympicRank: 26, medals: 202 },
  { name: 'Brazil', code: 'brazil', olympicRank: 27, medals: 182 },
  { name: 'Greece', code: 'greece', olympicRank: 28, medals: 169 },
  { name: 'New Zealand', code: 'new-zealand', olympicRank: 29, medals: 160 },
  { name: 'Turkey', code: 'turkey', olympicRank: 30, medals: 134 },
];
