export const olympicData = [
  { name: 'United States', code: 'US', olympicRank: 1, medals: 3105, olympic: 3105 },
  { name: 'Germany', code: 'DE', olympicRank: 2, medals: 1211, olympic: 1211 },
  { name: 'France', code: 'FR', olympicRank: 3, medals: 1040, olympic: 1040 },
  { name: 'United Kingdom', code: 'GB', olympicRank: 4, medals: 1035, olympic: 1035 },
  { name: 'China', code: 'CN', olympicRank: 5, medals: 900, olympic: 900 },
  { name: 'Italy', code: 'IT', olympicRank: 6, medals: 885, olympic: 885 },
  { name: 'Russia', code: 'RU', olympicRank: 7, medals: 779, olympic: 779 },
  { name: 'Sweden', code: 'SE', olympicRank: 8, medals: 740, olympic: 740 },
  { name: 'Japan', code: 'JP', olympicRank: 9, medals: 690, olympic: 690 },
  { name: 'Australia', code: 'AU', olympicRank: 10, medals: 636, olympic: 636 },
  { name: 'Norway', code: 'NO', olympicRank: 11, medals: 617, olympic: 617 },
  { name: 'Canada', code: 'CA', olympicRank: 12, medals: 604, olympic: 604 },
  { name: 'Hungary', code: 'HU', olympicRank: 13, medals: 601, olympic: 601 },
  { name: 'Netherlands', code: 'NL', olympicRank: 14, medals: 512, olympic: 512 },
  { name: 'Finland', code: 'FI', olympicRank: 15, medals: 507, olympic: 507 },
  { name: 'South Korea', code: 'KR', olympicRank: 16, medals: 447, olympic: 447 },
  { name: 'Switzerland', code: 'CH', olympicRank: 17, medals: 441, olympic: 441 },
  { name: 'Austria', code: 'AT', olympicRank: 18, medals: 412, olympic: 412 },
  { name: 'Poland', code: 'PL', olympicRank: 19, medals: 346, olympic: 346 },
  { name: 'Romania', code: 'RO', olympicRank: 20, medals: 332, olympic: 332 },
  { name: 'Cuba', code: 'CU', olympicRank: 21, medals: 259, olympic: 259 },
  { name: 'Bulgaria', code: 'BG', olympicRank: 22, medals: 246, olympic: 246 },
  { name: 'Denmark', code: 'DK', olympicRank: 23, medals: 232, olympic: 232 },
  { name: 'Ukraine', code: 'UA', olympicRank: 24, medals: 225, olympic: 225 },
  { name: 'Spain', code: 'ES', olympicRank: 25, medals: 208, olympic: 208 },
  { name: 'Belgium', code: 'BE', olympicRank: 26, medals: 202, olympic: 202 },
  { name: 'Brazil', code: 'BR', olympicRank: 27, medals: 182, olympic: 182 },
  { name: 'Greece', code: 'GR', olympicRank: 28, medals: 169, olympic: 169 },
  { name: 'New Zealand', code: 'NZ', olympicRank: 29, medals: 160, olympic: 160 },
  { name: 'Turkey', code: 'TR', olympicRank: 30, medals: 134, olympic: 134 },
];