export const passportData = [
  { name: 'United Arab Emirates', code: 'united-arab-emirates', passportRank: 1, passportstrength: 179, tieGroup: 1 },
  { name: 'Singapore', code: 'singapore', passportRank: 2, passportstrength: 175, tieGroup: 2 },
  { name: 'Spain', code: 'spain', passportRank: 2, passportstrength: 175, tieGroup: 2 },
  { name: 'Belgium', code: 'belgium', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'France', code: 'france', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Germany', code: 'germany', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Netherlands', code: 'netherlands', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Finland', code: 'finland', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Luxembourg', code: 'luxembourg', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Italy', code: 'italy', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Denmark', code: 'denmark', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Portugal', code: 'portugal', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Switzerland', code: 'switzerland', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Greece', code: 'greece', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Austria', code: 'austria', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Norway', code: 'norway', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Ireland', code: 'ireland', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'South Korea', code: 'south-korea', passportRank: 3, passportstrength: 174, tieGroup: 3 },
  { name: 'Sweden', code: 'sweden', passportRank: 4, passportstrength: 173, tieGroup: 4 },
  { name: 'Poland', code: 'poland', passportRank: 4, passportstrength: 173, tieGroup: 4 },
  { name: 'Slovenia', code: 'slovenia', passportRank: 4, passportstrength: 173, tieGroup: 4 },
  { name: 'Croatia', code: 'croatia', passportRank: 4, passportstrength: 173, tieGroup: 4 },
  { name: 'Slovakia', code: 'slovakia', passportRank: 4, passportstrength: 173, tieGroup: 4 },
  { name: 'Hungary', code: 'hungary', passportRank: 4, passportstrength: 173, tieGroup: 4 },
  { name: 'Estonia', code: 'estonia', passportRank: 4, passportstrength: 173, tieGroup: 4 },
  { name: 'Japan', code: 'japan', passportRank: 4, passportstrength: 173, tieGroup: 4 },
  { name: 'Malta', code: 'malta', passportRank: 5, passportstrength: 172, tieGroup: 5 },
  { name: 'Czech Republic', code: 'czech-republic', passportRank: 5, passportstrength: 172, tieGroup: 5 },
  { name: 'Romania', code: 'romania', passportRank: 5, passportstrength: 172, tieGroup: 5 },
  { name: 'Latvia', code: 'latvia', passportRank: 5, passportstrength: 172, tieGroup: 5 },
  { name: 'Bulgaria', code: 'bulgaria', passportRank: 5, passportstrength: 172, tieGroup: 5 },
  { name: 'New Zealand', code: 'new-zealand', passportRank: 5, passportstrength: 172, tieGroup: 5 },
  { name: 'Lithuania', code: 'lithuania', passportRank: 6, passportstrength: 171, tieGroup: 6 },
  { name: 'Liechtenstein', code: 'liechtenstein', passportRank: 6, passportstrength: 171, tieGroup: 6 },
  { name: 'Australia', code: 'australia', passportRank: 6, passportstrength: 171, tieGroup: 6 },
  { name: 'Cyprus', code: 'cyprus', passportRank: 7, passportstrength: 170, tieGroup: 7 },
  { name: 'Malaysia', code: 'malaysia', passportRank: 7, passportstrength: 170, tieGroup: 7 },
  { name: 'Iceland', code: 'iceland', passportRank: 7, passportstrength: 170, tieGroup: 7 },
  { name: 'United Kingdom', code: 'united-kingdom', passportRank: 8, passportstrength: 169, tieGroup: 8 },
  { name: 'Canada', code: 'canada', passportRank: 8, passportstrength: 169, tieGroup: 8 },
  { name: 'United States', code: 'united-states', passportRank: 9, passportstrength: 168, tieGroup: 9 },
  { name: 'Monaco', code: 'monaco', passportRank: 10, passportstrength: 167, tieGroup: 10 },
  { name: 'Brazil', code: 'brazil', passportRank: 11, passportstrength: 163, tieGroup: 11 },
  { name: 'Hong Kong', code: 'hong-kong', passportRank: 12, passportstrength: 162, tieGroup: 12 },
  { name: 'Chile', code: 'chile', passportRank: 12, passportstrength: 162, tieGroup: 12 },
  { name: 'Argentina', code: 'argentina', passportRank: 12, passportstrength: 162, tieGroup: 12 },
  { name: 'San Marino', code: 'san-marino', passportRank: 13, passportstrength: 161, tieGroup: 13 },
  { name: 'Andorra', code: 'andorra', passportRank: 13, passportstrength: 161, tieGroup: 13 },
  { name: 'Barbados', code: 'barbados', passportRank: 14, passportstrength: 156, tieGroup: 14 },
  { name: 'Brunei', code: 'brunei', passportRank: 15, passportstrength: 155, tieGroup: 15 },
  { name: 'Bahamas', code: 'bahamas', passportRank: 16, passportstrength: 154, tieGroup: 16 },
  { name: 'Israel', code: 'israel', passportRank: 17, passportstrength: 153, tieGroup: 17 },
  { name: 'Mexico', code: 'mexico', passportRank: 17, passportstrength: 153, tieGroup: 17 },
  { name: 'Uruguay', code: 'uruguay', passportRank: 18, passportstrength: 151, tieGroup: 18 },
  { name: 'Vatican City', code: 'vatican-city', passportRank: 19, passportstrength: 150, tieGroup: 19 },
  { name: 'Peru', code: 'peru', passportRank: 19, passportstrength: 150, tieGroup: 19 },
  { name: 'Saint Kitts and Nevis', code: 'saint-kitts-and-nevis', passportRank: 20, passportstrength: 149, tieGroup: 20 },
  { name: 'Seychelles', code: 'seychelles', passportRank: 20, passportstrength: 149, tieGroup: 20 },
  { name: 'Saint Vincent and the Grenadines', code: 'saint-vincent-and-the-grenadines', passportRank: 21, passportstrength: 147, tieGroup: 21 },
  { name: 'Ukraine', code: 'ukraine', passportRank: 21, passportstrength: 147, tieGroup: 21 },
  { name: 'Antigua and Barbuda', code: 'antigua-and-barbuda', passportRank: 22, passportstrength: 144, tieGroup: 22 },
  { name: 'Costa Rica', code: 'costa-rica', passportRank: 22, passportstrength: 144, tieGroup: 22 },
  { name: 'Paraguay', code: 'paraguay', passportRank: 22, passportstrength: 144, tieGroup: 22 },
  { name: 'Trinidad and Tobago', code: 'trinidad-and-tobago', passportRank: 23, passportstrength: 143, tieGroup: 23 },
  { name: 'Macao', code: 'macao', passportRank: 23, passportstrength: 143, tieGroup: 23 },
  { name: 'Mauritius', code: 'mauritius', passportRank: 24, passportstrength: 141, tieGroup: 24 },
  { name: 'Grenada', code: 'grenada', passportRank: 24, passportstrength: 141, tieGroup: 24 },
  { name: 'Panama', code: 'panama', passportRank: 24, passportstrength: 141, tieGroup: 24 },
  { name: 'Saint Lucia', code: 'saint-lucia', passportRank: 25, passportstrength: 140, tieGroup: 25 },
  { name: 'Dominica', code: 'dominica', passportRank: 26, passportstrength: 137, tieGroup: 26 },
  { name: 'Solomon Islands', code: 'solomon-islands', passportRank: 26, passportstrength: 137, tieGroup: 26 },
  { name: 'Serbia', code: 'serbia', passportRank: 27, passportstrength: 135, tieGroup: 27 },
  { name: 'Colombia', code: 'colombia', passportRank: 27, passportstrength: 135, tieGroup: 27 },
  { name: 'North Macedonia', code: 'north-macedonia', passportRank: 28, passportstrength: 133, tieGroup: 28 },
  { name: 'Guatemala', code: 'guatemala', passportRank: 28, passportstrength: 133, tieGroup: 28 },
  { name: 'Georgia', code: 'georgia', passportRank: 28, passportstrength: 133, tieGroup: 28 },
  { name: 'Samoa', code: 'samoa', passportRank: 29, passportstrength: 132, tieGroup: 29 },
  { name: 'El Salvador', code: 'el-salvador', passportRank: 29, passportstrength: 132, tieGroup: 29 },
  { name: 'Honduras', code: 'honduras', passportRank: 30, passportstrength: 131, tieGroup: 30 },
  { name: 'Montenegro', code: 'montenegro', passportRank: 30, passportstrength: 131, tieGroup: 30 },
  { name: 'Tuvalu', code: 'tuvalu', passportRank: 31, passportstrength: 130, tieGroup: 31 },
  { name: 'Taiwan', code: 'taiwan', passportRank: 32, passportstrength: 129, tieGroup: 32 },
  { name: 'Kiribati', code: 'kiribati', passportRank: 32, passportstrength: 129, tieGroup: 32 },
  { name: 'Tonga', code: 'tonga', passportRank: 33, passportstrength: 128, tieGroup: 33 },
  { name: 'Marshall Islands', code: 'marshall-islands', passportRank: 34, passportstrength: 126, tieGroup: 34 },
  { name: 'Nicaragua', code: 'nicaragua', passportRank: 34, passportstrength: 126, tieGroup: 34 },
  { name: 'Venezuela', code: 'venezuela', passportRank: 34, passportstrength: 126, tieGroup: 34 },
  { name: 'Russian Federation', code: 'russia', passportRank: 35, passportstrength: 125, tieGroup: 35 },
  { name: 'Moldova', code: 'moldova', passportRank: 35, passportstrength: 125, tieGroup: 35 },
  { name: 'Bosnia and Herzegovina', code: 'bosnia-and-herzegovina', passportRank: 36, passportstrength: 124, tieGroup: 36 },
  { name: 'Türkiye', code: 'turkey', passportRank: 36, passportstrength: 124, tieGroup: 36 },
  { name: 'Palau', code: 'palau', passportRank: 37, passportstrength: 123, tieGroup: 37 },
  { name: 'Albania', code: 'albania', passportRank: 38, passportstrength: 122, tieGroup: 38 },
  { name: 'Micronesia', code: 'micronesia', passportRank: 39, passportstrength: 121, tieGroup: 39 },
  { name: 'Qatar', code: 'qatar', passportRank: 40, passportstrength: 119, tieGroup: 40 },
  { name: 'Kuwait', code: 'kuwait', passportRank: 41, passportstrength: 111, tieGroup: 41 },
  { name: 'South Africa', code: 'south-africa', passportRank: 42, passportstrength: 110, tieGroup: 42 },
  { name: 'Ecuador', code: 'ecuador', passportRank: 43, passportstrength: 104, tieGroup: 43 },
  { name: 'Timor-Leste', code: 'timor-leste', passportRank: 44, passportstrength: 103, tieGroup: 44 },
  { name: 'Belize', code: 'belize', passportRank: 45, passportstrength: 102, tieGroup: 45 },
  { name: 'Saudi Arabia', code: 'saudi-arabia', passportRank: 45, passportstrength: 102, tieGroup: 45 },
  { name: 'Maldives', code: 'maldives', passportRank: 45, passportstrength: 102, tieGroup: 45 },
  { name: 'Bahrain', code: 'bahrain', passportRank: 46, passportstrength: 101, tieGroup: 46 },
  { name: 'Jamaica', code: 'jamaica', passportRank: 47, passportstrength: 100, tieGroup: 47 },
  { name: 'Guyana', code: 'guyana', passportRank: 48, passportstrength: 98, tieGroup: 48 },
  { name: 'Fiji', code: 'fiji', passportRank: 48, passportstrength: 98, tieGroup: 48 },
  { name: 'Oman', code: 'oman', passportRank: 49, passportstrength: 97, tieGroup: 49 },
  { name: 'Vanuatu', code: 'vanuatu', passportRank: 50, passportstrength: 96, tieGroup: 50 },
  { name: 'Thailand', code: 'thailand', passportRank: 50, passportstrength: 96, tieGroup: 50 },
  { name: 'Kazakhstan', code: 'kazakhstan', passportRank: 51, passportstrength: 95, tieGroup: 51 },
  { name: 'Belarus', code: 'belarus', passportRank: 52, passportstrength: 94, tieGroup: 52 },
  { name: 'Kosovo', code: 'kosovo', passportRank: 53, passportstrength: 93, tieGroup: 53 },
  { name: 'China', code: 'china', passportRank: 53, passportstrength: 93, tieGroup: 53 },
  { name: 'Indonesia', code: 'indonesia', passportRank: 54, passportstrength: 92, tieGroup: 54 },
  { name: 'Nauru', code: 'nauru', passportRank: 55, passportstrength: 90, tieGroup: 55 },
  { name: 'Suriname', code: 'suriname', passportRank: 56, passportstrength: 89, tieGroup: 56 },
  { name: 'Bolivia', code: 'bolivia', passportRank: 56, passportstrength: 89, tieGroup: 56 },
  { name: 'Papua New Guinea', code: 'papua-new-guinea', passportRank: 57, passportstrength: 88, tieGroup: 57 },
  { name: 'Azerbaijan', code: 'azerbaijan', passportRank: 58, passportstrength: 87, tieGroup: 58 },
  { name: 'Botswana', code: 'botswana', passportRank: 59, passportstrength: 85, tieGroup: 59 },
  { name: 'Morocco', code: 'morocco', passportRank: 59, passportstrength: 85, tieGroup: 59 },
  { name: 'Dominican Republic', code: 'dominican-republic', passportRank: 59, passportstrength: 85, tieGroup: 59 },
  { name: 'Lesotho', code: 'lesotho', passportRank: 60, passportstrength: 82, tieGroup: 60 },
  { name: 'Eswatini', code: 'eswatini', passportRank: 61, passportstrength: 81, tieGroup: 61 },
  { name: 'Armenia', code: 'armenia', passportRank: 61, passportstrength: 81, tieGroup: 61 },
  { name: 'Namibia', code: 'namibia', passportRank: 62, passportstrength: 80, tieGroup: 62 },
  { name: 'Malawi', code: 'malawi', passportRank: 62, passportstrength: 80, tieGroup: 62 },
  { name: 'Kenya', code: 'kenya', passportRank: 63, passportstrength: 78, tieGroup: 63 },
  { name: 'Mongolia', code: 'mongolia', passportRank: 63, passportstrength: 78, tieGroup: 63 },
  { name: 'Tunisia', code: 'tunisia', passportRank: 63, passportstrength: 78, tieGroup: 63 },
  { name: 'Philippines', code: 'philippines', passportRank: 63, passportstrength: 78, tieGroup: 63 },
  { name: 'Tanzania', code: 'tanzania', passportRank: 64, passportstrength: 76, tieGroup: 64 },
  { name: 'Zambia', code: 'zambia', passportRank: 64, passportstrength: 76, tieGroup: 64 },
  { name: 'Uzbekistan', code: 'uzbekistan', passportRank: 64, passportstrength: 76, tieGroup: 64 },
  { name: 'Ghana', code: 'ghana', passportRank: 65, passportstrength: 75, tieGroup: 65 },
  { name: 'Cape Verde', code: 'cape-verde', passportRank: 65, passportstrength: 75, tieGroup: 65 },
  { name: 'Cuba', code: 'cuba', passportRank: 65, passportstrength: 75, tieGroup: 65 },
  { name: 'Kyrgyzstan', code: 'kyrgyzstan', passportRank: 65, passportstrength: 75, tieGroup: 65 },
  { name: 'Gambia', code: 'gambia', passportRank: 66, passportstrength: 74, tieGroup: 66 },
  { name: 'India', code: 'india', passportRank: 66, passportstrength: 74, tieGroup: 66 },
  { name: 'Uganda', code: 'uganda', passportRank: 67, passportstrength: 73, tieGroup: 67 },
  { name: 'Rwanda', code: 'rwanda', passportRank: 67, passportstrength: 73, tieGroup: 67 },
  { name: 'Zimbabwe', code: 'zimbabwe', passportRank: 68, passportstrength: 72, tieGroup: 68 },
  { name: 'Sao Tome and Principe', code: 'sao-tome-and-principe', passportRank: 68, passportstrength: 72, tieGroup: 68 },
  { name: 'Tajikistan', code: 'tajikistan', passportRank: 68, passportstrength: 72, tieGroup: 68 },
  { name: 'Benin', code: 'benin', passportRank: 69, passportstrength: 70, tieGroup: 69 },
  { name: 'Madagascar', code: 'madagascar', passportRank: 69, passportstrength: 70, tieGroup: 69 },
  { name: 'Viet Nam', code: 'vietnam', passportRank: 69, passportstrength: 70, tieGroup: 69 },
  { name: 'Gabon', code: 'gabon', passportRank: 70, passportstrength: 69, tieGroup: 70 },
  { name: 'Cambodia', code: 'cambodia', passportRank: 70, passportstrength: 69, tieGroup: 70 },
  { name: 'Algeria', code: 'algeria', passportRank: 70, passportstrength: 69, tieGroup: 70 },
  { name: 'Sierra Leone', code: 'sierra-leone', passportRank: 71, passportstrength: 68, tieGroup: 71 },
  { name: 'Senegal', code: 'senegal', passportRank: 71, passportstrength: 68, tieGroup: 71 },
  { name: 'Mozambique', code: 'mozambique', passportRank: 71, passportstrength: 68, tieGroup: 71 },
  { name: 'Togo', code: 'togo', passportRank: 72, passportstrength: 67, tieGroup: 72 },
  { name: 'Bhutan', code: 'bhutan', passportRank: 72, passportstrength: 67, tieGroup: 72 },
  { name: 'Burkina Faso', code: 'burkina-faso', passportRank: 73, passportstrength: 66, tieGroup: 73 },
  { name: 'Equatorial Guinea', code: 'equatorial-guinea', passportRank: 73, passportstrength: 66, tieGroup: 73 },
  { name: "Cote d'Ivoire", code: 'cote-divoire', passportRank: 74, passportstrength: 65, tieGroup: 74 },
  { name: 'Mauritania', code: 'mauritania', passportRank: 74, passportstrength: 65, tieGroup: 74 },
  { name: 'Jordan', code: 'jordan', passportRank: 74, passportstrength: 65, tieGroup: 74 },
  { name: 'Egypt', code: 'egypt', passportRank: 74, passportstrength: 65, tieGroup: 74 },
  { name: 'Turkmenistan', code: 'turkmenistan', passportRank: 74, passportstrength: 65, tieGroup: 74 },
  { name: 'Niger', code: 'niger', passportRank: 75, passportstrength: 64, tieGroup: 75 },
  { name: 'Angola', code: 'angola', passportRank: 75, passportstrength: 64, tieGroup: 75 },
  { name: 'Guinea', code: 'guinea', passportRank: 76, passportstrength: 63, tieGroup: 76 },
  { name: 'Laos', code: 'laos', passportRank: 76, passportstrength: 63, tieGroup: 76 },
  { name: 'Comoros', code: 'comoros', passportRank: 76, passportstrength: 63, tieGroup: 76 },
  { name: 'Haiti', code: 'haiti', passportRank: 77, passportstrength: 62, tieGroup: 77 },
  { name: 'Mali', code: 'mali', passportRank: 78, passportstrength: 61, tieGroup: 78 },
  { name: 'Central African Republic', code: 'central-african-republic', passportRank: 78, passportstrength: 61, tieGroup: 78 },
  { name: 'Djibouti', code: 'djibouti', passportRank: 78, passportstrength: 61, tieGroup: 78 },
  { name: 'Guinea-Bissau', code: 'guinea-bissau', passportRank: 79, passportstrength: 60, tieGroup: 79 },
  { name: 'Chad', code: 'chad', passportRank: 79, passportstrength: 60, tieGroup: 79 },
  { name: 'Cameroon', code: 'cameroon', passportRank: 79, passportstrength: 60, tieGroup: 79 },
  { name: 'Liberia', code: 'liberia', passportRank: 80, passportstrength: 59, tieGroup: 80 },
  { name: 'Burundi', code: 'burundi', passportRank: 81, passportstrength: 58, tieGroup: 81 },
  { name: 'Lebanon', code: 'lebanon', passportRank: 81, passportstrength: 58, tieGroup: 81 },
  { name: 'Myanmar', code: 'myanmar', passportRank: 81, passportstrength: 58, tieGroup: 81 },
  { name: 'Congo', code: 'congo', passportRank: 82, passportstrength: 57, tieGroup: 82 },
  { name: 'Sri Lanka', code: 'sri-lanka', passportRank: 82, passportstrength: 57, tieGroup: 82 },
  { name: 'Iran', code: 'iran', passportRank: 83, passportstrength: 55, tieGroup: 83 },
  { name: 'Ethiopia', code: 'ethiopia', passportRank: 83, passportstrength: 55, tieGroup: 83 },
  { name: 'Nigeria', code: 'nigeria', passportRank: 84, passportstrength: 54, tieGroup: 84 },
  { name: 'Congo (Dem. Rep.)', code: 'democratic-republic-of-the-congo', passportRank: 84, passportstrength: 54, tieGroup: 84 },
  { name: 'Nepal', code: 'nepal', passportRank: 84, passportstrength: 54, tieGroup: 84 },
  { name: 'South Sudan', code: 'south-sudan', passportRank: 85, passportstrength: 53, tieGroup: 85 },
  { name: 'Libya', code: 'libya', passportRank: 85, passportstrength: 53, tieGroup: 85 },
  { name: 'Sudan', code: 'sudan', passportRank: 85, passportstrength: 53, tieGroup: 85 },
  { name: 'Eritrea', code: 'eritrea', passportRank: 86, passportstrength: 51, tieGroup: 86 },
  { name: 'North Korea', code: 'north-korea', passportRank: 86, passportstrength: 51, tieGroup: 86 },
  { name: 'Bangladesh', code: 'bangladesh', passportRank: 87, passportstrength: 50, tieGroup: 87 },
  { name: 'Palestinian Territories', code: 'palestinian-territories', passportRank: 87, passportstrength: 50, tieGroup: 87 },
  { name: 'Yemen', code: 'yemen', passportRank: 88, passportstrength: 46, tieGroup: 88 },
  { name: 'Pakistan', code: 'pakistan', passportRank: 89, passportstrength: 45, tieGroup: 89 },
  { name: 'Somalia', code: 'somalia', passportRank: 89, passportstrength: 45, tieGroup: 89 },
  { name: 'Iraq', code: 'iraq', passportRank: 90, passportstrength: 44, tieGroup: 90 },
  { name: 'Syria', code: 'syria', passportRank: 91, passportstrength: 39, tieGroup: 91 },
  { name: 'Afghanistan', code: 'afghanistan', passportRank: 92, passportstrength: 38, tieGroup: 92 },
];

