export const passportData = [
  { name: 'United Arab Emirates', code: 'AE', passportRank: 1, passportstrength: 179, tieGroup: 1 },
  { name: 'Singapore', code: 'SG', passportRank: 2, passportstrength: 175, tieGroup: 2 },
  { name: 'Spain', code: 'ES', passportRank: 3, passportstrength: 175, tieGroup: 2 },
  { name: 'Austria', code: 'AT', passportRank: 4, passportstrength: 174, tieGroup: 3 },
  { name: 'Belgium', code: 'BE', passportRank: 5, passportstrength: 174, tieGroup: 3 },
  { name: 'Denmark', code: 'DK', passportRank: 6, passportstrength: 174, tieGroup: 3 },
  { name: 'Finland', code: 'FI', passportRank: 7, passportstrength: 174, tieGroup: 3 },
  { name: 'France', code: 'FR', passportRank: 8, passportstrength: 174, tieGroup: 3 },
  { name: 'Germany', code: 'DE', passportRank: 9, passportstrength: 174, tieGroup: 3 },
  { name: 'Greece', code: 'GR', passportRank: 10, passportstrength: 174, tieGroup: 3 },
  { name: 'Ireland', code: 'IE', passportRank: 11, passportstrength: 174, tieGroup: 3 },
  { name: 'Italy', code: 'IT', passportRank: 12, passportstrength: 174, tieGroup: 3 },
  { name: 'Luxembourg', code: 'LU', passportRank: 13, passportstrength: 174, tieGroup: 3 },
  { name: 'Netherlands', code: 'NL', passportRank: 14, passportstrength: 174, tieGroup: 3 },
  { name: 'Norway', code: 'NO', passportRank: 15, passportstrength: 174, tieGroup: 3 },
  { name: 'Portugal', code: 'PT', passportRank: 16, passportstrength: 174, tieGroup: 3 },
  { name: 'South Korea', code: 'KR', passportRank: 17, passportstrength: 174, tieGroup: 3 },
  { name: 'Switzerland', code: 'CH', passportRank: 18, passportstrength: 174, tieGroup: 3 },
  { name: 'Croatia', code: 'HR', passportRank: 19, passportstrength: 173, tieGroup: 4 },
  { name: 'Estonia', code: 'EE', passportRank: 20, passportstrength: 173, tieGroup: 4 },
  { name: 'Hungary', code: 'HU', passportRank: 21, passportstrength: 173, tieGroup: 4 },
  { name: 'Japan', code: 'JP', passportRank: 22, passportstrength: 173, tieGroup: 4 },
  { name: 'Poland', code: 'PL', passportRank: 23, passportstrength: 173, tieGroup: 4 },
  { name: 'Slovakia', code: 'SK', passportRank: 24, passportstrength: 173, tieGroup: 4 },
  { name: 'Slovenia', code: 'SI', passportRank: 25, passportstrength: 173, tieGroup: 4 },
  { name: 'Sweden', code: 'SE', passportRank: 26, passportstrength: 173, tieGroup: 4 },
  { name: 'Bulgaria', code: 'BG', passportRank: 27, passportstrength: 172, tieGroup: 5 },
  { name: 'Czech Republic', code: 'CZ', passportRank: 28, passportstrength: 172, tieGroup: 5 },
  { name: 'Latvia', code: 'LV', passportRank: 29, passportstrength: 172, tieGroup: 5 },
  { name: 'Malta', code: 'MT', passportRank: 30, passportstrength: 172, tieGroup: 5 },
  { name: 'New Zealand', code: 'NZ', passportRank: 31, passportstrength: 172, tieGroup: 5 },
  { name: 'Romania', code: 'RO', passportRank: 32, passportstrength: 172, tieGroup: 5 },
  { name: 'Australia', code: 'AU', passportRank: 33, passportstrength: 171, tieGroup: 6 },
  { name: 'Liechtenstein', code: 'LI', passportRank: 34, passportstrength: 171, tieGroup: 6 },
  { name: 'Lithuania', code: 'LT', passportRank: 35, passportstrength: 171, tieGroup: 6 },
  { name: 'Cyprus', code: 'CY', passportRank: 36, passportstrength: 170, tieGroup: 7 },
  { name: 'Iceland', code: 'IS', passportRank: 37, passportstrength: 170, tieGroup: 7 },
  { name: 'Malaysia', code: 'MY', passportRank: 38, passportstrength: 170, tieGroup: 7 },
  { name: 'Canada', code: 'CA', passportRank: 39, passportstrength: 169, tieGroup: 8 },
  { name: 'United Kingdom', code: 'GB', passportRank: 40, passportstrength: 169, tieGroup: 8 },
  { name: 'United States', code: 'US', passportRank: 41, passportstrength: 168, tieGroup: 9 },
  { name: 'Monaco', code: 'MC', passportRank: 42, passportstrength: 167, tieGroup: 10 },
  { name: 'Brazil', code: 'BR', passportRank: 43, passportstrength: 163, tieGroup: 11 },
  { name: 'Argentina', code: 'AR', passportRank: 44, passportstrength: 162, tieGroup: 12 },
  { name: 'Chile', code: 'CL', passportRank: 45, passportstrength: 162, tieGroup: 12 },
  { name: 'Hong Kong', code: 'HK', passportRank: 46, passportstrength: 162, tieGroup: 12 },
  { name: 'Andorra', code: 'AD', passportRank: 47, passportstrength: 161, tieGroup: 13 },
  { name: 'San Marino', code: 'SM', passportRank: 48, passportstrength: 161, tieGroup: 13 },
  { name: 'Barbados', code: 'BB', passportRank: 49, passportstrength: 156, tieGroup: 14 },
  { name: 'Brunei', code: 'BN', passportRank: 50, passportstrength: 155, tieGroup: 15 },
  { name: 'Bahamas', code: 'BS', passportRank: 51, passportstrength: 154, tieGroup: 16 },
  { name: 'Israel', code: 'IL', passportRank: 52, passportstrength: 153, tieGroup: 17 },
  { name: 'Mexico', code: 'MX', passportRank: 53, passportstrength: 153, tieGroup: 17 },
  { name: 'Uruguay', code: 'UY', passportRank: 54, passportstrength: 151, tieGroup: 18 },
  { name: 'Peru', code: 'PE', passportRank: 55, passportstrength: 150, tieGroup: 19 },
  { name: 'Vatican City', code: 'VA', passportRank: 56, passportstrength: 150, tieGroup: 19 },
  { name: 'Saint Kitts and Nevis', code: 'KN', passportRank: 57, passportstrength: 149, tieGroup: 20 },
  { name: 'Seychelles', code: 'SC', passportRank: 58, passportstrength: 149, tieGroup: 20 },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', passportRank: 59, passportstrength: 147, tieGroup: 21 },
  { name: 'Ukraine', code: 'UA', passportRank: 60, passportstrength: 147, tieGroup: 21 },
  { name: 'Antigua and Barbuda', code: 'AG', passportRank: 61, passportstrength: 144, tieGroup: 22 },
  { name: 'Costa Rica', code: 'CR', passportRank: 62, passportstrength: 144, tieGroup: 22 },
  { name: 'Paraguay', code: 'PY', passportRank: 63, passportstrength: 144, tieGroup: 22 },
  { name: 'Macao', code: 'MO', passportRank: 64, passportstrength: 143, tieGroup: 23 },
  { name: 'Trinidad and Tobago', code: 'TT', passportRank: 65, passportstrength: 143, tieGroup: 23 },
  { name: 'Grenada', code: 'GD', passportRank: 66, passportstrength: 141, tieGroup: 24 },
  { name: 'Mauritius', code: 'MU', passportRank: 67, passportstrength: 141, tieGroup: 24 },
  { name: 'Panama', code: 'PA', passportRank: 68, passportstrength: 141, tieGroup: 24 },
  { name: 'Saint Lucia', code: 'LC', passportRank: 69, passportstrength: 140, tieGroup: 25 },
  { name: 'Dominica', code: 'DM', passportRank: 70, passportstrength: 137, tieGroup: 26 },
  { name: 'Solomon Islands', code: 'SB', passportRank: 71, passportstrength: 137, tieGroup: 26 },
  { name: 'Colombia', code: 'CO', passportRank: 72, passportstrength: 135, tieGroup: 27 },
  { name: 'Serbia', code: 'RS', passportRank: 73, passportstrength: 135, tieGroup: 27 },
  { name: 'Georgia', code: 'GE', passportRank: 74, passportstrength: 133, tieGroup: 28 },
  { name: 'Guatemala', code: 'GT', passportRank: 75, passportstrength: 133, tieGroup: 28 },
  { name: 'North Macedonia', code: 'MK', passportRank: 76, passportstrength: 133, tieGroup: 28 },
  { name: 'El Salvador', code: 'SV', passportRank: 77, passportstrength: 132, tieGroup: 29 },
  { name: 'Samoa', code: 'WS', passportRank: 78, passportstrength: 132, tieGroup: 29 },
  { name: 'Honduras', code: 'HN', passportRank: 79, passportstrength: 131, tieGroup: 30 },
  { name: 'Montenegro', code: 'ME', passportRank: 80, passportstrength: 131, tieGroup: 30 },
  { name: 'Tuvalu', code: 'TV', passportRank: 81, passportstrength: 130, tieGroup: 31 },
  { name: 'Kiribati', code: 'KI', passportRank: 82, passportstrength: 129, tieGroup: 32 },
  { name: 'Taiwan', code: 'TW', passportRank: 83, passportstrength: 129, tieGroup: 32 },
  { name: 'Tonga', code: 'TO', passportRank: 84, passportstrength: 128, tieGroup: 33 },
  { name: 'Marshall Islands', code: 'MH', passportRank: 85, passportstrength: 126, tieGroup: 34 },
  { name: 'Nicaragua', code: 'NI', passportRank: 86, passportstrength: 126, tieGroup: 34 },
  { name: 'Venezuela', code: 'VE', passportRank: 87, passportstrength: 126, tieGroup: 34 },
  { name: 'Moldova', code: 'MD', passportRank: 88, passportstrength: 125, tieGroup: 35 },
  { name: 'Russia', code: 'RU', passportRank: 89, passportstrength: 125, tieGroup: 35 },
  { name: 'Bosnia and Herzegovina', code: 'BA', passportRank: 90, passportstrength: 124, tieGroup: 36 },
  { name: 'Turkey', code: 'TR', passportRank: 91, passportstrength: 124, tieGroup: 36 },
  { name: 'Palau', code: 'PW', passportRank: 92, passportstrength: 123, tieGroup: 37 },
  { name: 'Albania', code: 'AL', passportRank: 93, passportstrength: 122, tieGroup: 38 },
  { name: 'Micronesia', code: 'FM', passportRank: 94, passportstrength: 121, tieGroup: 39 },
  { name: 'Qatar', code: 'QA', passportRank: 95, passportstrength: 119, tieGroup: 40 },
  { name: 'Kuwait', code: 'KW', passportRank: 96, passportstrength: 111, tieGroup: 41 },
  { name: 'South Africa', code: 'ZA', passportRank: 97, passportstrength: 110, tieGroup: 42 },
  { name: 'Ecuador', code: 'EC', passportRank: 98, passportstrength: 104, tieGroup: 43 },
  { name: 'East Timor', code: 'TL', passportRank: 99, passportstrength: 103, tieGroup: 44 },
  { name: 'Belize', code: 'BZ', passportRank: 100, passportstrength: 102, tieGroup: 45 },
  { name: 'Maldives', code: 'MV', passportRank: 101, passportstrength: 102, tieGroup: 45 },
  { name: 'Saudi Arabia', code: 'SA', passportRank: 102, passportstrength: 102, tieGroup: 45 },
  { name: 'Bahrain', code: 'BH', passportRank: 103, passportstrength: 101, tieGroup: 46 },
  { name: 'Jamaica', code: 'JM', passportRank: 104, passportstrength: 100, tieGroup: 47 },
  { name: 'Fiji', code: 'FJ', passportRank: 105, passportstrength: 98, tieGroup: 48 },
  { name: 'Guyana', code: 'GY', passportRank: 106, passportstrength: 98, tieGroup: 48 },
  { name: 'Oman', code: 'OM', passportRank: 107, passportstrength: 97, tieGroup: 49 },
  { name: 'Thailand', code: 'TH', passportRank: 108, passportstrength: 96, tieGroup: 50 },
  { name: 'Vanuatu', code: 'VU', passportRank: 109, passportstrength: 96, tieGroup: 50 },
  { name: 'Kazakhstan', code: 'KZ', passportRank: 110, passportstrength: 95, tieGroup: 51 },
  { name: 'Belarus', code: 'BY', passportRank: 111, passportstrength: 94, tieGroup: 52 },
  { name: 'China', code: 'CN', passportRank: 112, passportstrength: 93, tieGroup: 53 },
  { name: 'Kosovo', code: 'XK', passportRank: 113, passportstrength: 93, tieGroup: 53 },
  { name: 'Indonesia', code: 'ID', passportRank: 114, passportstrength: 92, tieGroup: 54 },
  { name: 'Nauru', code: 'NR', passportRank: 115, passportstrength: 90, tieGroup: 55 },
  { name: 'Bolivia', code: 'BO', passportRank: 116, passportstrength: 89, tieGroup: 56 },
  { name: 'Suriname', code: 'SR', passportRank: 117, passportstrength: 89, tieGroup: 56 },
  { name: 'Papua New Guinea', code: 'PG', passportRank: 118, passportstrength: 88, tieGroup: 57 },
  { name: 'Azerbaijan', code: 'AZ', passportRank: 119, passportstrength: 87, tieGroup: 58 },
  { name: 'Botswana', code: 'BW', passportRank: 120, passportstrength: 85, tieGroup: 59 },
  { name: 'Dominican Republic', code: 'DO', passportRank: 121, passportstrength: 85, tieGroup: 59 },
  { name: 'Morocco', code: 'MA', passportRank: 122, passportstrength: 85, tieGroup: 59 },
  { name: 'Lesotho', code: 'LS', passportRank: 123, passportstrength: 82, tieGroup: 60 },
  { name: 'Armenia', code: 'AM', passportRank: 124, passportstrength: 81, tieGroup: 61 },
  { name: 'Eswatini', code: 'SZ', passportRank: 125, passportstrength: 81, tieGroup: 61 },
  { name: 'Malawi', code: 'MW', passportRank: 126, passportstrength: 80, tieGroup: 62 },
  { name: 'Namibia', code: 'NA', passportRank: 127, passportstrength: 80, tieGroup: 62 },
  { name: 'Kenya', code: 'KE', passportRank: 128, passportstrength: 78, tieGroup: 63 },
  { name: 'Mongolia', code: 'MN', passportRank: 129, passportstrength: 78, tieGroup: 63 },
  { name: 'Philippines', code: 'PH', passportRank: 130, passportstrength: 78, tieGroup: 63 },
  { name: 'Tunisia', code: 'TN', passportRank: 131, passportstrength: 78, tieGroup: 63 },
  { name: 'Tanzania', code: 'TZ', passportRank: 132, passportstrength: 76, tieGroup: 64 },
  { name: 'Uzbekistan', code: 'UZ', passportRank: 133, passportstrength: 76, tieGroup: 64 },
  { name: 'Zambia', code: 'ZM', passportRank: 134, passportstrength: 76, tieGroup: 64 },
  { name: 'Cape Verde', code: 'CV', passportRank: 135, passportstrength: 75, tieGroup: 65 },
  { name: 'Cuba', code: 'CU', passportRank: 136, passportstrength: 75, tieGroup: 65 },
  { name: 'Ghana', code: 'GH', passportRank: 137, passportstrength: 75, tieGroup: 65 },
  { name: 'Kyrgyzstan', code: 'KG', passportRank: 138, passportstrength: 75, tieGroup: 65 },
  { name: 'Gambia', code: 'GM', passportRank: 139, passportstrength: 74, tieGroup: 66 },
  { name: 'India', code: 'IN', passportRank: 140, passportstrength: 74, tieGroup: 66 },
  { name: 'Rwanda', code: 'RW', passportRank: 141, passportstrength: 73, tieGroup: 67 },
  { name: 'Uganda', code: 'UG', passportRank: 142, passportstrength: 73, tieGroup: 67 },
  { name: 'Sao Tome and Principe', code: 'ST', passportRank: 143, passportstrength: 72, tieGroup: 68 },
  { name: 'Tajikistan', code: 'TJ', passportRank: 144, passportstrength: 72, tieGroup: 68 },
  { name: 'Zimbabwe', code: 'ZW', passportRank: 145, passportstrength: 72, tieGroup: 68 },
  { name: 'Benin', code: 'BJ', passportRank: 146, passportstrength: 70, tieGroup: 69 },
  { name: 'Madagascar', code: 'MG', passportRank: 147, passportstrength: 70, tieGroup: 69 },
  { name: 'Vietnam', code: 'VN', passportRank: 148, passportstrength: 70, tieGroup: 69 },
  { name: 'Algeria', code: 'DZ', passportRank: 149, passportstrength: 69, tieGroup: 70 },
  { name: 'Cambodia', code: 'KH', passportRank: 150, passportstrength: 69, tieGroup: 70 },
  { name: 'Gabon', code: 'GA', passportRank: 151, passportstrength: 69, tieGroup: 70 },
  { name: 'Mozambique', code: 'MZ', passportRank: 152, passportstrength: 68, tieGroup: 71 },
  { name: 'Senegal', code: 'SN', passportRank: 153, passportstrength: 68, tieGroup: 71 },
  { name: 'Sierra Leone', code: 'SL', passportRank: 154, passportstrength: 68, tieGroup: 71 },
  { name: 'Bhutan', code: 'BT', passportRank: 155, passportstrength: 67, tieGroup: 72 },
  { name: 'Togo', code: 'TG', passportRank: 156, passportstrength: 67, tieGroup: 72 },
  { name: 'Burkina Faso', code: 'BF', passportRank: 157, passportstrength: 66, tieGroup: 73 },
  { name: 'Equatorial Guinea', code: 'GQ', passportRank: 158, passportstrength: 66, tieGroup: 73 },
  { name: 'Ivory Coast', code: 'ivory-coast', passportRank: 159, passportstrength: 65, tieGroup: 74 },
  { name: 'Egypt', code: 'EG', passportRank: 160, passportstrength: 65, tieGroup: 74 },
  { name: 'Jordan', code: 'JO', passportRank: 161, passportstrength: 65, tieGroup: 74 },
  { name: 'Turkmenistan', code: 'TM', passportRank: 162, passportstrength: 65, tieGroup: 74 },
  { name: 'Angola', code: 'AO', passportRank: 163, passportstrength: 64, tieGroup: 75 },
  { name: 'Niger', code: 'NE', passportRank: 164, passportstrength: 64, tieGroup: 75 },
  { name: 'Comoros', code: 'KM', passportRank: 165, passportstrength: 63, tieGroup: 76 },
  { name: 'Guinea', code: 'GN', passportRank: 166, passportstrength: 63, tieGroup: 76 },
  { name: 'Laos', code: 'LA', passportRank: 167, passportstrength: 63, tieGroup: 76 },
  { name: 'Haiti', code: 'HT', passportRank: 168, passportstrength: 62, tieGroup: 77 },
  { name: 'Central African Republic', code: 'CF', passportRank: 169, passportstrength: 61, tieGroup: 78 },
  { name: 'Djibouti', code: 'DJ', passportRank: 170, passportstrength: 61, tieGroup: 78 },
  { name: 'Mali', code: 'ML', passportRank: 171, passportstrength: 61, tieGroup: 78 },
  { name: 'Cameroon', code: 'CM', passportRank: 172, passportstrength: 60, tieGroup: 79 },
  { name: 'Chad', code: 'TD', passportRank: 173, passportstrength: 60, tieGroup: 79 },
  { name: 'Guinea-Bissau', code: 'GW', passportRank: 174, passportstrength: 60, tieGroup: 79 },
  { name: 'Liberia', code: 'LR', passportRank: 175, passportstrength: 59, tieGroup: 80 },
  { name: 'Burundi', code: 'BI', passportRank: 176, passportstrength: 58, tieGroup: 81 },
  { name: 'Lebanon', code: 'LB', passportRank: 177, passportstrength: 58, tieGroup: 81 },
  { name: 'Myanmar', code: 'MM', passportRank: 178, passportstrength: 58, tieGroup: 81 },
  { name: 'Republic of the Congo', code: 'CG', passportRank: 179, passportstrength: 57, tieGroup: 82 },
  { name: 'Sri Lanka', code: 'LK', passportRank: 180, passportstrength: 57, tieGroup: 82 },
  { name: 'Ethiopia', code: 'ET', passportRank: 181, passportstrength: 55, tieGroup: 83 },
  { name: 'Iran', code: 'IR', passportRank: 182, passportstrength: 55, tieGroup: 83 },
  { name: 'DR Congo', code: 'CD', passportRank: 183, passportstrength: 54, tieGroup: 84 },
  { name: 'Nepal', code: 'NP', passportRank: 184, passportstrength: 54, tieGroup: 84 },
  { name: 'Nigeria', code: 'NG', passportRank: 185, passportstrength: 54, tieGroup: 84 },
  { name: 'Libya', code: 'LY', passportRank: 186, passportstrength: 53, tieGroup: 85 },
  { name: 'South Sudan', code: 'SS', passportRank: 187, passportstrength: 53, tieGroup: 85 },
  { name: 'Sudan', code: 'SD', passportRank: 188, passportstrength: 53, tieGroup: 85 },
  { name: 'Eritrea', code: 'ER', passportRank: 189, passportstrength: 51, tieGroup: 86 },
  { name: 'North Korea', code: 'KP', passportRank: 190, passportstrength: 51, tieGroup: 86 },
  { name: 'Bangladesh', code: 'BD', passportRank: 191, passportstrength: 50, tieGroup: 87 },
  { name: 'Palestine', code: 'PS', passportRank: 192, passportstrength: 50, tieGroup: 87 },
  { name: 'Yemen', code: 'YE', passportRank: 193, passportstrength: 46, tieGroup: 88 },
  { name: 'Pakistan', code: 'PK', passportRank: 194, passportstrength: 45, tieGroup: 89 },
  { name: 'Somalia', code: 'SO', passportRank: 195, passportstrength: 45, tieGroup: 89 },
  { name: 'Iraq', code: 'IQ', passportRank: 196, passportstrength: 44, tieGroup: 90 },
  { name: 'Syria', code: 'SY', passportRank: 197, passportstrength: 39, tieGroup: 91 },
  { name: 'Afghanistan', code: 'AF', passportRank: 198, passportstrength: 38, tieGroup: 92 }
];