export const poorestgdpData = [
  { name: 'South Sudan', code: 'SS', rank: 1, gdpPerCapita: 251 },
  { name: 'Yemen', code: 'YE', rank: 2, gdpPerCapita: 417 },
  { name: 'Burundi', code: 'BI', rank: 3, gdpPerCapita: 490 },
  { name: 'Central African Republic', code: 'CF', rank: 4, gdpPerCapita: 532 },
  { name: 'Malawi', code: 'MW', rank: 5, gdpPerCapita: 580 },
  { name: 'Madagascar', code: 'MG', rank: 6, gdpPerCapita: 595 },
  { name: 'Sudan', code: 'SD', rank: 7, gdpPerCapita: 625 },
  { name: 'Mozambique', code: 'MZ', rank: 8, gdpPerCapita: 663 },
  { name: 'Democratic Republic of the Congo', code: 'CD', rank: 9, gdpPerCapita: 743 },
  { name: 'Niger', code: 'NE', rank: 10, gdpPerCapita: 751 },
  { name: 'Somalia', code: 'SO', rank: 11, gdpPerCapita: 766 },
  { name: 'Nigeria', code: 'NG', rank: 12, gdpPerCapita: 807 },
  { name: 'Liberia', code: 'LR', rank: 13, gdpPerCapita: 908 },
  { name: 'Sierra Leone', code: 'SL', rank: 14, gdpPerCapita: 916 },
  { name: 'Mali', code: 'ML', rank: 15, gdpPerCapita: 936 },
  { name: 'Gambia', code: 'GM', rank: 16, gdpPerCapita: 988 },
  { name: 'Chad', code: 'TD', rank: 17, gdpPerCapita: 991 },
  { name: 'Rwanda', code: 'RW', rank: 18, gdpPerCapita: 1043 },
  { name: 'Togo', code: 'TG', rank: 19, gdpPerCapita: 1053 },
  { name: 'Ethiopia', code: 'ET', rank: 20, gdpPerCapita: 1066 },
  { name: 'Lesotho', code: 'LS', rank: 21, gdpPerCapita: 1098 },
  { name: 'Burkina Faso', code: 'BF', rank: 22, gdpPerCapita: 1107 },
  { name: 'Guinea-Bissau', code: 'GW', rank: 23, gdpPerCapita: 1126 },
  { name: 'Myanmar', code: 'MM', rank: 24, gdpPerCapita: 1177 },
  { name: 'Tanzania', code: 'TZ', rank: 25, gdpPerCapita: 1280 },
];
