export const precipitationData = [
  { name: 'Micronesia', code: 'micronesia', precipitationRank: 1, precipitation: 4128 },
  { name: 'Palau', code: 'palau', precipitationRank: 2, precipitation: 3711 },
  { name: 'Fiji', code: 'fiji', precipitationRank: 3, precipitation: 3349 },
  { name: 'Costa Rica', code: 'costa-rica', precipitationRank: 4, precipitation: 3300 },
  { name: 'Papua New Guinea', code: 'papua-new-guinea', precipitationRank: 5, precipitation: 3185 },
  { name: 'Malaysia', code: 'malaysia', precipitationRank: 6, precipitation: 3124 },
  { name: 'Indonesia', code: 'indonesia', precipitationRank: 7, precipitation: 2998 },
  { name: 'Belize', code: 'belize', precipitationRank: 8, precipitation: 2886 },
  { name: 'Vanuatu', code: 'vanuatu', precipitationRank: 9, precipitation: 2826 },
  { name: 'Philippines', code: 'philippines', precipitationRank: 10, precipitation: 2768 },
  { name: 'Colombia', code: 'colombia', precipitationRank: 11, precipitation: 2561 },
  { name: 'Maldives', code: 'maldives', precipitationRank: 12, precipitation: 2495 },
  { name: 'Jamaica', code: 'jamaica', precipitationRank: 13, precipitation: 2395 },
  { name: 'Equatorial Guinea', code: 'equatorial-guinea', precipitationRank: 14, precipitation: 2179 },
  { name: 'Bangladesh', code: 'bangladesh', precipitationRank: 15, precipitation: 2021 },
  { name: 'Suriname', code: 'suriname', precipitationRank: 16, precipitation: 2013 },
  { name: 'Myanmar', code: 'myanmar', precipitationRank: 17, precipitation: 2009 },
  { name: 'Mauritius', code: 'mauritius', precipitationRank: 18, precipitation: 1993 },
  { name: 'Laos', code: 'laos', precipitationRank: 19, precipitation: 1894 },
  { name: 'Venezuela', code: 'venezuela', precipitationRank: 20, precipitation: 1881 },
  { name: 'Sri Lanka', code: 'sri-lanka', precipitationRank: 21, precipitation: 1859 },
  { name: 'Vietnam', code: 'vietnam', precipitationRank: 22, precipitation: 1799 },
  { name: 'Japan', code: 'japan', precipitationRank: 23, precipitation: 1792 },
  { name: 'El Salvador', code: 'el-salvador', precipitationRank: 24, precipitation: 1764 },
  { name: 'Gabon', code: 'gabon', precipitationRank: 25, precipitation: 1741 },
  { name: 'Trinidad and Tobago', code: 'trinidad-and-tobago', precipitationRank: 26, precipitation: 1705 },
  { name: 'Cameroon', code: 'cameroon', precipitationRank: 27, precipitation: 1605 },
  { name: 'Barbados', code: 'barbados', precipitationRank: 28, precipitation: 1516 },
  { name: 'Slovenia', code: 'slovenia', precipitationRank: 29, precipitation: 1484 },
  { name: 'Kiribati', code: 'kiribati', precipitationRank: 30, precipitation: 1424 },
  { name: 'Peru', code: 'peru', precipitationRank: 31, precipitation: 1409 },
  { name: 'Switzerland', code: 'switzerland', precipitationRank: 32, precipitation: 1362 },
  { name: 'South Korea', code: 'south-korea', precipitationRank: 33, precipitation: 1350 },
  { name: 'United Kingdom', code: 'united-kingdom', precipitationRank: 34, precipitation: 1275 },
  { name: 'India', code: 'india', precipitationRank: 35, precipitation: 1254 },
  { name: 'Antigua and Barbuda', code: 'antigua-and-barbuda', precipitationRank: 36, precipitation: 1246 },
  { name: 'Ivory Coast', code: 'ivory-coast', precipitationRank: 37, precipitation: 1239 },
  { name: 'Georgia', code: 'georgia', precipitationRank: 38, precipitation: 1227 },
  { name: 'Ghana', code: 'ghana', precipitationRank: 39, precipitation: 1181 },
  { name: 'Ireland', code: 'ireland', precipitationRank: 40, precipitation: 1172 },
  { name: 'Andorra', code: 'andorra', precipitationRank: 41, precipitation: 1166 },
  { name: 'Belgium', code: 'belgium', precipitationRank: 42, precipitation: 1143 },
  { name: 'Iceland', code: 'iceland', precipitationRank: 43, precipitation: 1133 },
  { name: 'Albania', code: 'albania', precipitationRank: 44, precipitation: 1085 },
  { name: 'Paraguay', code: 'paraguay', precipitationRank: 45, precipitation: 1062 },
  { name: 'North Korea', code: 'north-korea', precipitationRank: 46, precipitation: 1047 },
  { name: 'Angola', code: 'angola', precipitationRank: 47, precipitation: 1028 }
];
