export const renewableShareData = [
  { name: 'China', code: 'CN', renewableRank: 1, sharepercent: 31.4 },
  { name: 'United States', code: 'US', renewableRank: 2, sharepercent: 10.9 },
  { name: 'Brazil', code: 'BR', renewableRank: 3, sharepercent: 6.3 },
  { name: 'India', code: 'IN', renewableRank: 4, sharepercent: 3.6 },
  { name: 'Canada', code: 'CA', renewableRank: 5, sharepercent: 3.5 },
  { name: 'Germany', code: 'DE', renewableRank: 6, sharepercent: 3.2 },
  { name: 'Japan', code: 'JP', renewableRank: 7, sharepercent: 2.9 },
  { name: 'Indonesia', code: 'ID', renewableRank: 8, sharepercent: 2.4 },
  { name: 'Turkey', code: 'TR', renewableRank: 9, sharepercent: 2.3 },
  { name: 'United Kingdom', code: 'GB', renewableRank: 10, sharepercent: 1.9 },
  { name: 'Russia', code: 'RU', renewableRank: 11, sharepercent: 1.8 },
  { name: 'Italy', code: 'IT', renewableRank: 12, sharepercent: 1.7 },
  { name: 'Spain', code: 'ES', renewableRank: 13, sharepercent: 1.5 },
  { name: 'France', code: 'FR', renewableRank: 14, sharepercent: 1.4 },
  { name: 'Norway', code: 'NO', renewableRank: 15, sharepercent: 1.3 },
  { name: 'Sweden', code: 'SE', renewableRank: 16, sharepercent: 1.2 },
  { name: 'Vietnam', code: 'VN', renewableRank: 17, sharepercent: 1.1 },
  { name: 'New Zealand', code: 'NZ', renewableRank: 18, sharepercent: 1.0 },
  { name: 'Mexico', code: 'MX', renewableRank: 19, sharepercent: 0.9 },
  { name: 'South Korea', code: 'KR', renewableRank: 20, sharepercent: 0.8 },
  { name: 'Chile', code: 'CL', renewableRank: 21, sharepercent: 0.7 },
  { name: 'Venezuela', code: 'VE', renewableRank: 22, sharepercent: 0.6 },
  { name: 'Switzerland', code: 'CH', renewableRank: 23, sharepercent: 0.5 },
  { name: 'Portugal', code: 'PT', renewableRank: 24, sharepercent: 0.4 },
  { name: 'Denmark', code: 'DK', renewableRank: 25, sharepercent: 0.3 },
  { name: 'Ecuador', code: 'EC', renewableRank: 26, sharepercent: 0.2 },
  { name: 'Uzbekistan', code: 'UZ', renewableRank: 27, sharepercent: 0.1 },
];
