export const sexratioData = [
  { name: 'Qatar', code: 'QA', sexRatioRank: 1, sexRatio: 266 },
  { name: 'United Arab Emirates', code: 'AE', sexRatioRank: 2, sexRatio: 228 },
  { name: 'Bahrain', code: 'BH', sexRatioRank: 3, sexRatio: 164 },
  { name: 'Oman', code: 'OM', sexRatioRank: 4, sexRatio: 157 },
  { name: 'Kuwait', code: 'KW', sexRatioRank: 5, sexRatio: 156 },
  { name: 'Saudi Arabia', code: 'SA', sexRatioRank: 6, sexRatio: 137 },
  { name: 'Greenland', code: 'GL', sexRatioRank: 7, sexRatio: 111 },
  { name: 'India', code: 'IN', sexRatioRank: 8, sexRatio: 107 },
  { name: 'Iceland', code: 'IS', sexRatioRank: 9, sexRatio: 105 },
  { name: 'China', code: 'CN', sexRatioRank: 10, sexRatio: 104 },
  { name: 'Nigeria', code: 'NG', sexRatioRank: 11, sexRatio: 102 },
  { name: 'Egypt', code: 'EG', sexRatioRank: 12, sexRatio: 102 },
  { name: 'Bolivia', code: 'BO', sexRatioRank: 13, sexRatio: 101 },
  { name: 'Australia', code: 'AU', sexRatioRank: 14, sexRatio: 99 },
  { name: 'Canada', code: 'CA', sexRatioRank: 15, sexRatio: 99 },
  { name: 'United States', code: 'US', sexRatioRank: 16, sexRatio: 98 },
  { name: 'Uganda', code: 'UG', sexRatioRank: 17, sexRatio: 98 },
  { name: 'Brazil', code: 'BR', sexRatioRank: 18, sexRatio: 97 },
  { name: 'Japan', code: 'JP', sexRatioRank: 19, sexRatio: 95 },
  { name: 'Poland', code: 'PL', sexRatioRank: 20, sexRatio: 94 },
  { name: 'Kazakhstan', code: 'KZ', sexRatioRank: 21, sexRatio: 93 },
  { name: 'Portugal', code: 'PT', sexRatioRank: 22, sexRatio: 89 },
  { name: 'Zimbabwe', code: 'ZW', sexRatioRank: 23, sexRatio: 89 },
  { name: 'Russia', code: 'RU', sexRatioRank: 24, sexRatio: 87 },
  { name: 'Armenia', code: 'AM', sexRatioRank: 25, sexRatio: 82 },
];