export const tallestbuildingData = [
  { name: 'United Arab Emirates', code: 'AE', tallestBuildingRank: 1, tallestBuilding: 828, height: 828, tallestBuildingName: 'Burj Khalifa' },
  { name: 'China', code: 'CN', tallestBuildingRank: 2, tallestBuilding: 632, height: 632, tallestBuildingName: 'Shanghai Tower' },
  { name: 'Saudi Arabia', code: 'SA', tallestBuildingRank: 3, tallestBuilding: 601, height: 601, tallestBuildingName: 'Makkah Royal Clock Tower Hotel' },
  { name: 'South Korea', code: 'KR', tallestBuildingRank: 4, tallestBuilding: 555.7, height: 555.7, tallestBuildingName: 'Lotte World Tower' },
  { name: 'United States', code: 'US', tallestBuildingRank: 5, tallestBuilding: 541.3, height: 541.3, tallestBuildingName: 'One World Trade Center' },
  { name: 'Taiwan', code: 'TW', tallestBuildingRank: 6, tallestBuilding: 508, height: 508, tallestBuildingName: 'Taipei 101' },
  { name: 'Hong Kong', code: 'HK', tallestBuildingRank: 7, tallestBuilding: 484, height: 484, tallestBuildingName: 'International Commerce Centre' },
  { name: 'Russia', code: 'RU', tallestBuildingRank: 8, tallestBuilding: 462, height: 462, tallestBuildingName: 'Lakhta Center' },
  { name: 'Vietnam', code: 'VN', tallestBuildingRank: 9, tallestBuilding: 461.2, height: 461.2, tallestBuildingName: 'Landmark 81' },
  { name: 'Malaysia', code: 'MY', tallestBuildingRank: 10, tallestBuilding: 451.9, height: 451.9, tallestBuildingName: 'Petronas Towers' },
  { name: 'Kuwait', code: 'KW', tallestBuildingRank: 11, tallestBuilding: 412.6, height: 412.6, tallestBuildingName: 'Al Hamra Tower' },
  { name: 'North Korea', code: 'KP', tallestBuildingRank: 12, tallestBuilding: 330, height: 330, tallestBuildingName: 'Ryugyong Hotel' },
  { name: 'Australia', code: 'AU', tallestBuildingRank: 13, tallestBuilding: 322.5, height: 322.5, tallestBuildingName: 'Q1' },
  { name: 'India', code: 'IN', tallestBuildingRank: 14, tallestBuilding: 320, height: 320, tallestBuildingName: 'Palais Royale' },
  { name: 'Philippines', code: 'PH', tallestBuildingRank: 15, tallestBuilding: 318, height: 318, tallestBuildingName: 'Grand Hyatt Manila' },
  { name: 'Thailand', code: 'TH', tallestBuildingRank: 16, tallestBuilding: 317, height: 317, tallestBuildingName: 'Iconsiam' },
  { name: 'United Kingdom', code: 'GB', tallestBuildingRank: 17, tallestBuilding: 309.7, height: 309.7, tallestBuildingName: 'Shard, The' },
  { name: 'Mexico', code: 'MX', tallestBuildingRank: 18, tallestBuilding: 305.3, height: 305.3, tallestBuildingName: 'T.Op Torre 1' },
  { name: 'Germany', code: 'DE', tallestBuildingRank: 19, tallestBuilding: 300.1, height: 300.1, tallestBuildingName: 'Commerzbank Tower' },
  { name: 'Japan', code: 'JP', tallestBuildingRank: 20, tallestBuilding: 300, height: 300, tallestBuildingName: 'Abeno Harukas' },
  { name: 'Chile', code: 'CL', tallestBuildingRank: 21, tallestBuilding: 300, height: 300, tallestBuildingName: 'Gran Torre Costanera' },
  { name: 'Qatar', code: 'QA', tallestBuildingRank: 22, tallestBuilding: 300, height: 300, tallestBuildingName: 'Aspire Tower' },
  { name: 'Canada', code: 'CA', tallestBuildingRank: 23, tallestBuilding: 298.1, height: 298.1, tallestBuildingName: 'First Canadian Place' },
  { name: 'Turkey', code: 'TR', tallestBuildingRank: 24, tallestBuilding: 293, height: 293, tallestBuildingName: 'Skyland Istanbul' },
  { name: 'Singapore', code: 'SG', tallestBuildingRank: 25, tallestBuilding: 290, height: 290, tallestBuildingName: 'Tanjong Pagar Centre' },
  { name: 'Indonesia', code: 'ID', tallestBuildingRank: 26, tallestBuilding: 288.6, height: 288.6, tallestBuildingName: 'Gama Tower' },
  { name: 'Panama', code: 'PA', tallestBuildingRank: 27, tallestBuilding: 284, height: 284, tallestBuildingName: 'JW Marriott Panama' },
  { name: 'Brazil', code: 'BR', tallestBuildingRank: 28, tallestBuilding: 281, height: 281, tallestBuildingName: 'Yachthouse Residence Club – Towers 1 and 2' },
  { name: 'Pakistan', code: 'PK', tallestBuildingRank: 29, tallestBuilding: 273, height: 273, tallestBuildingName: 'Bahria Icon Tower' },
  { name: 'Algeria', code: 'DZ', tallestBuildingRank: 30, tallestBuilding: 270, height: 270, tallestBuildingName: 'Djamaâ El Djazaïr' },
  { name: 'Bahrain', code: 'BH', tallestBuildingRank: 31, tallestBuilding: 269.7, height: 269.7, tallestBuildingName: 'Four Seasons Hotel' },
  { name: 'Venezuela', code: 'VE', tallestBuildingRank: 32, tallestBuilding: 262.5, height: 262.5, tallestBuildingName: 'Parque Central Torre Este' },
  { name: 'Spain', code: 'ES', tallestBuildingRank: 33, tallestBuilding: 249, height: 249, tallestBuildingName: 'Torre de Cristal' },
  { name: 'Sri Lanka', code: 'LK', tallestBuildingRank: 34, tallestBuilding: 240, height: 240, tallestBuildingName: 'Altair' },
  { name: 'Israel', code: 'IL', tallestBuildingRank: 35, tallestBuilding: 238.5, height: 238.5, tallestBuildingName: 'Azrieli Sarona Tower' },
  { name: 'Argentina', code: 'AR', tallestBuildingRank: 36, tallestBuilding: 235, height: 235, tallestBuildingName: 'Alvear Tower' },
  { name: 'South Africa', code: 'ZA', tallestBuildingRank: 37, tallestBuilding: 234, height: 234, tallestBuildingName: 'Leonardo, The' },
  { name: 'France', code: 'FR', tallestBuildingRank: 38, tallestBuilding: 231, height: 231, tallestBuildingName: 'Tour First' },
  { name: 'Italy', code: 'IT', tallestBuildingRank: 39, tallestBuilding: 231, height: 231, tallestBuildingName: 'Unicredit Tower' },
  { name: 'Austria', code: 'AT', tallestBuildingRank: 40, tallestBuilding: 220, height: 220, tallestBuildingName: 'DC Tower 1' },
  { name: 'Colombia', code: 'CO', tallestBuildingRank: 41, tallestBuilding: 216, height: 216, tallestBuildingName: 'BD Bacatá Torre Sur' },
  { name: 'Morocco', code: 'MA', tallestBuildingRank: 42, tallestBuilding: 210, height: 210, tallestBuildingName: 'Hassan II Mosque' },
  { name: 'Kazakhstan', code: 'KZ', tallestBuildingRank: 43, tallestBuilding: 210, height: 210, tallestBuildingName: 'Emerald Towers 1' },
  { name: 'Azerbaijan', code: 'AZ', tallestBuildingRank: 44, tallestBuilding: 210, height: 210, tallestBuildingName: 'Crescent City, The' },
  { name: 'Kenya', code: 'KE', tallestBuildingRank: 45, tallestBuilding: 200, height: 200, tallestBuildingName: 'Britam Tower' },
  { name: 'Georgia', code: 'GE', tallestBuildingRank: 46, tallestBuilding: 200, height: 200, tallestBuildingName: 'Batumi Technological University Tower' }
];