export const temperatureData = [
  { name: 'United Arab Emirates', code: 'united-arab-emirates', temperatureRank: 1, temperature: 28.9 },
  { name: 'Djibouti', code: 'djibouti', temperatureRank: 2, temperature: 28.6 },
  { name: 'Gambia', code: 'gambia', temperatureRank: 3, temperature: 28.5 },
  { name: 'Maldives', code: 'maldives', temperatureRank: 4, temperature: 28.1 },
  { name: 'Guinea-Bissau', code: 'guinea-bissau', temperatureRank: 5, temperature: 28.1 },
  { name: 'Singapore', code: 'singapore', temperatureRank: 6, temperature: 27.7 },
  { name: 'Saint Kitts & Nevis', code: 'saint-kitts-and-nevis', temperatureRank: 7, temperature: 27.3 },
  { name: 'Thailand', code: 'thailand', temperatureRank: 8, temperature: 26.8 },
  { name: 'Bahamas', code: 'bahamas', temperatureRank: 9, temperature: 26.1 },
  { name: 'Bangladesh', code: 'bangladesh', temperatureRank: 10, temperature: 25.7 },
  { name: 'India', code: 'india', temperatureRank: 11, temperature: 25.2 },
  { name: 'Papua New Guinea', code: 'papua-new-guinea', temperatureRank: 12, temperature: 24.8 },
  { name: 'DR Congo', code: 'democratic-republic-of-the-congo', temperatureRank: 13, temperature: 24.4 },
  { name: 'Myanmar', code: 'myanmar', temperatureRank: 14, temperature: 24.0 },
  { name: 'Ethiopia', code: 'ethiopia', temperatureRank: 15, temperature: 23.5 },
  { name: 'Libya', code: 'libya', temperatureRank: 16, temperature: 22.8 },
  { name: 'Australia', code: 'australia', temperatureRank: 17, temperature: 22.0 },
  { name: 'Ecuador', code: 'ecuador', temperatureRank: 18, temperature: 21.1 },
  { name: 'Malta', code: 'malta', temperatureRank: 19, temperature: 20.3 },
  { name: 'Jordan', code: 'jordan', temperatureRank: 20, temperature: 19.8 },
  { name: 'Morocco', code: 'morocco', temperatureRank: 21, temperature: 19.1 },
  { name: 'South Africa', code: 'south-africa', temperatureRank: 22, temperature: 18.4 },
  { name: 'Uruguay', code: 'uruguay', temperatureRank: 23, temperature: 17.7 },
  { name: 'Portugal', code: 'portugal', temperatureRank: 24, temperature: 16.9 },
  { name: 'Lebanon', code: 'lebanon', temperatureRank: 25, temperature: 15.7 },
  { name: 'Argentina', code: 'argentina', temperatureRank: 26, temperature: 15.1 },
  { name: 'Italy', code: 'italy', temperatureRank: 27, temperature: 14.4 },
  { name: 'France', code: 'france', temperatureRank: 28, temperature: 13.2 },
  { name: 'South Korea', code: 'south-korea', temperatureRank: 29, temperature: 12.8 },
  { name: 'Belgium', code: 'belgium', temperatureRank: 30, temperature: 12.0 },
  { name: 'Luxembourg', code: 'luxembourg', temperatureRank: 31, temperature: 11.4 },
  { name: 'Germany', code: 'germany', temperatureRank: 32, temperature: 10.8 },
  { name: 'United Kingdom', code: 'united-kingdom', temperatureRank: 33, temperature: 10.1 },
  { name: 'Chile', code: 'chile', temperatureRank: 34, temperature: 9.4 },
  { name: 'Armenia', code: 'armenia', temperatureRank: 35, temperature: 8.6 },
  { name: 'China', code: 'china', temperatureRank: 36, temperature: 8.1 },
  { name: 'North Korea', code: 'north-korea', temperatureRank: 37, temperature: 7.5 },
  { name: 'Estonia', code: 'estonia', temperatureRank: 38, temperature: 6.9 },
  { name: 'Tajikistan', code: 'tajikistan', temperatureRank: 39, temperature: 5.1 },
  { name: 'Sweden', code: 'sweden', temperatureRank: 40, temperature: 3.8 },
  { name: 'Finland', code: 'finland', temperatureRank: 41, temperature: 3.2 },
  { name: 'Norway', code: 'norway', temperatureRank: 42, temperature: 2.9 },
  { name: 'Iceland', code: 'iceland', temperatureRank: 43, temperature: 2.1 },
  { name: 'Mongolia', code: 'mongolia', temperatureRank: 44, temperature: 1.3 },
  { name: 'Russia', code: 'russia', temperatureRank: 45, temperature: -2.9 },
  { name: 'Canada', code: 'canada', temperatureRank: 46, temperature: -4.2 },
  { name: 'Greenland', code: 'greenland', temperatureRank: 47, temperature: -18.6 },
];
