export const temperatureData = [
  { name: 'United Arab Emirates', code: 'AE', temperatureRank: 1, temperature: 28.9 },
  { name: 'Djibouti', code: 'DJ', temperatureRank: 2, temperature: 28.6 },
  { name: 'Gambia', code: 'GM', temperatureRank: 3, temperature: 28.5 },
  { name: 'Maldives', code: 'MV', temperatureRank: 4, temperature: 28.1 },
  { name: 'Guinea-Bissau', code: 'GW', temperatureRank: 5, temperature: 28.1 },
  { name: 'Singapore', code: 'SG', temperatureRank: 6, temperature: 27.7 },
  { name: 'Saint Kitts & Nevis', code: 'KN', temperatureRank: 7, temperature: 27.3 },
  { name: 'Thailand', code: 'TH', temperatureRank: 8, temperature: 26.8 },
  { name: 'Bahamas', code: 'BS', temperatureRank: 9, temperature: 26.1 },
  { name: 'Bangladesh', code: 'BD', temperatureRank: 10, temperature: 25.7 },
  { name: 'India', code: 'IN', temperatureRank: 11, temperature: 25.2 },
  { name: 'Papua New Guinea', code: 'PG', temperatureRank: 12, temperature: 24.8 },
  { name: 'DR Congo', code: 'CD', temperatureRank: 13, temperature: 24.4 },
  { name: 'Myanmar', code: 'MM', temperatureRank: 14, temperature: 24.0 },
  { name: 'Ethiopia', code: 'ET', temperatureRank: 15, temperature: 23.5 },
  { name: 'Libya', code: 'LY', temperatureRank: 16, temperature: 22.8 },
  { name: 'Australia', code: 'AU', temperatureRank: 17, temperature: 22.0 },
  { name: 'Ecuador', code: 'EC', temperatureRank: 18, temperature: 21.1 },
  { name: 'Malta', code: 'MT', temperatureRank: 19, temperature: 20.3 },
  { name: 'Jordan', code: 'JO', temperatureRank: 20, temperature: 19.8 },
  { name: 'Morocco', code: 'MA', temperatureRank: 21, temperature: 19.1 },
  { name: 'South Africa', code: 'ZA', temperatureRank: 22, temperature: 18.4 },
  { name: 'Uruguay', code: 'UY', temperatureRank: 23, temperature: 17.7 },
  { name: 'Portugal', code: 'PT', temperatureRank: 24, temperature: 16.9 },
  { name: 'Lebanon', code: 'LB', temperatureRank: 25, temperature: 15.7 },
  { name: 'Argentina', code: 'AR', temperatureRank: 26, temperature: 15.1 },
  { name: 'Italy', code: 'IT', temperatureRank: 27, temperature: 14.4 },
  { name: 'France', code: 'FR', temperatureRank: 28, temperature: 13.2 },
  { name: 'South Korea', code: 'KR', temperatureRank: 29, temperature: 12.8 },
  { name: 'Belgium', code: 'BE', temperatureRank: 30, temperature: 12.0 },
  { name: 'Luxembourg', code: 'LU', temperatureRank: 31, temperature: 11.4 },
  { name: 'Germany', code: 'DE', temperatureRank: 32, temperature: 10.8 },
  { name: 'United Kingdom', code: 'GB', temperatureRank: 33, temperature: 10.1 },
  { name: 'Chile', code: 'CL', temperatureRank: 34, temperature: 9.4 },
  { name: 'Armenia', code: 'AM', temperatureRank: 35, temperature: 8.6 },
  { name: 'China', code: 'CN', temperatureRank: 36, temperature: 8.1 },
  { name: 'North Korea', code: 'KP', temperatureRank: 37, temperature: 7.5 },
  { name: 'Estonia', code: 'EE', temperatureRank: 38, temperature: 6.9 },
  { name: 'Tajikistan', code: 'TJ', temperatureRank: 39, temperature: 5.1 },
  { name: 'Sweden', code: 'SE', temperatureRank: 40, temperature: 3.8 },
  { name: 'Finland', code: 'FI', temperatureRank: 41, temperature: 3.2 },
  { name: 'Norway', code: 'NO', temperatureRank: 42, temperature: 2.9 },
  { name: 'Iceland', code: 'IS', temperatureRank: 43, temperature: 2.1 },
  { name: 'Mongolia', code: 'MN', temperatureRank: 44, temperature: 1.3 },
  { name: 'Russia', code: 'RU', temperatureRank: 45, temperature: -2.9 },
  { name: 'Canada', code: 'CA', temperatureRank: 46, temperature: -4.2 },
  { name: 'Greenland', code: 'GL', temperatureRank: 47, temperature: -18.6 },
];