export const universityData = [
  { name: 'India', code: 'IN', universityRank: 1, universities: 5349, university: 5349 },
  { name: 'Indonesia', code: 'ID', universityRank: 2, universities: 3277, university: 3277 },
  { name: 'United States', code: 'US', universityRank: 3, universities: 3180, university: 3180 },
  { name: 'China', code: 'CN', universityRank: 4, universities: 2495, university: 2495 },
  { name: 'Brazil', code: 'BR', universityRank: 5, universities: 1264, university: 1264 },
  { name: 'Mexico', code: 'MX', universityRank: 6, universities: 1139, university: 1139 },
  { name: 'Russia', code: 'RU', universityRank: 7, universities: 1010, university: 1010 },
  { name: 'Japan', code: 'JP', universityRank: 8, universities: 992, university: 992 },
  { name: 'France', code: 'FR', universityRank: 9, universities: 625, university: 625 },
  { name: 'Germany', code: 'DE', universityRank: 10, universities: 461, university: 461 },
  { name: 'Iran', code: 'IR', universityRank: 11, universities: 440, university: 440 },
  { name: 'Poland', code: 'PL', universityRank: 12, universities: 408, university: 408 },
  { name: 'South Korea', code: 'KR', universityRank: 13, universities: 401, university: 401 },
  { name: 'Canada', code: 'CA', universityRank: 14, universities: 383, university: 383 },
  { name: 'Philippines', code: 'PH', universityRank: 15, universities: 366, university: 366 },
  { name: 'Pakistan', code: 'PK', universityRank: 16, universities: 359, university: 359 },
  { name: 'Malaysia', code: 'MY', universityRank: 17, universities: 351, university: 351 },
  { name: 'United Kingdom', code: 'GB', universityRank: 18, universities: 337, university: 337 },
  { name: 'Ukraine', code: 'UA', universityRank: 19, universities: 300, university: 300 },
  { name: 'Colombia', code: 'CO', universityRank: 20, universities: 299, university: 299 },
  { name: 'Italy', code: 'IT', universityRank: 21, universities: 289, university: 289 },
  { name: 'Nigeria', code: 'NG', universityRank: 22, universities: 278, university: 278 },
  { name: 'Spain', code: 'ES', universityRank: 23, universities: 276, university: 276 },
  { name: 'Tunisia', code: 'TN', universityRank: 24, universities: 236, university: 236 },
  { name: 'Turkey', code: 'TR', universityRank: 25, universities: 209, university: 209 },
];
