export const universityData = [
  { name: 'United States', code: 'US', universityRank: 1, universities: 154, university: 154 },
  { name: 'United Kingdom', code: 'GB', universityRank: 2, universities: 94, university: 94 },
  { name: 'China', code: 'CN', universityRank: 3, universities: 59, university: 59 },
  { name: 'Italy', code: 'IT', universityRank: 4, universities: 49, university: 49 },
  { name: 'Australia', code: 'AU', universityRank: 5, universities: 44, university: 44 },
  { name: 'India', code: 'IN', universityRank: 6, universities: 38, university: 38 },
  { name: 'Spain', code: 'ES', universityRank: 7, universities: 36, university: 36 },
  { name: 'Japan', code: 'JP', universityRank: 8, universities: 33, university: 33 },
  { name: 'Canada', code: 'CA', universityRank: 9, universities: 32, university: 32 },
  { name: 'Iran', code: 'IR', universityRank: 10, universities: 29, university: 29 },
  { name: 'South Korea', code: 'KR', universityRank: 11, universities: 18, university: 18 },
  { name: 'Taiwan', code: 'TW', universityRank: 12, universities: 16, university: 16 },
  { name: 'Switzerland', code: 'CH', universityRank: 13, universities: 15, university: 15 },
  { name: 'Pakistan', code: 'PK', universityRank: 14, universities: 14, university: 14 },
  { name: 'Netherlands', code: 'NL', universityRank: 15, universities: 13, university: 13 },
  { name: 'Finland', code: 'FI', universityRank: 16, universities: 12, university: 12 },
  { name: 'Sweden', code: 'SE', universityRank: 17, universities: 11, university: 11 },
  { name: 'Turkey', code: 'TR', universityRank: 18, universities: 10, university: 10 },
  { name: 'South Africa', code: 'ZA', universityRank: 19, universities: 9, university: 9 },
  { name: 'United Arab Emirates', code: 'AE', universityRank: 20, universities: 8, university: 8 },
  { name: 'Austria', code: 'AT', universityRank: 21, universities: 7, university: 7 },
  { name: 'Malaysia', code: 'MY', universityRank: 22, universities: 6, university: 6 },
  { name: 'Thailand', code: 'TH', universityRank: 23, universities: 5, university: 5 },
  { name: 'Ghana', code: 'GH', universityRank: 24, universities: 4, university: 4 },
  { name: 'Chile', code: 'CL', universityRank: 25, universities: 3, university: 3 },
];