export const volcanoData = [
  { name: 'United States', code: 'US', volcanoRank: 1, volcanos: 165 },
  { name: 'Japan', code: 'JP', volcanoRank: 2, volcanos: 120 },
  { name: 'Russia', code: 'RU', volcanoRank: 3, volcanos: 114 },
  { name: 'Indonesia', code: 'ID', volcanoRank: 4, volcanos: 107 },
  { name: 'Chile', code: 'CL', volcanoRank: 5, volcanos: 90 },
  { name: 'Ethiopia', code: 'ET', volcanoRank: 6, volcanos: 50 },
  { name: 'Papua New Guinea', code: 'PG', volcanoRank: 7, volcanos: 39 },
  { name: 'Ecuador', code: 'EC', volcanoRank: 8, volcanos: 36 },
  { name: 'Mexico', code: 'MX', volcanoRank: 9, volcanos: 35 },
  { name: 'Argentina', code: 'AR', volcanoRank: 10, volcanos: 32 },
  { name: 'Canada', code: 'CA', volcanoRank: 11, volcanos: 24 },
  { name: 'Philippines', code: 'PH', volcanoRank: 12, volcanos: 23 },
  { name: 'Kenya', code: 'KE', volcanoRank: 13, volcanos: 21 },
  { name: 'Guatemala', code: 'GT', volcanoRank: 14, volcanos: 20 },
  { name: 'France', code: 'FR', volcanoRank: 15, volcanos: 19 },
  { name: 'El Salvador', code: 'SV', volcanoRank: 16, volcanos: 17 },
  { name: 'United Kingdom', code: 'GB', volcanoRank: 17, volcanos: 14 },
  { name: 'Italy', code: 'IT', volcanoRank: 18, volcanos: 13 },
  { name: 'China', code: 'CN', volcanoRank: 19, volcanos: 10 },
  { name: 'Spain', code: 'ES', volcanoRank: 20, volcanos: 8 },
  { name: 'Turkey', code: 'TR', volcanoRank: 21, volcanos: 7 },
  { name: 'Tanzania', code: 'TZ', volcanoRank: 22, volcanos: 6 },
  { name: 'Madagascar', code: 'MG', volcanoRank: 23, volcanos: 5 },
  { name: 'DR Congo', code: 'CD', volcanoRank: 24, volcanos: 4 },
  { name: 'South Korea', code: 'KR', volcanoRank: 25, volcanos: 3 },
  { name: 'India', code: 'IN', volcanoRank: 26, volcanos: 2 },
  { name: 'Iran', code: 'IR', volcanoRank: 27, volcanos: 1 },
];
