export const worldCupWinsData = [
  { name: 'Brazil', code: 'BR', winsRank: 1, wins: 76, tieGroup: 1 },
  { name: 'Germany', code: 'DE', winsRank: 2, wins: 68, tieGroup: 2 },
  { name: 'Argentina', code: 'AR', winsRank: 3, wins: 47, tieGroup: 3 },
  { name: 'Italy', code: 'IT', winsRank: 4, wins: 45, tieGroup: 4 },
  { name: 'France', code: 'FR', winsRank: 5, wins: 39, tieGroup: 5 },
  { name: 'England', code: 'GB-ENG', winsRank: 6, wins: 32, tieGroup: 6 },
  { name: 'Spain', code: 'ES', winsRank: 7, wins: 31, tieGroup: 7 },
  { name: 'Netherlands', code: 'NL', winsRank: 8, wins: 30, tieGroup: 8 },
  { name: 'Uruguay', code: 'UY', winsRank: 9, wins: 25, tieGroup: 9 },
  { name: 'Belgium', code: 'BE', winsRank: 10, wins: 21, tieGroup: 10 },
  { name: 'Russia', code: 'RU', winsRank: 11, wins: 19, tieGroup: 11 },
  { name: 'Sweden', code: 'SE', winsRank: 11, wins: 19, tieGroup: 11 },
  { name: 'Serbia', code: 'RS', winsRank: 13, wins: 18, tieGroup: 12 },
  { name: 'Portugal', code: 'PT', winsRank: 14, wins: 17, tieGroup: 13 },
  { name: 'Mexico', code: 'MX', winsRank: 14, wins: 17, tieGroup: 13 },
  { name: 'Poland', code: 'PL', winsRank: 14, wins: 17, tieGroup: 13 },
  { name: 'Hungary', code: 'HU', winsRank: 17, wins: 15, tieGroup: 14 },
  { name: 'Switzerland', code: 'CH', winsRank: 18, wins: 14, tieGroup: 15 },
  { name: 'Croatia', code: 'HR', winsRank: 19, wins: 13, tieGroup: 16 },
  { name: 'Czech Republic', code: 'CZ', winsRank: 20, wins: 12, tieGroup: 17 },
  { name: 'Austria', code: 'AT', winsRank: 20, wins: 12, tieGroup: 17 },
  { name: 'Chile', code: 'CL', winsRank: 22, wins: 11, tieGroup: 18 },
  { name: 'Denmark', code: 'DK', winsRank: 23, wins: 9, tieGroup: 19 },
  { name: 'USA', code: 'US', winsRank: 23, wins: 9, tieGroup: 19 },
  { name: 'Colombia', code: 'CO', winsRank: 23, wins: 9, tieGroup: 19 },
  { name: 'Romania', code: 'RO', winsRank: 26, wins: 8, tieGroup: 20 },
  { name: 'Japan', code: 'JP', winsRank: 27, wins: 7, tieGroup: 21 },
  { name: 'South Korea', code: 'KR', winsRank: 27, wins: 7, tieGroup: 21 },
  { name: 'Paraguay', code: 'PY', winsRank: 27, wins: 7, tieGroup: 21 },
  { name: 'Nigeria', code: 'NG', winsRank: 30, wins: 6, tieGroup: 22 },
  { name: 'Costa Rica', code: 'CR', winsRank: 30, wins: 6, tieGroup: 22 },

  { name: 'Senegal', code: 'SN', winsRank: 32, wins: 5, tieGroup: 23 },
  { name: 'Ghana', code: 'GH', winsRank: 32, wins: 5, tieGroup: 23 },
  { name: 'Peru', code: 'PE', winsRank: 32, wins: 5, tieGroup: 23 },
  { name: 'Morocco', code: 'MA', winsRank: 32, wins: 5, tieGroup: 23 },
  { name: 'Cameroon', code: 'CM', winsRank: 32, wins: 5, tieGroup: 23 },
  { name: 'Ecuador', code: 'EC', winsRank: 32, wins: 5, tieGroup: 23 },
  { name: 'Turkey', code: 'TR', winsRank: 32, wins: 5, tieGroup: 23 },

  { name: 'Scotland', code: 'GB-SCT', winsRank: 39, wins: 4, tieGroup: 24 },
  { name: 'Saudi Arabia', code: 'SA', winsRank: 39, wins: 4, tieGroup: 24 },
  { name: 'Australia', code: 'AU', winsRank: 39, wins: 4, tieGroup: 24 },

  { name: 'Bulgaria', code: 'BG', winsRank: 42, wins: 3, tieGroup: 25 },
  { name: 'Iran', code: 'IR', winsRank: 42, wins: 3, tieGroup: 25 },
  { name: 'Algeria', code: 'DZ', winsRank: 42, wins: 3, tieGroup: 25 },
  { name: 'Ivory Coast', code: 'CI', winsRank: 42, wins: 3, tieGroup: 25 },
  { name: 'Northern Ireland', code: 'GB-NIR', winsRank: 42, wins: 3, tieGroup: 25 },
  { name: 'Tunisia', code: 'TN', winsRank: 42, wins: 3, tieGroup: 25 },

  { name: 'South Africa', code: 'ZA', winsRank: 48, wins: 2, tieGroup: 26 },
  { name: 'Ireland', code: 'IE', winsRank: 48, wins: 2, tieGroup: 26 },
  { name: 'Norway', code: 'NO', winsRank: 48, wins: 2, tieGroup: 26 },
  { name: 'East Germany', code: 'DE-DDR', winsRank: 48, wins: 2, tieGroup: 26 },
  { name: 'Greece', code: 'GR', winsRank: 48, wins: 2, tieGroup: 26 },
  { name: 'Ukraine', code: 'UA', winsRank: 48, wins: 2, tieGroup: 26 },

  { name: 'Jamaica', code: 'JM', winsRank: 54, wins: 1, tieGroup: 27 },
  { name: 'Bosnia and Herzegovina', code: 'BA', winsRank: 54, wins: 1, tieGroup: 27 },
  { name: 'Cuba', code: 'CU', winsRank: 54, wins: 1, tieGroup: 27 },
  { name: 'North Korea', code: 'KP', winsRank: 54, wins: 1, tieGroup: 27 },
  { name: 'Slovakia', code: 'SK', winsRank: 54, wins: 1, tieGroup: 27 },
  { name: 'Slovenia', code: 'SI', winsRank: 54, wins: 1, tieGroup: 27 },
  { name: 'Wales', code: 'GB-WLS', winsRank: 54, wins: 1, tieGroup: 27 },

  { name: 'New Zealand', code: 'NZ', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Honduras', code: 'HN', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Angola', code: 'AO', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Israel', code: 'IL', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Egypt', code: 'EG', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Iceland', code: 'IS', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Kuwait', code: 'KW', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Trinidad and Tobago', code: 'TT', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Bolivia', code: 'BO', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Iraq', code: 'IQ', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Togo', code: 'TG', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Qatar', code: 'QA', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Indonesia', code: 'ID', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Panama', code: 'PA', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'United Arab Emirates', code: 'AE', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'China', code: 'CN', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Canada', code: 'CA', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Haiti', code: 'HT', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'RD Congo', code: 'CD', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'El Salvador', code: 'SV', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Cape Verde', code: 'CV', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Curacao', code: 'CW', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Jordan', code: 'JO', winsRank: 61, wins: 0, tieGroup: 28 },
  { name: 'Uzbekistan', code: 'UZ', winsRank: 61, wins: 0, tieGroup: 28 },
];