export const worldCupGoalsScoredData = [
  { name: 'Brazil', code: 'BR', goalsRank: 1, goalsScored: 237, tieGroup: 1 },
  { name: 'Germany', code: 'DE', goalsRank: 2, goalsScored: 232, tieGroup: 2 },
  { name: 'Argentina', code: 'AR', goalsRank: 3, goalsScored: 152, tieGroup: 3 },
  { name: 'France', code: 'FR', goalsRank: 4, goalsScored: 136, tieGroup: 4 },
  { name: 'Italy', code: 'IT', goalsRank: 5, goalsScored: 128, tieGroup: 5 },
  { name: 'Spain', code: 'ES', goalsRank: 6, goalsScored: 108, tieGroup: 6 },
  { name: 'England', code: 'GB-ENG', goalsRank: 7, goalsScored: 104, tieGroup: 7 },
  { name: 'Netherlands', code: 'NL', goalsRank: 8, goalsScored: 96, tieGroup: 8 },
  { name: 'Uruguay', code: 'UY', goalsRank: 9, goalsScored: 89, tieGroup: 9 },
  { name: 'Hungary', code: 'HU', goalsRank: 10, goalsScored: 87, tieGroup: 10 },
  { name: 'Sweden', code: 'SE', goalsRank: 11, goalsScored: 80, tieGroup: 11 },
  { name: 'Russia', code: 'RU', goalsRank: 12, goalsScored: 77, tieGroup: 12 },
  { name: 'Serbia', code: 'RS', goalsRank: 13, goalsScored: 71, tieGroup: 13 },
  { name: 'Belgium', code: 'BE', goalsRank: 14, goalsScored: 69, tieGroup: 14 },
  { name: 'Mexico', code: 'MX', goalsRank: 15, goalsScored: 62, tieGroup: 15 },
  { name: 'Portugal', code: 'PT', goalsRank: 16, goalsScored: 61, tieGroup: 16 },
  { name: 'Switzerland', code: 'CH', goalsRank: 17, goalsScored: 55, tieGroup: 17 },
  { name: 'Poland', code: 'PL', goalsRank: 18, goalsScored: 49, tieGroup: 18 },
  { name: 'Czech Republic', code: 'CZ', goalsRank: 19, goalsScored: 47, tieGroup: 19 },
  { name: 'Croatia', code: 'HR', goalsRank: 20, goalsScored: 43, tieGroup: 20 },
  { name: 'Austria', code: 'AT', goalsRank: 20, goalsScored: 43, tieGroup: 20 },
  { name: 'Chile', code: 'CL', goalsRank: 22, goalsScored: 40, tieGroup: 21 },
  { name: 'USA', code: 'US', goalsRank: 22, goalsScored: 40, tieGroup: 21 },
  { name: 'South Korea', code: 'KR', goalsRank: 24, goalsScored: 39, tieGroup: 22 },
  { name: 'Colombia', code: 'CO', goalsRank: 25, goalsScored: 32, tieGroup: 23 },
  { name: 'Denmark', code: 'DK', goalsRank: 26, goalsScored: 31, tieGroup: 24 },
  { name: 'Romania', code: 'RO', goalsRank: 27, goalsScored: 30, tieGroup: 25 },
  { name: 'Paraguay', code: 'PY', goalsRank: 27, goalsScored: 30, tieGroup: 25 },
  { name: 'Japan', code: 'JP', goalsRank: 29, goalsScored: 25, tieGroup: 26 },
  { name: 'Scotland', code: 'GB-SCT', goalsRank: 29, goalsScored: 25, tieGroup: 26 },
  { name: 'Nigeria', code: 'NG', goalsRank: 31, goalsScored: 23, tieGroup: 27 },
  { name: 'Costa Rica', code: 'CR', goalsRank: 32, goalsScored: 22, tieGroup: 28 },
  { name: 'Cameroon', code: 'CM', goalsRank: 32, goalsScored: 22, tieGroup: 28 },
  { name: 'Bulgaria', code: 'BG', goalsRank: 32, goalsScored: 22, tieGroup: 28 },
  { name: 'Peru', code: 'PE', goalsRank: 35, goalsScored: 21, tieGroup: 29 },
  { name: 'Turkey', code: 'TR', goalsRank: 36, goalsScored: 20, tieGroup: 30 },
  { name: 'Morocco', code: 'MA', goalsRank: 36, goalsScored: 20, tieGroup: 30 },
  { name: 'Ghana', code: 'GH', goalsRank: 38, goalsScored: 18, tieGroup: 31 },
  { name: 'Australia', code: 'AU', goalsRank: 39, goalsScored: 17, tieGroup: 32 },
  { name: 'Senegal', code: 'SN', goalsRank: 40, goalsScored: 16, tieGroup: 33 },
  { name: 'Ecuador', code: 'EC', goalsRank: 41, goalsScored: 14, tieGroup: 34 },
  { name: 'Saudi Arabia', code: 'SA', goalsRank: 41, goalsScored: 14, tieGroup: 34 },
  { name: 'Tunisia', code: 'TN', goalsRank: 41, goalsScored: 14, tieGroup: 34 },
  { name: 'Iran', code: 'IR', goalsRank: 44, goalsScored: 13, tieGroup: 35 },
  { name: 'Algeria', code: 'DZ', goalsRank: 44, goalsScored: 13, tieGroup: 35 },
  { name: 'Ivory Coast', code: 'CI', goalsRank: 44, goalsScored: 13, tieGroup: 35 },
  { name: 'Northern Ireland', code: 'GB-NIR', goalsRank: 44, goalsScored: 13, tieGroup: 35 },
  { name: 'South Africa', code: 'ZA', goalsRank: 48, goalsScored: 11, tieGroup: 36 },
  { name: 'Ireland', code: 'IE', goalsRank: 49, goalsScored: 10, tieGroup: 37 },
  { name: 'Norway', code: 'NO', goalsRank: 50, goalsScored: 7, tieGroup: 38 },
  { name: 'North Korea', code: 'KP', goalsRank: 51, goalsScored: 6, tieGroup: 39 },
  { name: 'Greece', code: 'GR', goalsRank: 52, goalsScored: 5, tieGroup: 40 },
  { name: 'East Germany', code: 'DE-DDR', goalsRank: 52, goalsScored: 5, tieGroup: 40 },
  { name: 'Ukraine', code: 'UA', goalsRank: 52, goalsScored: 5, tieGroup: 40 },
  { name: 'Wales', code: 'GB-WLS', goalsRank: 52, goalsScored: 5, tieGroup: 40 },
  { name: 'Cuba', code: 'CU', goalsRank: 52, goalsScored: 5, tieGroup: 40 },
  { name: 'Slovakia', code: 'SK', goalsRank: 52, goalsScored: 5, tieGroup: 40 },
  { name: 'Slovenia', code: 'SI', goalsRank: 52, goalsScored: 5, tieGroup: 40 },
  { name: 'Egypt', code: 'EG', goalsRank: 52, goalsScored: 5, tieGroup: 40 },
  { name: 'Bosnia and Herzegovina', code: 'BA', goalsRank: 60, goalsScored: 4, tieGroup: 41 },
  { name: 'New Zealand', code: 'NZ', goalsRank: 60, goalsScored: 4, tieGroup: 41 },
  { name: 'Jamaica', code: 'JM', goalsRank: 62, goalsScored: 3, tieGroup: 42 },
  { name: 'Honduras', code: 'HN', goalsRank: 62, goalsScored: 3, tieGroup: 42 },
  { name: 'Iceland', code: 'IS', goalsRank: 64, goalsScored: 2, tieGroup: 43 },
  { name: 'Kuwait', code: 'KW', goalsRank: 64, goalsScored: 2, tieGroup: 43 },
  { name: 'Panama', code: 'PA', goalsRank: 64, goalsScored: 2, tieGroup: 43 },
  { name: 'United Arab Emirates', code: 'AE', goalsRank: 64, goalsScored: 2, tieGroup: 43 },
  { name: 'Haiti', code: 'HT', goalsRank: 64, goalsScored: 2, tieGroup: 43 },
  { name: 'Canada', code: 'CA', goalsRank: 64, goalsScored: 2, tieGroup: 43 },
  { name: 'Angola', code: 'AO', goalsRank: 70, goalsScored: 1, tieGroup: 44 },
  { name: 'Israel', code: 'IL', goalsRank: 70, goalsScored: 1, tieGroup: 44 },
  { name: 'Bolivia', code: 'BO', goalsRank: 70, goalsScored: 1, tieGroup: 44 },
  { name: 'Iraq', code: 'IQ', goalsRank: 70, goalsScored: 1, tieGroup: 44 },
  { name: 'Togo', code: 'TG', goalsRank: 70, goalsScored: 1, tieGroup: 44 },
  { name: 'Qatar', code: 'QA', goalsRank: 70, goalsScored: 1, tieGroup: 44 },
  { name: 'El Salvador', code: 'SV', goalsRank: 70, goalsScored: 1, tieGroup: 44 },
  { name: 'Trinidad and Tobago', code: 'TT', goalsRank: 77, goalsScored: 0, tieGroup: 45 },
  { name: 'Indonesia', code: 'ID', goalsRank: 77, goalsScored: 0, tieGroup: 45 },
  { name: 'China', code: 'CN', goalsRank: 77, goalsScored: 0, tieGroup: 45 },
  { name: 'RD Congo', code: 'CD', goalsRank: 77, goalsScored: 0, tieGroup: 45 },
  { name: 'Cape Verde', code: 'CV', goalsRank: 77, goalsScored: 0, tieGroup: 45 },
  { name: 'Curacao', code: 'CW', goalsRank: 77, goalsScored: 0, tieGroup: 45 },
  { name: 'Jordan', code: 'JO', goalsRank: 77, goalsScored: 0, tieGroup: 45 },
  { name: 'Uzbekistan', code: 'UZ', goalsRank: 77, goalsScored: 0, tieGroup: 45 },
];