export const worldCupAppearancesData = [
  { name: 'Brazil', code: 'BR', appearancesRank: 1, appearances: 23, tieGroup: 1 },
  { name: 'Germany', code: 'DE', appearancesRank: 2, appearances: 21, tieGroup: 2 },
  { name: 'Argentina', code: 'AR', appearancesRank: 3, appearances: 19, tieGroup: 3 },
  { name: 'Italy', code: 'IT', appearancesRank: 4, appearances: 18, tieGroup: 4 },
  { name: 'Mexico', code: 'MX', appearancesRank: 4, appearances: 18, tieGroup: 4 },
  { name: 'France', code: 'FR', appearancesRank: 6, appearances: 17, tieGroup: 5 },
  { name: 'England', code: 'GB-ENG', appearancesRank: 6, appearances: 17, tieGroup: 5 },
  { name: 'Spain', code: 'ES', appearancesRank: 6, appearances: 17, tieGroup: 5 },
  { name: 'Belgium', code: 'BE', appearancesRank: 9, appearances: 15, tieGroup: 6 },
  { name: 'Uruguay', code: 'UY', appearancesRank: 9, appearances: 15, tieGroup: 6 },
  { name: 'Sweden', code: 'SE', appearancesRank: 11, appearances: 13, tieGroup: 7 },
  { name: 'Serbia', code: 'RS', appearancesRank: 11, appearances: 13, tieGroup: 7 },
  { name: 'Switzerland', code: 'CH', appearancesRank: 11, appearances: 13, tieGroup: 7 },
  { name: 'South Korea', code: 'KR', appearancesRank: 14, appearances: 12, tieGroup: 8 },
  { name: 'USA', code: 'US', appearancesRank: 14, appearances: 12, tieGroup: 8 },
  { name: 'Netherlands', code: 'NL', appearancesRank: 14, appearances: 12, tieGroup: 8 },
  { name: 'Russia', code: 'RU', appearancesRank: 17, appearances: 11, tieGroup: 9 },
  { name: 'Czech Republic', code: 'CZ', appearancesRank: 18, appearances: 10, tieGroup: 10 },
  { name: 'Portugal', code: 'PT', appearancesRank: 19, appearances: 9, tieGroup: 11 },
  { name: 'Poland', code: 'PL', appearancesRank: 19, appearances: 9, tieGroup: 11 },
  { name: 'Hungary', code: 'HU', appearancesRank: 19, appearances: 9, tieGroup: 11 },
  { name: 'Austria', code: 'AT', appearancesRank: 19, appearances: 9, tieGroup: 11 },
  { name: 'Chile', code: 'CL', appearancesRank: 19, appearances: 9, tieGroup: 11 },
  { name: 'Paraguay', code: 'PY', appearancesRank: 19, appearances: 9, tieGroup: 11 },
  { name: 'Scotland', code: 'GB-SCT', appearancesRank: 19, appearances: 9, tieGroup: 11 },
  { name: 'Cameroon', code: 'CM', appearancesRank: 26, appearances: 8, tieGroup: 12 },
  { name: 'Japan', code: 'JP', appearancesRank: 26, appearances: 8, tieGroup: 12 },
  { name: 'Saudi Arabia', code: 'SA', appearancesRank: 28, appearances: 7, tieGroup: 13 },
  { name: 'Iran', code: 'IR', appearancesRank: 28, appearances: 7, tieGroup: 13 },
  { name: 'Morocco', code: 'MA', appearancesRank: 28, appearances: 7, tieGroup: 13 },
  { name: 'Croatia', code: 'HR', appearancesRank: 28, appearances: 7, tieGroup: 13 },
  { name: 'Colombia', code: 'CO', appearancesRank: 28, appearances: 7, tieGroup: 13 },
  { name: 'Romania', code: 'RO', appearancesRank: 28, appearances: 7, tieGroup: 13 },
  { name: 'Bulgaria', code: 'BG', appearancesRank: 28, appearances: 7, tieGroup: 13 },
  { name: 'Australia', code: 'AU', appearancesRank: 28, appearances: 7, tieGroup: 13 },
  { name: 'Tunisia', code: 'TN', appearancesRank: 28, appearances: 7, tieGroup: 13 },
  { name: 'Nigeria', code: 'NG', appearancesRank: 37, appearances: 6, tieGroup: 14 },
  { name: 'Costa Rica', code: 'CR', appearancesRank: 37, appearances: 6, tieGroup: 14 },
  { name: 'Denmark', code: 'DK', appearancesRank: 37, appearances: 6, tieGroup: 14 },
  { name: 'Ecuador', code: 'EC', appearancesRank: 40, appearances: 5, tieGroup: 15 },
  { name: 'Ghana', code: 'GH', appearancesRank: 40, appearances: 5, tieGroup: 15 },
  { name: 'Peru', code: 'PE', appearancesRank: 40, appearances: 5, tieGroup: 15 },
  { name: 'Algeria', code: 'DZ', appearancesRank: 40, appearances: 5, tieGroup: 15 },
  { name: 'Senegal', code: 'SN', appearancesRank: 44, appearances: 4, tieGroup: 16 },
  { name: 'Ivory Coast', code: 'CI', appearancesRank: 44, appearances: 4, tieGroup: 16 },
  { name: 'South Africa', code: 'ZA', appearancesRank: 44, appearances: 4, tieGroup: 16 },
  { name: 'Norway', code: 'NO', appearancesRank: 44, appearances: 4, tieGroup: 16 },
  { name: 'Egypt', code: 'EG', appearancesRank: 44, appearances: 4, tieGroup: 16 },
  { name: 'Ireland', code: 'IE', appearancesRank: 49, appearances: 3, tieGroup: 17 },
  { name: 'Northern Ireland', code: 'GB-NIR', appearancesRank: 49, appearances: 3, tieGroup: 17 },
  { name: 'Turkey', code: 'TR', appearancesRank: 49, appearances: 3, tieGroup: 17 },
  { name: 'Greece', code: 'GR', appearancesRank: 49, appearances: 3, tieGroup: 17 },
  { name: 'Canada', code: 'CA', appearancesRank: 49, appearances: 3, tieGroup: 17 },
  { name: 'New Zealand', code: 'NZ', appearancesRank: 49, appearances: 3, tieGroup: 17 },
  { name: 'Honduras', code: 'HN', appearancesRank: 49, appearances: 3, tieGroup: 17 },
  { name: 'Bolivia', code: 'BO', appearancesRank: 49, appearances: 3, tieGroup: 17 },
  { name: 'Wales', code: 'GB-WLS', appearancesRank: 57, appearances: 2, tieGroup: 18 },
  { name: 'Slovenia', code: 'SI', appearancesRank: 57, appearances: 2, tieGroup: 18 },
  { name: 'North Korea', code: 'KP', appearancesRank: 57, appearances: 2, tieGroup: 18 },
  { name: 'Bosnia and Herzegovina', code: 'BA', appearancesRank: 57, appearances: 2, tieGroup: 18 },
  { name: 'Qatar', code: 'QA', appearancesRank: 57, appearances: 2, tieGroup: 18 },
  { name: 'Panama', code: 'PA', appearancesRank: 57, appearances: 2, tieGroup: 18 },
  { name: 'Haiti', code: 'HT', appearancesRank: 57, appearances: 2, tieGroup: 18 },
  { name: 'RD Congo', code: 'CD', appearancesRank: 57, appearances: 2, tieGroup: 18 },
  { name: 'El Salvador', code: 'SV', appearancesRank: 57, appearances: 2, tieGroup: 18 },
  { name: 'Iraq', code: 'IQ', appearancesRank: 57, appearances: 2, tieGroup: 18 },
  { name: 'Slovakia', code: 'SK', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Ukraine', code: 'UA', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'East Germany', code: 'DE-DDR', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Angola', code: 'AO', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Israel', code: 'IL', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Iceland', code: 'IS', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Kuwait', code: 'KW', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Trinidad and Tobago', code: 'TT', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Togo', code: 'TG', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Jamaica', code: 'JM', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Cuba', code: 'CU', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Indonesia', code: 'ID', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'China', code: 'CN', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Cape Verde', code: 'CV', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Curacao', code: 'CW', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Jordan', code: 'JO', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'Uzbekistan', code: 'UZ', appearancesRank: 67, appearances: 1, tieGroup: 19 },
  { name: 'United Arab Emirates', code: 'AE', appearancesRank: 67, appearances: 1, tieGroup: 19 },
];